### ISSUE TITLE
Crash When Launch APP：java.lang.VerifyError

### ISSUE THREAD

**Issue by ASCE1885** [facebook/redex#103]
``` java
                                                                          java.lang.VerifyError: Verifier rejected class com.pingan.anydoor.base.net.b due to bad method void com.pingan.anydoor.base.net.b.bz() (declaration of 'com.pingan.anydoor.base.net.b' appears in /data/app/com.pafinancialtech.pafs-1/base.apk:classes2.dex)
                                                                              at com.pingan.anydoor.base.net.a.a(textOn:625)
                                                                              at com.pingan.anydoor.base.net.a.a(textOn:359)
                                                                              at com.pingan.anydoor.common.http.a.a(text/plain; charset=UTF-8:60)
                                                                              at com.pingan.anydoor.common.a.bQ(text2_a:128)
                                                                              at com.pingan.anydoor.PAAnydoor.initAnydoorInfo(wx9a459cb031d8b13b:298)
                                                                              at com.pingan.fstandard.anydoor.PAAnyDoorHelper.initAnydoor(widthPadding:58)
                                                                              at com.pingan.fstandard.HomeApplication.onCreate(wildcardType:61)
                                                                              at com.pingan.fstandard.paff.activity.PAFFApplication.onCreate(trasPasswordText:18)
                                                                              at com.pingan.fstandard.paff.activity.PAFFDebugApplication.onCreate(trasPassword:14)
                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5010)
                                                                              at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:145)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by tiffyangel89** [comment]
Javalava.553

**Comment by shanenay** [comment]
Can you run 'dexdump -d' on the classes2.dex, and then paste the class in question?  It has to be from the same build as what generated the error because looks like you've got class-renaming turned on.  (Ideally disabling it while debugging makes life easier)

Also if there's some more context than that from logcat it would be helpful.  Usually above a message like this there would be some more context to help pin point the problem.

**Comment by justinjhendrick** [comment]
closing due to age
