### ISSUE TITLE
incompatible with Annotation lib

### ISSUE THREAD

**Issue by c1024** [facebook/redex#112]
I use let (https://github.com/canelmas/let) to handle new Android runtime permission model .
When I use redex optimize apk , after install , crash after launch .
I get the crash stack trace below.
`Attempt to invoke virtual method 'java.lang.annotation.Annotation java.lang.reflect.Method.getAnnotation(java.lang.Class)' on a null object reference
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.annotation.Annotation java.lang.reflect.Method.getAnnotation(java.lang.Class)' on a null object reference
                                                                    at com.canelmas.let.RuntimePermissionRequest.proceed(Unknown Source)
                                                                    at com.canelmas.let.RuntimePermissionRequest.proceed(Unknown Source)
                                                                    at com.canelmas.let.LetAspect.ajc$inlineAccessMethod$com_canelmas_let_LetAspect$com_canelmas_let_RuntimePermissionRequest$proceed(Unknown Source)
                                                                    at com.canelmas.let.LetAspect.annotatedMethods(Unknown Source)
                                                                    at com.city.club.interflow.JobCategoryNew.getCurLocation(Unknown Source)
                                                                    at com.city.club.interflow.JobCategoryNew.onActivityCreated(Unknown Source)
                                                                    at android.support.v4.app.Fragment.performActivityCreated(Unknown Source)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                                                    at android.support.v4.app.BackStackRecord.run(Unknown Source)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source)
                                                                    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source)
                                                                    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(Unknown Source)
                                                                    at android.support.v4.view.ViewPager.populate(Unknown Source)
                                                                    at android.support.v4.view.ViewPager.populate(Unknown Source)
                                                                    at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    at android.view.View.measure(View.java:18794)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)`

I find SimpleInlinePass could cause the problem , the other pass may also cause the problem.

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this problem after updating to the most recent version. Feel free to re-open the issue or create a new one.
