### ISSUE TITLE
dump_classes_from_hprof.py error

### ISSUE THREAD

**Issue by williamycyh** [facebook/redex#119]
Traceback (most recent call last):
  File "tools/hprof/dump_classes_from_hprof.py", line 1261, in <module>
    hp = parse_filename(args.hprof)
  File "tools/hprof/dump_classes_from_hprof.py", line 53, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "tools/hprof/dump_classes_from_hprof.py", line 45, in parse_hprof_dump
    hprof_data.resolve()
  File "tools/hprof/dump_classes_from_hprof.py", line 862, in resolve
    clazz.resolve(self)
  File "tools/hprof/dump_classes_from_hprof.py", line 555, in resolve
    assert name not in self.fields.**dict**
AssertionError

I got this error with python 2.7.6
Help me please...

**Comment by williamycyh** [comment]
I got this error with python 2.7.6.
i have no idea where is wrong. 
Help me please...

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.

**Comment by maocanmao** [comment]
I use newest version and python 2.7.16, still got this error

**Comment by jeneyloo** [comment]
still got this error on newest version with python 2.7.14

**Comment by justinjhendrick** [comment]
Looking more closely at the error message. It seems this might happen when there are duplicate static fields in the hprof.

Could you print out what `name` is and the contents of `self.fields.__dict__` when the assertion occurs?

**Comment by jeneyloo** [comment]
@justinjhendrick when the assertion occurs
name = a
key in `self.fields.__dict__` is [a,__hprof_a,$classOverhead]

**Comment by justinjhendrick** [comment]
Yep, looks like duplicate names. I'm not sure how this script works, nor do I know very much about hprof files. But, is it possible to alter your hprof file to not have duplicate names? Or possibly alter the script to accept duplicate names?

**Comment by jeneyloo** [comment]
@justinjhendrick thanks for your suggestion
I alter the script to accept duplicate names, but got below error
```
Traceback (most recent call last):
  File "/tools/hprof/dump_classes_from_hprof.py", line 1265, in <module>
    hp = parse_filename(args.hprof)
  File "/tools/hprof/dump_classes_from_hprof.py", line 57, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "/tools/hprof/dump_classes_from_hprof.py", line 49, in parse_hprof_dump
    hprof_data.resolve()
  File "/tools/hprof/dump_classes_from_hprof.py", line 889, in resolve
    root.resolve(self)
  File "/tools/hprof/dump_classes_from_hprof.py", line 304, in resolve
    self.obj = hprof_data.object_id_dict[self.object_id]
KeyError: 344654400
```
I will try other way to  generate class list for interdex

**Comment by Zane96** [comment]
--- a/tools/hprof/dump_classes_from_hprof.py
+++ b/tools/hprof/dump_classes_from_hprof.py
@@ -613,7 +613,7 @@ class HprofClass(HprofObject):
             # Don't want to overwrite Python internal fields - like __dict__
             if name in self.fields.__dict__:
                 name = "__hprof_" + name
-                assert name not in self.fields.__dict__
+                # assert name not in self.fields.__dict__
             setattr(self.fields, name, static_field.value)
 
     def outgoing_references_to(self, obj):
@@ -726,10 +726,13 @@ class HprofObjectArray(HprofObject):
 
         for i, obj in enumerate(self.array_values):
             # Resolve non-null value to parsed instance
-            if obj != 0:
-                self.array_values[i] = hprof_data.object_id_dict[obj]
-            else:
-                self.array_values[i] = None
+            try:
+                if obj != 0:
+                    self.array_values[i] = hprof_data.object_id_dict[obj]
+                else:
+                    self.array_values[i] = None
+            except:
+                print ("L")
 
     def outgoing_references_to(self, obj):
         return self.outgoing_references(lambda x: x is obj)
@@ -972,7 +975,7 @@ class HprofData(object):
                             self.class_name_dict[clazz.name]
                         )
                     self.dupe_class_dict[clazz.name].append(clazz)
-                    print("Warning: duplicate class: %s" % clazz.name)
+                    #print("Warning: duplicate class: %s" % clazz.name)
                 else:
                     self.class_name_dict[clazz.name] = clazz
         # Fix up all classes to derive from java.lang.Class

this patch can fix this bug

**Comment by Zane96** [comment]
`--- a/tools/hprof/dump_classes_from_hprof.py
+++ b/tools/hprof/dump_classes_from_hprof.py
@@ -613,7 +613,7 @@ class HprofClass(HprofObject):
             # Don't want to overwrite Python internal fields - like __dict__
             if name in self.fields.__dict__:
                 name = "__hprof_" + name
-                assert name not in self.fields.__dict__
+                # assert name not in self.fields.__dict__
             setattr(self.fields, name, static_field.value)
 
     def outgoing_references_to(self, obj):
@@ -726,10 +726,13 @@ class HprofObjectArray(HprofObject):
 
         for i, obj in enumerate(self.array_values):
             # Resolve non-null value to parsed instance
-            if obj != 0:
-                self.array_values[i] = hprof_data.object_id_dict[obj]
-            else:
-                self.array_values[i] = None
+            try:
+                if obj != 0:
+                    self.array_values[i] = hprof_data.object_id_dict[obj]
+                else:
+                    self.array_values[i] = None
+            except:
+                print ("L")
 
     def outgoing_references_to(self, obj):
         return self.outgoing_references(lambda x: x is obj)
@@ -972,7 +975,7 @@ class HprofData(object):
                             self.class_name_dict[clazz.name]
                         )
                     self.dupe_class_dict[clazz.name].append(clazz)
-                    print("Warning: duplicate class: %s" % clazz.name)
+                    #print("Warning: duplicate class: %s" % clazz.name)
                 else:
                     self.class_name_dict[clazz.name] = clazz
         # Fix up all classes to derive from java.lang.Class`

this patch can fix bug
