### ISSUE TITLE
Error with dump_classes_from_hprof.py

### ISSUE THREAD

**Issue by mdekermadec** [facebook/redex#124]
Hello,

I have an error with dump_classes_from_hprof.py script:

```
python redex/tools/hprof/dump_classes_from_hprof.py --hprof redex-chromium.hprof > redex-chromium.txt
```

```
Traceback (most recent call last):
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 1261, in <module>
    hp = parse_filename(args.hprof)
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 53, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 45, in parse_hprof_dump
    hprof_data.resolve()
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 862, in resolve
    clazz.resolve(self)
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 547, in resolve
    static_field.value = hprof_data.object_id_dict[static_field.value]
KeyError: 670

```

I got this error with python 2.7.6.

My hprof is available here:

[redex-chromium.hprof.zip](https://github.com/facebook/redex/files/240108/redex-chromium.hprof.zip)

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
