### ISSUE TITLE
Assertion `cls->get_access() & ACC_INTERFACE' failed

### ISSUE THREAD

**Issue by rohanpatel2602** [facebook/redex#138]
If I run redex with "ReBindRefsPass" I get the following error:

```
libredex/Resolver.cpp:37: auto (anonymous namespace)::resolve_intf_methodref(DexType *, DexMethod *)::(anonymous class)::operator()(const DexClass *) const: assertion `cls->get_access() & ACC_INTERFACE' failed.

0   redex-all                           0x0000000106df8cc4 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9726652a _sigtramp + 26
2   ???                                 0x737361203a74736e 0x0 + 8319099727730996078
3   libsystem_c.dylib                   0x00007fff8aa0937b abort + 129
4   redex-all                           0x0000000106df8c81 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000106e21578 _ZN12_GLOBAL__N_122resolve_intf_methodrefEP7DexTypeP9DexMethod + 200
6   redex-all                           0x0000000106e734ef _ZN14ReBindRefsPass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 1407
7   redex-all                           0x0000000106e180ba _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 378
8   redex-all                           0x0000000106dead17 main + 2263
9   libdyld.dylib                       0x00007fff959a95ad start + 1
10  ???                                 0x0000000000000009 0x0 + 9
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 788, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 744, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 115, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/bl/nqcwxkbn79jdd3sqxh0q4khw0000gn/T/tmp6xqujm5q.redex_extracted_apk --outdir /var/folders/bl/nqcwxkbn79jdd3sqxh0q4khw0000gn/T/tmpuvv0jffx.redex_dexen --config /var/folders/bl/nqcwxkbn79jdd3sqxh0q4khw0000gn/T/tmpt6fh12gq/rewritten.config /var/folders/bl/nqcwxkbn79jdd3sqxh0q4khw0000gn/T/tmpuvv0jffx.redex_dexen/dex0/classes.dex /var/folders/bl/nqcwxkbn79jdd3sqxh0q4khw0000gn/T/tmpuvv0jffx.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6
```

If I remove the "ReBindRefsPass" from my config file then it is fine.

**Comment by eveliotc** [comment]
Same issue here with the latest public Lyft build http://evel.io/static/builds/lyft-android-50522.apk

```
libredex/Resolver.cpp:37: auto (anonymous namespace)::resolve_intf_methodref(DexType *, DexMethod *)::(anonymous class)::operator()(const DexClass *) const: assertion `cls->get_access() & ACC_INTERFACE' failed.

0   redex-all                           0x0000000104930c24 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff8f86352a _sigtramp + 26
2   ???                                 0x737361203a74736e 0x0 + 8319099727730996078
3   libsystem_c.dylib                   0x00007fff8edac6e7 abort + 129
4   redex-all                           0x0000000104930be1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x000000010495b038 _ZN12_GLOBAL__N_122resolve_intf_methodrefEP7DexTypeP9DexMethod + 200
6   redex-all                           0x00000001049afccf _ZN14ReBindRefsPass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 1407
7   redex-all                           0x000000010495168a _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 378
8   redex-all                           0x0000000104926341 main + 2689
9   libdyld.dylib                       0x00007fff9c5f05ad start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 797, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 752, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 114, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/3p/_93htw1x3f75j7yn3dl56dx80000gp/T/tmpg_o6v4pz.redex_extracted_apk --outdir /var/folders/3p/_93htw1x3f75j7yn3dl56dx80000gp/T/tmpvy1arvfx.redex_dexen /var/folders/3p/_93htw1x3f75j7yn3dl56dx80000gp/T/tmpvy1arvfx.redex_dexen/dex0/classes.dex /var/folders/3p/_93htw1x3f75j7yn3dl56dx80000gp/T/tmpvy1arvfx.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6
```

**Comment by bertmaher** [comment]
Hey, sorry for the extremely long lag on this.  I've coincidentally fixed this issue on master; mind giving it another spin?

**Comment by bertmaher** [comment]
Can you ping the other issues?  I'm trying to go through the backlog, I'd like to prioritize the ones that people are still hitting.  Thanks!
