### ISSUE TITLE
KeyError: 'RenameClassesPass'

### ISSUE THREAD

**Issue by ly20050516** [facebook/redex#142]
Hi,When I configure all of pass,I got the error as follow,is it a bug?
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 788, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 770, in run_redex
    args.proguard_map)
  File "/usr/local/bin/redex", line 530, in merge_proguard_map_with_rename_output
    redex_rename_map_path = config_dict['RenameClassesPass']['class_rename']
KeyError: 'RenameClassesPass'

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
