### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by dinuscxj** [facebook/redex#154]
redex the signed apk, [/Users/dinus/Documents/workspace/wakaka/build/outputs/apk/rx_wkk_4_43_0_100002_google_play.apk], ...
输入wakaka的密钥口令: jarsigner: 必须输入密钥口令
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 782, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 753, in run_redex
    args.keyalias, args.keypass)
  File "/usr/local/bin/redex", line 517, in create_output_apk
    stdout=sys.stderr)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jarsigner', '-sigalg', 'SHA1withRSA', '-digestalg', 'SHA1', '-keystore', '/Users/dinus/Documents/workspace/wakaka/gifshow.keystore', '-storepass', '*******', '/var/folders/74/31vmdf1x41zg7d459hl4hpqw0000gn/T/tmp8arbrvd6.redex_unaligned/redex-unaligned.apk', 'wakaka']' returned non-zero exit status 1

**Comment by dinuscxj** [comment]
@bernieperez

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
