### ISSUE TITLE
Redex not considering multidex behaviour

### ISSUE THREAD

**Issue by abhishesh-srivastava** [facebook/redex#173]
I am trying to run redex on multidex app. 
It has two dex: classes.dex(primary) and classes1.dex
When I run redex on my app, app crashed with NoClassDefFoundError .
I noticed app is crashing for classes which are in classes1.dex
I decompiled redex-out.apk and found it is single dex and none of the entries for classes of classes1.dex is there in redex-out.apk's classes.dex. Only entries of classes.dex is present in redex-out.apk's classes.dex

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzmt;
                                                               at com.google.android.gms.measurement.internal.zzaa.zzl(Unknown Source)
                                                               at com.google.android.gms.measurement.internal.zzw.<init>(Unknown Source)
                                                               at com.google.android.gms.measurement.internal.zzaa.zzDj(Unknown Source)
                                                               at com.google.android.gms.measurement.internal.zzw.zzaT(Unknown Source)
                                                               at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1789)
                                                               at android.content.ContentProvider.attachInfo(ContentProvider.java:1764)
                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:6762)
                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:6357)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6297)
                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:158)
                                                               at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by bertmaher** [comment]
Sigh, I've seen so many different multidex formats, and this is yet another one (sadly I mostly see FB's multidex formats, which I'm sure are different from the rest of the world's).  Redex expects secondaries to be named starting with classes2.dex (not classes1.dex).  This should be a fairly easy fix though, I'll try to knock it out soon.

**Comment by abhishesh-srivastava** [comment]
second dex is starting with classes2.dex only, ClassyShark tool messed up with dex(which I used to decompile)

Following are the logs which I printed on terminal by modifying redex script. May be this can help,

```
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
APK: /var/folders/4q/_nrbr1k96kj3mvphspsh9p84kx_q1g/T/tmpPxpCoG.redex_extracted_apk
DEX: /var/folders/4q/_nrbr1k96kj3mvphspsh9p84kx_q1g/T/tmpe2Y7Bt.redex_dexen
Dex format: 2
Dex result /var/folders/4q/_nrbr1k96kj3mvphspsh9p84kx_q1g/T/tmpe2Y7Bt.redex_dexen/classes2.dex
move dexen to directories classes.dex
move dexen to directories classes2.dex
Unpacking APK finished in 2.48 seconds
Using config (default)
Using binary (default)
Replacing /tmp in config with /var/folders/4q/_nrbr1k96kj3mvphspsh9p84kx_q1g/T/tmpqFofgF
Running redex-all on 2 dex files 
Running redex binary at /usr/local/bin/redex-all
resultCode is: 0
Dex processing finished in 7.70 seconds
Repacking dex files
Creating output apk
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2038-01-03) or after any future revocation date.
Creating output APK finished in 6.57 seconds
Skipping line number map copy, since no file found to copy
Skipping stats copy, since no file found to copy
Skipping src strings map copy, since no file found to copy
Skipping method id map copy, since no file found to copy
Skipping rename map merging, because we didn't run the rename pass
```

**Comment by bertmaher** [comment]
Can you share the APK?  I'm honestly not sure what's going wrong, since redex supports native multidex.

**Comment by zjf1023** [comment]
I have met the same problem. I missed classes2.dex after using redex。
![image](https://cloud.githubusercontent.com/assets/5461196/18777403/847fcecc-81a1-11e6-8859-38d567af95b2.png)
![image](https://cloud.githubusercontent.com/assets/5461196/18777405/8b50aa1e-81a1-11e6-9dbc-6e3e3c8e1b84.png)

**Comment by ufsoares-luizalabs** [comment]
I can confirm this bug☝️

**Comment by bertmaher** [comment]
I don't think the bug is in redex's handling of native multidex, but rather that it's incorrectly removing some classes, and shrinking the dexes enough that multiple dexes are no longer needed.  How are you invoking redex?  I can't think of anything in the default configuration that would cause this.

Also, If you have a few minutes to help me debug, try this:
* Create a do-nothing redex configuration file, like:
```
{ "redex" : { "passes" : [] } }
```
* Run redex on your APK with that config:
```
redex -c do-nothing.cfg -o output.apk input.apk
```
* Test that APK.  If it still exhibits the problem, then redex is in fact somehow messing up native multidex.
* If it works, then the problem is in the optimization passes.  Gradually add them back in to the passes array until the problem shows up.  Here's the default list:
```
      "ReBindRefsPass",
      "BridgePass",
      "SynthPass",
      "FinalInlinePass",
      "DelSuperPass",
      "SingleImplPass",
      "SimpleInlinePass",
      "StaticReloPass",
      "RemoveEmptyClassesPass",
      "ShortenSrcStringsPass",
```

**Comment by eveliotc** [comment]
@bertmaher I used a `do-nothing.cfg` and it seems second dexfile is removed:

![screen shot 2016-10-04 at 12 07 37 pm](https://cloud.githubusercontent.com/assets/400641/19088481/3457a658-8a2b-11e6-8d3d-3051bc3012ca.png)

If you want to reproduce by yourself please use latest public Lyft build http://evel.io/static/builds/lyft-android-94538.apk

**Comment by bertmaher** [comment]
Argh, thanks for the APK, I was able to find the bug quite easily from that.  I've no idea when we introduced this, but our multidex logic currently requires some metadata that FB's build system provides.  I'll have a fix in a few hours.

**Comment by bertmaher** [comment]
https://github.com/facebook/redex/commit/a3a11426550f438d5cfbf2bb2005d374d4365379 should fix it.  Let me know if that's not the case!
