### ISSUE TITLE
Ubuntu 16.10 vm guest, can`t sign apk

### ISSUE THREAD

**Issue by necros2k7** [facebook/redex#180]
vm@vm-VirtualBox:/media/sf_shared$ redex --sign redexsign.apk
Error writing mapping file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 494, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 460, in run_redex
    args.keyalias, args.keypass)
  File "/usr/local/bin/redex", line 222, in create_output_apk
    stdout=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by samyakjain** [comment]
+1

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
