### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by gaoxuxu** [facebook/redex#181]
```
➜  android git:(master) ✗ redex -o out.apk in.apk
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 494, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 439, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 74, in run_pass
    log('Running redex binary at ' + executable_path)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by knappador** [comment]
Alias, symlink, or use environment variables to get `which python` to resolve to `python2`
