### ISSUE TITLE
struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by wenqingtao** [facebook/redex#214]
When I run the command redex XXX.apk -o YYY.apk, the following error occurs:

Traceback (most recent call last):
  File "/tmp/redex.CqyDkC/redex.py", line 546, in <module>
    run_redex(args)
  File "/tmp/redex.CqyDkC/redex.py", line 416, in run_redex
    unzip_apk(args.input_apk, extracted_apk_dir)
  File "/tmp/redex.CqyDkC/redex.py", line 179, in unzip_apk
    with zipfile.ZipFile(apk) as z:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 857, in _RealGetContents
    x._decodeExtra()
  File "/usr/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
struct.error: unpack requires a string argument of length 4

**Comment by justinjhendrick** [comment]
Why did you close it? Did you solve the issue yourself? If so, please post your solution here in case someone else has the same issue.

**Comment by wenqingtao** [comment]
When I change a apk to test this issue has not happened,so I close it
