### ISSUE TITLE
redexdump segfaults and and an assertion failure

### ISSUE THREAD

**Issue by geeknik** [facebook/redex#225]
A malformed DEX triggers segfaults in multiple redexdump locations. This is triggered with `2e01c28`, compiled with afl on Debian 8 x64.

`
./redexdump -a test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14
ASAN:SIGSEGV
=================================================================
==26678==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000435a09 sp 0x7ffd084416a0 bp 0x7fe1d5145070 T0)
    #0 0x435a08 in dump_strings(ddump_data*, bool) tools/redexdump/DumpTables.cpp:521
    #1 0x403d97 in main tools/redexdump/RedexDump.cpp:170
    #2 0x7fe1d2771b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #3 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/redexdump/DumpTables.cpp:521 dump_strings(ddump_data*, bool)
==26678==ABORTING
```

`./redexdump -S test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

RAW STRING DATA
u16len [contents]
101 [{invalid encoding?}]
001 [.]
013 [.Result was: ]
002 [..]
001 [ ]
002 [ (]
009 [ HTTP/1.1]
029 [ blocked the main thread for ]
006 [ bytes]
020 [ bytes but received ]
021 [ bytes, but received ]
025 [ does not support writing]
004 [ is ]
013 [ is corrupt: ]
037 [ is using deprecated tag <url-filter>]
001 ["]
012 ["/> instead.]
015 [$ClientProvider]
009 [$Provider]
015 [$ServerProvider]
045 [$SwitchMap$com$squareup$okhttp$ResponseSource]
007 [$VALUES]
019 [$assertionsDisabled]
001 [%]
016 [%s: Line %d : %s]
018 [' was not verified]
002 [',]
003 [', ]
001 [(]
002 [()]
003 [()V]
002 [(I]
003 [(I)]
003 [(II]
006 [(IIIII]
003 [(Z)]
016 [([a-z0-9.-]*\.)?]
001 [)]
002 [);]
002 [)V]
001 [*]
002 [*.]
003 [*/*]
001 [,]
002 [, ]
010 [, removing]
016 [,"keepCallback":]
011 [,"message":]
002 [,[]
003 [-1.]
001 [.]
004 [.tmp]
001 [/]
002 [/*]
014 [/Android/data/]
015 [/android_asset/]
007 [/cache/]
001 [1]
041 [110 HttpURLConnection "Response is stale"]
044 [113 HttpURLConnection "Heuristic expiration"]
005 [20000]
005 [3.3.0]
003 [3ga]
001 [:]
002 [: ]
005 [:host]
007 [:method]
005 [:path]
007 [:scheme]
007 [:status]
008 [:version]
001 [;]
001 [<]
004 [<*>;]
006 [<*>;)V]
005 [<[B>;]
008 [<clinit>]
006 [<init>]
002 [=,]
085 [=====================================================================================]
002 [>;]
003 [>;)]
004 [>;)V]
004 [>;>;]
005 [>;>;)]
006 [>;>;)V]
006 [>;>;)Z]
006 [>;>;Z)]
005 [>;Z)V]
005 [>;ZZ)]
012 [>>> loadUrl(]
016 [>>> loadUrlNow()]
001 [?]
016 [@Null arguments.]
016 [ACTIVITY_EXITING]
016 [ACTIVITY_RUNNING]
017 [ACTIVITY_STARTING]
019 [ANY_SEQUENCE_NUMBER]
028 [AbstractHttpInputStream.java]
029 [AbstractHttpOutputStream.java]
025 [AbstractOutputStream.java]
015 [Accept-Encoding]
014 [ActivityResult]
012 [Address.java]
003 [Age]
005 [Alert]
009 [Android23]
009 [Android41]
003 [App]
008 [App.java]
012 [App.loadUrl(]
017 [Application Error]
044 [Attempted to send a second callback for ID: ]
024 [AuthenticationToken.java]
013 [Authorization]
001 [B]
010 [BIG_ENDIAN]
031 [BROWSER_COMPATIBLE_DATE_FORMATS]
011 [BUFFER_SIZE]
015 [BackgroundColor]
011 [Base64.java]
010 [BridgeMode]
016 [BuildConfig.java]
007 [Builder]
001 [C]
005 [CACHE]
006 [CANCEL]
022 [CASE_INSENSITIVE_ORDER]
025 [CB-3064: The errorUrl is ]
002 [CI]
025 [CLASS_NOT_FOUND_EXCEPTION]
005 [CLEAN]
006 [CLEAN ]
030 [CLIENT_CERTIFICATE_VECTOR_SIZE]
017 [CONDITIONAL_CACHE]
008 [CONNECT ]
023 [CORDOVA_EXEC_URL_PREFIX]
015 [CORDOVA_VERSION]
005 [COUNT]
027 [COVER_SCREEN_GRAVITY_CENTER]
002 [CR]
004 [CRLF]
012 [CURRENT_CWND]
013 [Cache-Control]
019 [CacheControlHandler]
016 [CacheRequestImpl]
021 [Callback %s stream %d]
020 [CallbackContext.java]
036 [Cannot SPDY; no SYNC_FLUSH available]
059 [Cannot access request header fields after connection is set]
052 [Cannot add request property after connection is made]
082 [Cannot get real path for URI string %s because it is a file:///android_asset/ URI.]
031 [Cannot retry streamed HTTP body]
052 [Cannot set request property after connection is made]
009 [Challenge]
022 [Changing log level to ]
018 [ChunkedInputStream]
019 [ChunkedOutputStream]
015 [Class not found]
006 [Config]
011 [Config.java]
007 [Confirm]
010 [Connection]
039 [Connection has not yet been established]
015 [Connection.java]
019 [ConnectionPool.java]
016 [Content-Encoding]
014 [Content-Length]
012 [Content-Type]
006 [Cookie]
007 [Cookie2]
015 [CordovaActivity]
022 [CordovaActivity.init()]
020 [CordovaActivity.java]
026 [CordovaActivity.onCreate()]
./libredex/DexDefs.h:198: uint32_t mutf8_next_code_point(const char*&): assertion `false' failed.
Invalid 2nd byte on mutf8 string
/usr/lib/x86_64-linux-gnu/libasan.so.1(backtrace+0x3a)[0x7f0b5894648a]
./redexdump[0x44e5c8]
./redexdump[0x44e942]
./redexdump[0x4350c6]
./redexdump[0x43557b]
./redexdump[0x403db9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f0b56fc2b45]
./redexdump[0x4045fd]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Redex assertion failure
Aborted
```

`./redexdump -p test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

PROTO IDS TABLE: 257015
[proto_ids_off] shorty proto
ASAN:SIGSEGV
=================================================================
==23112==ERROR: AddressSanitizer: SEGV on unknown address 0x7f3d27afa60c (pc 0x00000043ce57 sp 0x7ffe70e569b0 bp 0x000000000005 T0)
    #0 0x43ce56 in dex_raw_string_by_idx tools/common/DexCommon.cpp:111
    #1 0x43ce56 in dex_string_by_idx(ddump_data*, unsigned int) tools/common/DexCommon.cpp:115
    #2 0x4248bb in get_proto tools/redexdump/DumpTables.cpp:31
    #3 0x426a16 in dump_protos(ddump_data*, bool) tools/redexdump/DumpTables.cpp:562
    #4 0x403d65 in main tools/redexdump/RedexDump.cpp:179
    #5 0x7f3bc740db44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #6 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/common/DexCommon.cpp:111 dex_raw_string_by_idx
==23112==ABORTING
```

`./redexdump -m test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

METHOD IDS TABLE: 257076
[method_ids_off] class name proto_no_shorty
ASAN:SIGSEGV
=================================================================
==26872==ERROR: AddressSanitizer: SEGV on unknown address 0x7f4adcf5a0c9 (pc 0x0000004284e1 sp 0x7ffe033637d0 bp 0x7f4adcf02c01 T0)
    #0 0x4284e0 in get_proto tools/redexdump/DumpTables.cpp:34
    #1 0x4284e0 in get_method tools/redexdump/DumpTables.cpp:69
    #2 0x42c2fe in dump_methods(ddump_data*, bool) tools/redexdump/DumpTables.cpp:584
    #3 0x403d27 in main tools/redexdump/RedexDump.cpp:185
    #4 0x7f4ada4f0b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #5 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/redexdump/DumpTables.cpp:34 get_proto
==26872==ABORTING
```

`./redexdump -c test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

CLASS DEFS TABLE: 257104
[class_def_off] flags class 'extends' superclass['implements' interfaces]
        [file: <filename>] [anno: annotation_off] data: class_data_off [static values: static_value_off]
ASAN:SIGSEGV
=================================================================
==30421==ERROR: AddressSanitizer: SEGV on unknown address 0x7f8ee9e1706b (pc 0x000000420bcc sp 0x7ffecba997e0 bp 0x7f8e82da5c5f T0)
    #0 0x420bcb in get_class_def tools/redexdump/DumpTables.cpp:140
    #1 0x423150 in dump_clsdefs(ddump_data*, bool) tools/redexdump/DumpTables.cpp:599
    #2 0x403d05 in main tools/redexdump/RedexDump.cpp:188
    #3 0x7f8e80393b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #4 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/redexdump/DumpTables.cpp:140 get_class_def
==30421==ABORTING
```

`./redexdump -C test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

CLASS DATA TABLE: 257104
[cls_data_off] class
sfields: <count> followed by sfields
ifields: <count> followed by ifields
dmethods: <count> followed by dmethods
vmethods: <count> followed by vmethods
ASAN:SIGSEGV
=================================================================
==1834==ERROR: AddressSanitizer: SEGV on unknown address 0x7f1e1779c564 (pc 0x00000042ddfa sp 0x7ffe4ba98d10 bp 0x7ffe4ba98e20 T0)
    #0 0x42ddf9 in read_uleb128 libredex/DexDefs.h:72
    #1 0x42ddf9 in get_class_data_item tools/redexdump/DumpTables.cpp:192
    #2 0x4339a4 in dump_clsdata(ddump_data*, bool) tools/redexdump/DumpTables.cpp:619
    #3 0x403ce7 in main tools/redexdump/RedexDump.cpp:191
    #4 0x7f1e06dc2b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #5 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV libredex/DexDefs.h:72 read_uleb128
==1834==ABORTING
```

`./redexdump -x test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14

CODE ITEM: 17
[code_item_off] meth_id registers_size: <count>,ins_size: <count>,outs_size: <count>,tries_size: <count>,debug_info_off: <addr>,insns_size: <count>
[0x12364] registers_size: 0, ins_size: 0, outs_size: 0, tries_size: 0, debug_info_off: 0x0, insns_size: 0
ASAN:SIGSEGV
=================================================================
==4095==ERROR: AddressSanitizer: SEGV on unknown address 0x7f4c977e5392 (pc 0x00000040f913 sp 0x7ffc0d684500 bp 0x000000000000 T0)
    #0 0x40f912 in get_code_item tools/redexdump/DumpTables.cpp:252
    #1 0x412cbc in dump_code_items tools/redexdump/DumpTables.cpp:628
    #2 0x412cbc in dump_code(ddump_data*) tools/redexdump/DumpTables.cpp:657
    #3 0x403cc7 in main tools/redexdump/RedexDump.cpp:194
    #4 0x7f4c94d7fb44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #5 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/redexdump/DumpTables.cpp:252 get_code_item
==4095==ABORTING
```

`./redexdump -A test031.dex`
```
Type                              Size  Offset
TYPE_HEADER_ITEM                     1  00000000
TYPE_STRING_ID_ITEM               3278  00000070
TYPE_TYPE_ID_ITEM                  472  000033a8
TYPE_PROTO_ID_ITEM                 718  00003b08
TYPE_FIELD_ID_ITEM                 807  00005cb0
TYPE_METHOD_ID_ITEM               2245  000075e8
TYPE_CLASS_DEF_ITEM                181  0000bc10
TYPE_MAP_LIST                        1  0000d3a8
TYPE_TYPE_LIST                     405  0000d484
TYPE_ANNOTATION_SET_ITEM           200  0000e3b8
TYPE_CLASS_DATA_ITEM               176  0000ebcc
TYPE_CODE_ITEM                    1385  00012364
TYPE_STRING_DATA_ITEM             3278  00033bcc
TYPE_DEBUG_INFO_ITEM              1385  00043398
TYPE_ANNOTATION_ITEM               208  00050390
TYPE_ENCODED_ARRAY_ITEM             32  00051a9c
TYPE_ANNOTATIONS_DIR_ITEM          157  00051d14
ASAN:SIGSEGV
=================================================================
==8785==ERROR: AddressSanitizer: SEGV on unknown address 0x7f165b3fd974 (pc 0x00000040b92b sp 0x7ffcb596ca50 bp 0x7f15e5cf5c62 T0)
    #0 0x40b92a in dump_class_annotations tools/redexdump/DumpTables.cpp:680
    #1 0x40b92a in dump_anno(ddump_data*) tools/redexdump/DumpTables.cpp:731
    #2 0x403ca7 in main tools/redexdump/RedexDump.cpp:200
    #3 0x7f15e32e3b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #4 0x4045fc (/root/redex/redexdump+0x4045fc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tools/redexdump/DumpTables.cpp:680 dump_class_annotations
==8785==ABORTING
```

Withholding `test031.dex` for now. Leave an email address if you don't want it shared publicly.

**Comment by geeknik** [comment]
Withholding `test031.dex` for now. Leave an email address if you don't want it shared publicly.

**Comment by justinjhendrick** [comment]
Please send test031.dex to jhendrick at fb.com

**Comment by geeknik** [comment]
Sent.

**Comment by justinjhendrick** [comment]
I've fixed one of the segfaults, it occurred on valid Dexes. I'll be submitting that code soon.

I don't think it's really worthwhile to fix all the other occurrences. It would probably be quite a bit of work to make sure `redexdump` never segfaults no matter what you throw at it. Why is it a big deal if it segfaults on malformed input?
