### ISSUE TITLE
Issue while creating jar2dex using dex2jar tool if apk has more than one .dex file

### ISSUE THREAD

**Issue by tohaidar2005** [facebook/redex#246]
I am struggling while using jar2dex. Below is the step to reproduce this issue,

1. Converting .apk file (which having the more than one dex) into jar using dex2jar tool for some of my requirement.
2.  Whenever again converting from jar2dex it is throwing the below error,

================================================
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.lang.StringBuilder.toString(StringBuilder.java:407)
        at java.lang.StackTraceElement.toString(StackTraceElement.java:173)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.lang.Throwable.printStackTrace(Throwable.java:658)
        at java.lang.Throwable.printStackTrace(Throwable.java:643)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

==================================================================

Is there solution available to resolve this issue using dex2jar tool. Please help if someone already got resolved this issue.

-Thanks

**Comment by justinjhendrick** [comment]
Try increasing your heap size `-Xmx4g`

**Comment by justinjhendrick** [comment]
Also, we didn't create `dex2jar` or `jar2dex`. Did you mean to post this here https://github.com/pxb1988/dex2jar ?

**Comment by tohaidar2005** [comment]
Yes..I am running this command using ant script not gradle. I am facing another issue whenever increasing the heap...it is throwing unable to allocate the memory.

**Comment by justinjhendrick** [comment]
Have you tried some of the other suggestions here https://stackoverflow.com/questions/1393486/error-java-lang-outofmemoryerror-gc-overhead-limit-exceeded ?

**Comment by justinjhendrick** [comment]
Closing as we don't own `jar2dex`
