### ISSUE TITLE
No such file or directory error on Mac

### ISSUE THREAD

**Issue by benoitletondor** [facebook/redex#25]
Hello there,

I'm getting this error after running the `redex` cl on Mac OS. Any idea what may going wrong?

```
benoit@local:~/Desktop$ redex eb.apk -o eb-redex.apk
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/zl/cb9mqw910m907k5qdbcw65bm0000gn/T/tmpcm288xpk.redex_dexen/classes.dex' -> '/var/folders/zl/cb9mqw910m907k5qdbcw65bm0000gn/T/tmpcjbytfn6.redex_extracted_apk/classes.dex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 746, in run_redex
    dex_mode.repackage(extracted_apk_dir, dex_dir, have_locators)
  File "/usr/local/bin/redex", line 236, in repackage
    shutil.move(join(dex_dir, 'classes.dex'), extracted_apk_dir)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/zl/cb9mqw910m907k5qdbcw65bm0000gn/T/tmpcm288xpk.redex_dexen/classes.dex'
```

Thanks

**Comment by bertmaher** [comment]
It seems like something's screwy with your TMPDIR.  It's hard to say how that's going wrong but it'll probably work for you to run redex as: `TMPDIR=/tmp redex eb.apk -o eb-redex.apk`

**Comment by benoitletondor** [comment]
Hi,

Thanks for your help but unfortunately it still doesn't work:

```
benoit@local:~/Desktop$ TMPDIR=/tmp redex eb.apk -o eb-redex.apk
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9nz1iahk.redex_dexen/classes.dex' -> '/tmp/tmpizx0mby3.redex_extracted_apk/classes.dex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 746, in run_redex
    dex_mode.repackage(extracted_apk_dir, dex_dir, have_locators)
  File "/usr/local/bin/redex", line 236, in repackage
    shutil.move(join(dex_dir, 'classes.dex'), extracted_apk_dir)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9nz1iahk.redex_dexen/classes.dex'
```
