### ISSUE TITLE
Not Duplicate, Couldn't find zipalign. See README.md to resolve this.

### ISSUE THREAD

**Issue by rhonyabdullah** [facebook/redex#258]
Seems going to my android sdk folder doesn't resolve the problem.
```
MyMac:sdk rhony$ redex ~/Downloads/APK/app-prerelease-release.apk -o ~/Downloads/output.apk
Couldn't find zipalign. See README.md to resolve this.
Traceback (most recent call last):
  File "/tmp/redex.dXr73a/redex.py", line 225, in zipalign
    ['4', unaligned_apk_path, output_apk_path])
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'zipalign'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.dXr73a/redex.py", line 636, in <module>
    run_redex(args)
  File "/tmp/redex.dXr73a/redex.py", line 596, in run_redex
    args.keyalias, args.keypass, args.ignore_zipalign)
  File "/tmp/redex.dXr73a/redex.py", line 276, in create_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign)
  File "/tmp/redex.dXr73a/redex.py", line 229, in zipalign
    raise Exception('No zipalign executable found')
Exception: No zipalign executable found
```

After reading some solved issues, i'm try to adding my android evn.
```export ANDROID_SDK=~/Library/Android/sdk/```

Then execute the command, now i got the apk which is optimized from 13Mb to 12.8Mb. But, when i try to install the apk, it fails, installer says that the apk appears to corrupted. **Now what** ?

Fyi: [redex-src-strings-map.txt](https://pastebin.com/fB4tVjui)

**Comment by justinjhendrick** [comment]
Could you please post the output of `adb install <redex_apk>`?

**Comment by rhonyabdullah** [comment]
Here's the output, @justinjhendrick 
```Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl533939817.tmp/base.apk: Attempt to get length of null array]```

**Comment by justinjhendrick** [comment]
https://github.com/facebook/redex#my-app-fails-to-install-with-failure-install_parse_failed_no_certificates
