### ISSUE TITLE
Compilation does not pass

### ISSUE THREAD

**Issue by ManLoveGirlBaby** [facebook/redex#278]
Error log
```
./libredex/WorkQueue.h:110: WorkQueue<Input, Data, Output>::WorkQueue(std::function<Output(Data&, Input)>, std::function<Output(Output, Output)>, std::function<Data(unsigned int)>, unsigned int) [with Input = DexClass*; Data = std::nullptr_t; Output = std::nullptr_t]: assertion `num_threads >= 1' failed.

/tmp/redex.yUAqgj/redex-all[0x6d7c15]
/tmp/redex.yUAqgj/redex-all(_Z11assert_failPKcS0_jS0_S0_z+0xc7)[0x6d7d17]
/tmp/redex.yUAqgj/redex-all(_ZN9WorkQueueIP8DexClassDnS2_EC2ESt8functionIFS2_RS2_S1_EES4_IFS2_S2_S2_EES4_IFS2_jEEj+0x3b2)[0x552aa2]
/tmp/redex.yUAqgj/redex-all(_Z21walk_methods_parallelIDnS0_St6vectorIP8DexClassSaIS3_EEZ28walk_methods_parallel_simpleIS5_EvRKT_RKSt8functionIFvP9DexMethodEEEUlS0_SC_E_ZS6_IS5_EvS9_SG_EUlS0_S0_E0_ZS6_IS5_EvS9_SG_EUliE1_ET0_RKT1_T2_T3_T4_RKSK_m+0xb1)[0x552dd1]
/tmp/redex.yUAqgj/redex-all(_ZN11PassManager16run_type_checkerERKSt6vectorIP8DexClassSaIS2_EEbb+0xc6)[0x767396]
/tmp/redex.yUAqgj/redex-all(_ZN11PassManager10run_passesERSt6vectorI8DexStoreSaIS1_EERKS0_IP8DexClassSaIS6_EER11ConfigFiles+0x2043)[0x7694d3]
/tmp/redex.yUAqgj/redex-all(main+0x13cd)[0x51e27d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7faa79f32f45]
/tmp/redex.yUAqgj/redex-all[0x523f55]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Redex assertion failure
/tmp/redex.yUAqgj/redex-all[0x6d7c15]
/tmp/redex.yUAqgj/redex-all(_Z23crash_backtrace_handleri+0x8)[0x6d7c38]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7faa79f47cb0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7faa79f47c37]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7faa79f4b028]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7faa7a85f415]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x6a206)[0x7faa7a85d206]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x6a251)[0x7faa7a85d251]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x6a493)[0x7faa7a85d493]
/tmp/redex.yUAqgj/redex-all(_Z11assert_failPKcS0_jS0_S0_z+0xf9)[0x6d7d49]
/tmp/redex.yUAqgj/redex-all(_ZN9WorkQueueIP8DexClassDnS2_EC2ESt8functionIFS2_RS2_S1_EES4_IFS2_S2_S2_EES4_IFS2_jEEj+0x3b2)[0x552aa2]
/tmp/redex.yUAqgj/redex-all(_Z21walk_methods_parallelIDnS0_St6vectorIP8DexClassSaIS3_EEZ28walk_methods_parallel_simpleIS5_EvRKT_RKSt8functionIFvP9DexMethodEEEUlS0_SC_E_ZS6_IS5_EvS9_SG_EUlS0_S0_E0_ZS6_IS5_EvS9_SG_EUliE1_ET0_RKT1_T2_T3_T4_RKSK_m+0xb1)[0x552dd1]
/tmp/redex.yUAqgj/redex-all(_ZN11PassManager16run_type_checkerERKSt6vectorIP8DexClassSaIS2_EEbb+0xc6)[0x767396]
/tmp/redex.yUAqgj/redex-all(_ZN11PassManager10run_passesERSt6vectorI8DexStoreSaIS1_EERKS0_IP8DexClassSaIS6_EER11ConfigFiles+0x2043)[0x7694d3]
/tmp/redex.yUAqgj/redex-all(main+0x13cd)[0x51e27d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7faa79f32f45]
/tmp/redex.yUAqgj/redex-all[0x523f55]
Traceback (most recent call last):
  File "/tmp/redex.yUAqgj/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.yUAqgj/redex-all', '--apkdir', '/tmp/redex.yUAqgj/tmp502okxjp.redex_extracted_apk', '--outdir', '/tmp/redex.yUAqgj/tmpifoagyx0.redex_dexen', '/tmp/redex.yUAqgj/tmpifoagyx0.redex_dexen/dex0/classes.dex', '/tmp/redex.yUAqgj/tmpifoagyx0.redex_dexen/dex1/classes2.dex']' returned non-zero exit status -6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.yUAqgj/redex.py", line 641, in <module>
    run_redex(args)
  File "/tmp/redex.yUAqgj/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.yUAqgj/redex.py", line 165, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.yUAqgj/redex-gdb-clm4rzm6.sh or under lldb by running /tmp/redex.yUAqgj/redex-lldb-gz3cbr6v.sh
```

**Comment by justinjhendrick** [comment]
Aha. I think I might know what is happening. Could you compile and run this program, please?

```
#include <thread>
#include <cstdio>

int main() {
  printf("%d\n", std::thread::hardware_concurrency());
  return 0;
}
```

Please let me know what that program prints :)

**Comment by justinjhendrick** [comment]
This should be fixed. Please re-open if it's not.

**Comment by ManLoveGirlBaby** [comment]
Thank you, I trying.
