### ISSUE TITLE
returned non-zero exit status -6

### ISSUE THREAD

**Issue by zhuangjiahua** [facebook/redex#280]
# I use redex failed and it return me an error

## This is the command line I use:
       redex ShenZhenKeJiYuan.apk -o ShenZhenKeJiYuan-redex.apk

## And this is the error info:
dyld: Symbol not found: __ZN5boost16re_detail_10600012perl_matcherIPKcNSt3__19allocatorINS_9sub_matchIS3_EEEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14construct_initERKNS_11basic_regexIcSC_EENS_15regex_constants12_match_flagsE
  Referenced from: /tmp/redex.fRnPLJ/redex-all
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /tmp/redex.fRnPLJ/redex-all
Traceback (most recent call last):
  File "/tmp/redex.fRnPLJ/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.fRnPLJ/redex-all', '--apkdir', '/tmp/redex.fRnPLJ/tmpyl3zvrca.redex_extracted_apk', '--outdir', '/tmp/redex.fRnPLJ/tmpn66ghijb.redex_dexen', '/tmp/redex.fRnPLJ/tmpn66ghijb.redex_dexen/dex0/classes.dex', '/tmp/redex.fRnPLJ/tmpn66ghijb.redex_dexen/dex1/classes2.dex', '/tmp/redex.fRnPLJ/tmpn66ghijb.redex_dexen/dex2/classes3.dex', '/tmp/redex.fRnPLJ/tmpn66ghijb.redex_dexen/dex3/classes4.dex']' returned non-zero exit status -6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.fRnPLJ/redex.py", line 641, in <module>
    run_redex(args)
  File "/tmp/redex.fRnPLJ/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.fRnPLJ/redex.py", line 165, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.fRnPLJ/redex-gdb-7_02uh41.sh or under lldb by running /tmp/redex.fRnPLJ/redex-lldb-ug3c4kix.sh

### Why it happen? It's there something wrong i do?

**Comment by h4ck3r89** [comment]
Can you share the details of the build process that you used to compile redex???

**Comment by zhuangjiahua** [comment]
xcode-select --install
brew install autoconf automake libtool python3
brew install boost jsoncpp

git clone https://github.com/facebook/redex.git
cd redex

autoreconf -ivf && ./configure && make -j4
sudo make install

**Comment by justinjhendrick** [comment]
https://stackoverflow.com/questions/23456090/xcode-5-1-1-and-boost might be helpful?

**Comment by zhuangjiahua** [comment]
It didn't help for me.It's not for android.

**Comment by justinjhendrick** [comment]
We haven't made it to any android specifics yet. Redex is a C++ program that links in boost.

Could you `ls /usr/local/opt/boost/lib/` and show me what's there, please?

**Comment by zhuangjiahua** [comment]
libboost_atomic-mt.a			libboost_math_tr1l-mt.dylib
libboost_atomic-mt.dylib		libboost_math_tr1l.a
libboost_chrono-mt.a			libboost_math_tr1l.dylib
libboost_chrono-mt.dylib		libboost_prg_exec_monitor-mt.a
libboost_chrono.a			libboost_prg_exec_monitor-mt.dylib
libboost_chrono.dylib			libboost_prg_exec_monitor.a
libboost_container-mt.a			libboost_prg_exec_monitor.dylib
libboost_container-mt.dylib		libboost_program_options-mt.a
libboost_container.a			libboost_program_options-mt.dylib
libboost_container.dylib		libboost_program_options.a
libboost_context-mt.a			libboost_program_options.dylib
libboost_context-mt.dylib		libboost_random-mt.a
libboost_coroutine-mt.a			libboost_random-mt.dylib
libboost_coroutine-mt.dylib		libboost_random.a
libboost_coroutine.a			libboost_random.dylib
libboost_coroutine.dylib		libboost_regex-mt.a
libboost_date_time-mt.a			libboost_regex-mt.dylib
libboost_date_time-mt.dylib		libboost_regex.a
libboost_date_time.a			libboost_regex.dylib
libboost_date_time.dylib		libboost_serialization-mt.a
libboost_exception-mt.a			libboost_serialization-mt.dylib
libboost_exception.a			libboost_serialization.a
libboost_filesystem-mt.a		libboost_serialization.dylib
libboost_filesystem-mt.dylib		libboost_signals-mt.a
libboost_filesystem.a			libboost_signals-mt.dylib
libboost_filesystem.dylib		libboost_signals.a
libboost_graph-mt.a			libboost_signals.dylib
libboost_graph-mt.dylib			libboost_stacktrace_addr2line-mt.a
libboost_graph.a			libboost_stacktrace_addr2line-mt.dylib
libboost_graph.dylib			libboost_stacktrace_addr2line.a
libboost_iostreams-mt.a			libboost_stacktrace_addr2line.dylib
libboost_iostreams-mt.dylib		libboost_stacktrace_basic-mt.a
libboost_iostreams.a			libboost_stacktrace_basic-mt.dylib
libboost_iostreams.dylib		libboost_stacktrace_basic.a
libboost_locale-mt.a			libboost_stacktrace_basic.dylib
libboost_locale-mt.dylib		libboost_stacktrace_noop-mt.a
libboost_log-mt.a			libboost_stacktrace_noop-mt.dylib
libboost_log-mt.dylib			libboost_stacktrace_noop.a
libboost_log.a				libboost_stacktrace_noop.dylib
libboost_log.dylib			libboost_system-mt.a
libboost_log_setup-mt.a			libboost_system-mt.dylib
libboost_log_setup-mt.dylib		libboost_system.a
libboost_log_setup.a			libboost_system.dylib
libboost_log_setup.dylib		libboost_test_exec_monitor-mt.a
libboost_math_c99-mt.a			libboost_test_exec_monitor.a
libboost_math_c99-mt.dylib		libboost_thread-mt.a
libboost_math_c99.a			libboost_thread-mt.dylib
libboost_math_c99.dylib			libboost_timer-mt.a
libboost_math_c99f-mt.a			libboost_timer-mt.dylib
libboost_math_c99f-mt.dylib		libboost_timer.a
libboost_math_c99f.a			libboost_timer.dylib
libboost_math_c99f.dylib		libboost_type_erasure-mt.a
libboost_math_c99l-mt.a			libboost_type_erasure-mt.dylib
libboost_math_c99l-mt.dylib		libboost_type_erasure.a
libboost_math_c99l.a			libboost_type_erasure.dylib
libboost_math_c99l.dylib		libboost_unit_test_framework-mt.a
libboost_math_tr1-mt.a			libboost_unit_test_framework-mt.dylib
libboost_math_tr1-mt.dylib		libboost_unit_test_framework.a
libboost_math_tr1.a			libboost_unit_test_framework.dylib
libboost_math_tr1.dylib			libboost_wave-mt.a
libboost_math_tr1f-mt.a			libboost_wave-mt.dylib
libboost_math_tr1f-mt.dylib		libboost_wserialization-mt.a
libboost_math_tr1f.a			libboost_wserialization-mt.dylib
libboost_math_tr1f.dylib		libboost_wserialization.a
libboost_math_tr1l-mt.a			libboost_wserialization.dylib

**Comment by zhuangjiahua** [comment]
libboost_atomic-mt.a             	libboost_math_tr1l-mt.dylib
libboost_atomic-mt.dylib             libboost_math_tr1l.a
libboost_chrono-mt.a             	libboost_math_tr1l.dylib
libboost_chrono-mt.dylib             libboost_prg_exec_monitor-mt.a
libboost_chrono.a             	libboost_prg_exec_monitor-mt.dylib
libboost_chrono.dylib             	libboost_prg_exec_monitor.a
libboost_container-mt.a             	libboost_prg_exec_monitor.dylib
libboost_container-mt.dylib             libboost_program_options-mt.a
libboost_container.a             	libboost_program_options-mt.dylib
libboost_container.dylib             libboost_program_options.a
libboost_context-mt.a             	libboost_program_options.dylib
libboost_context-mt.dylib             libboost_random-mt.a
libboost_coroutine-mt.a             	libboost_random-mt.dylib
libboost_coroutine-mt.dylib             libboost_random.a
libboost_coroutine.a             	libboost_random.dylib
libboost_coroutine.dylib             libboost_regex-mt.a
libboost_date_time-mt.a             	libboost_regex-mt.dylib
libboost_date_time-mt.dylib             libboost_regex.a
libboost_date_time.a             	libboost_regex.dylib
libboost_date_time.dylib             libboost_serialization-mt.a
libboost_exception-mt.a             	libboost_serialization-mt.dylib
libboost_exception.a             	libboost_serialization.a
libboost_filesystem-mt.a             libboost_serialization.dylib
libboost_filesystem-mt.dylib             libboost_signals-mt.a
libboost_filesystem.a             	libboost_signals-mt.dylib
libboost_filesystem.dylib             libboost_signals.a
libboost_graph-mt.a             	libboost_signals.dylib
libboost_graph-mt.dylib             	libboost_stacktrace_addr2line-mt.a
libboost_graph.a             	libboost_stacktrace_addr2line-mt.dylib
libboost_graph.dylib             	libboost_stacktrace_addr2line.a
libboost_iostreams-mt.a             	libboost_stacktrace_addr2line.dylib
libboost_iostreams-mt.dylib             libboost_stacktrace_basic-mt.a
libboost_iostreams.a             	libboost_stacktrace_basic-mt.dylib
libboost_iostreams.dylib             libboost_stacktrace_basic.a
libboost_locale-mt.a             	libboost_stacktrace_basic.dylib
libboost_locale-mt.dylib             libboost_stacktrace_noop-mt.a
libboost_log-mt.a             	libboost_stacktrace_noop-mt.dylib
libboost_log-mt.dylib             	libboost_stacktrace_noop.a
libboost_log.a                          libboost_stacktrace_noop.dylib
libboost_log.dylib             	libboost_system-mt.a
libboost_log_setup-mt.a             	libboost_system-mt.dylib
libboost_log_setup-mt.dylib             libboost_system.a
libboost_log_setup.a             	libboost_system.dylib
libboost_log_setup.dylib             libboost_test_exec_monitor-mt.a
libboost_math_c99-mt.a             	libboost_test_exec_monitor.a
libboost_math_c99-mt.dylib             libboost_thread-mt.a
libboost_math_c99.a             	libboost_thread-mt.dylib
libboost_math_c99.dylib             	libboost_timer-mt.a
libboost_math_c99f-mt.a             	libboost_timer-mt.dylib
libboost_math_c99f-mt.dylib             libboost_timer.a
libboost_math_c99f.a             	libboost_timer.dylib
libboost_math_c99f.dylib             libboost_type_erasure-mt.a
libboost_math_c99l-mt.a             	libboost_type_erasure-mt.dylib
libboost_math_c99l-mt.dylib             libboost_type_erasure.a
libboost_math_c99l.a             	libboost_type_erasure.dylib
libboost_math_c99l.dylib             libboost_unit_test_framework-mt.a
libboost_math_tr1-mt.a             	libboost_unit_test_framework-mt.dylib
libboost_math_tr1-mt.dylib             libboost_unit_test_framework.a
libboost_math_tr1.a             	libboost_unit_test_framework.dylib
libboost_math_tr1.dylib             	libboost_wave-mt.a
libboost_math_tr1f-mt.a             	libboost_wave-mt.dylib
libboost_math_tr1f-mt.dylib             libboost_wserialization-mt.a
libboost_math_tr1f.a             	libboost_wserialization-mt.dylib
libboost_math_tr1f.dylib             libboost_wserialization.a
libboost_math_tr1l-mt.a             	libboost_wserialization.dylib

**Comment by zhuangjiahua** [comment]
libboost_atomic-mt.a
libboost_atomic-mt.dylib
libboost_chrono-mt.a
libboost_chrono-mt.dylib
libboost_chrono.a
libboost_chrono.dylib
libboost_container-mt.a
libboost_container-mt.dylib
libboost_container.a
libboost_container.dylib
libboost_context-mt.a
libboost_context-mt.dylib
libboost_coroutine-mt.a
libboost_coroutine-mt.dylib
libboost_coroutine.a
libboost_coroutine.dylib
libboost_date_time-mt.a
libboost_date_time-mt.dylib
libboost_date_time.a
libboost_date_time.dylib
libboost_exception-mt.a
libboost_exception.a
libboost_filesystem-mt.a
libboost_filesystem-mt.dylib
libboost_filesystem.a
libboost_filesystem.dylib
libboost_graph-mt.a
libboost_graph-mt.dylib
libboost_graph.a
libboost_graph.dylib
libboost_iostreams-mt.a
libboost_iostreams-mt.dylib
libboost_iostreams.a
libboost_iostreams.dylib
libboost_locale-mt.a
libboost_locale-mt.dylib
libboost_log-mt.a
libboost_log-mt.dylib
libboost_log.a
libboost_log.dylib
libboost_log_setup-mt.a
libboost_log_setup-mt.dylib
libboost_log_setup.a
libboost_log_setup.dylib
libboost_math_c99-mt.a
libboost_math_c99-mt.dylib
libboost_math_c99.a
libboost_math_c99.dylib
libboost_math_c99f-mt.a
libboost_math_c99f-mt.dylib
libboost_math_c99f.a
libboost_math_c99f.dylib
libboost_math_c99l-mt.a
libboost_math_c99l-mt.dylib
libboost_math_c99l.a
libboost_math_c99l.dylib
libboost_math_tr1-mt.a
libboost_math_tr1-mt.dylib
libboost_math_tr1.a
libboost_math_tr1.dylib
libboost_math_tr1f-mt.a
libboost_math_tr1f-mt.dylib
libboost_math_tr1f.a
libboost_math_tr1f.dylib
libboost_math_tr1l-mt.a
libboost_math_tr1l-mt.dylib
libboost_math_tr1l.a
libboost_math_tr1l.dylib
libboost_prg_exec_monitor-mt.a
libboost_prg_exec_monitor-mt.dylib
libboost_prg_exec_monitor.a
libboost_prg_exec_monitor.dylib
libboost_program_options-mt.a
libboost_program_options-mt.dylib
libboost_program_options.a
libboost_program_options.dylib
libboost_random-mt.a
libboost_random-mt.dylib
libboost_random.a
libboost_random.dylib
libboost_regex-mt.a
libboost_regex-mt.dylib
libboost_regex.a
libboost_regex.dylib
libboost_serialization-mt.a
libboost_serialization-mt.dylib
libboost_serialization.a
libboost_serialization.dylib
libboost_signals-mt.a
libboost_signals-mt.dylib
libboost_signals.a
libboost_signals.dylib
libboost_stacktrace_addr2line-mt.a
libboost_stacktrace_addr2line-mt.dylib
libboost_stacktrace_addr2line.a
libboost_stacktrace_addr2line.dylib
libboost_stacktrace_basic-mt.a
libboost_stacktrace_basic-mt.dylib
libboost_stacktrace_basic.a
libboost_stacktrace_basic.dylib
libboost_stacktrace_noop-mt.a
libboost_stacktrace_noop-mt.dylib
libboost_stacktrace_noop.a
libboost_stacktrace_noop.dylib
libboost_system-mt.a
libboost_system-mt.dylib
libboost_system.a
libboost_system.dylib
libboost_test_exec_monitor-mt.a
libboost_test_exec_monitor.a
libboost_thread-mt.a
libboost_thread-mt.dylib
libboost_timer-mt.a
libboost_timer-mt.dylib
libboost_timer.a
libboost_timer.dylib
libboost_type_erasure-mt.a
libboost_type_erasure-mt.dylib
libboost_type_erasure.a
libboost_type_erasure.dylib
libboost_unit_test_framework-mt.a
libboost_unit_test_framework-mt.dylib
libboost_unit_test_framework.a
libboost_unit_test_framework.dylib
libboost_wave-mt.a
libboost_wave-mt.dylib
libboost_wserialization-mt.a
libboost_wserialization-mt.dylib
libboost_wserialization.a
libboost_wserialization.dylib

**Comment by NTillmann** [comment]
Closing due to inactivity. Feel free to reopen with new information.

**Comment by shineygs** [comment]
Did you solve the bug?

**Comment by shineygs** [comment]
Boost version might not be right
