### ISSUE TITLE
Issue while building Redex on MacOS 10.13 High sierra

### ISSUE THREAD

**Issue by geek2driod** [facebook/redex#313]
Getting this issue on MacOS 10.13 while building with Redex.  Please help

Traceback (most recent call last):
 File "/tmp/redex.HF6zdW/redex.py", line 687, in <module>
   run_redex(args)
 File "/tmp/redex.HF6zdW/redex.py", line 633, in run_redex
   args.keyalias, args.keypass, args.ignore_zipalign, args.page_align_libs)
 File "/tmp/redex.HF6zdW/redex.py", line 292, in create_output_apk
   zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
 File "/tmp/redex.HF6zdW/redex.py", line 248, in zipalign
   subprocess.check_call(zipalign + args)
 File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
   retcode = call(*popenargs, **kwargs)
 File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
   with Popen(*popenargs, **kwargs) as p:
 File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
   restore_signals, start_new_session)
 File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
   raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'zipalign': 'zipalign'

**Comment by geek2driod** [comment]
@justinjhendrick please tell me what arguments should I pass in this: ANDROID_SDK=/path/to/android/sdk redex [... arguments ...]

**Comment by justinjhendrick** [comment]
`redex --help` gives a full list of the available options
