### ISSUE TITLE
Unexpected token ' on line 3

### ISSUE THREAD

**Issue by rekire** [facebook/redex#32]
I get this crash:
```
Unexpected token ' on line 3
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
```
When I run this command line:
>redex playground/release.apk -m playground/mapping.txt -P playground/proguard-project.txt -o playground/out.apk

Line 3 of the proguard-project.txt is:

    -repackageclasses ''

When I comment that line out it works.

**Comment by rekire** [comment]
@bertmaher any progress or ETA here?

**Comment by bertmaher** [comment]
Hi @rekire, the -P flag is a work-in-progress feature.  It's not hooked up to the optimization passes, so if it's causing problems just don't use it.  I'm going to suppress the flag in the help text since it's misleading right now.
