### ISSUE TITLE
Command died with...

### ISSUE THREAD

**Issue by wuxinrong1981415** [facebook/redex#323]
I used redeem via bash command. The sh file write as follow:

redex ${my_apk} -o ${optimized_apk} -P ../../../proguard-rules.pro

I used a pro guard file named pro guard-rules.pro. 
In the last packaging process, error occurs: 

<error information as follows>

Traceback (most recent call last):
  File "/tmp/redex.pOVcOm/redex.py", line 177, in run_pass
    subprocess.check_call(args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.pOVcOm/redex-all', '--apkdir', '/tmp/redex.pOVcOm/tmpkiuaw3aj.redex_extracted_apk', '--outdir', '/tmp/redex.pOVcOm/tmpw0grr5g0.redex_dexen', '--proguard-config=../../../proguard-rules.pro', '/tmp/redex.pOVcOm/tmpw0grr5g0.redex_dexen/dex0/classes.dex']' died with <Signals.SIGABRT: 6>.

Can anyone help me ? Thanks a lot

**Comment by justinjhendrick** [comment]
I don't think there's a problem with your bash script, I think redex itself crashed by failing an `assert`. Could you turn on extra logging by setting the TRACE bash variable `export TRACE=1`? And also showing `stderr` from `redex-all`.

**Comment by wuxinrong1981415** [comment]
hi Justinjhendrick, thanks for your support.
I paste the error log here:

libredex/InstructionLowering.cpp:262: void instruction_lowering::check_load_params(DexMethod *): assertion `insn->dest() < next_ins' failed.
libredex/InstructionLowering.cpp:262: void instruction_lowering::check_load_params(DexMethod *): assertion `insn->dest() < next_ins' failed.
libredex/InstructionLowering.cpp:262: void instruction_lowering::check_load_params(DexMethod *): assertion `insn->dest() < next_ins' failed.
libredex/InstructionLowering.cpp:262: void instruction_lowering::check_load_params(DexMethod *): assertion `insn->dest() < next_ins' failed.
Instruction MOVE_OBJECT v21, v1 refers to a register (v21) >= size (21)in method Landroid/support/constraint/ConstraintLayout;.onMeasure:(II)V
Instruction MOVE_OBJECT v10, v5 refers to a register (v10) >= size (8)in method Landroid/support/constraint/solver/widgets/e;.b:(II)V
Instruction MOVE_OBJECT v29, v11 refers to a register (v29) >= size (26)in method Landroid/support/constraint/solver/widgets/ConstraintWidget;.a:(Landroid/support/constraint/solver/e;ZZLandroid/support/constraint/solver/widgets/ConstraintAnchor;Landroid/support/constraint/solver/widgets/ConstraintAnchor;IIIIFZZIII)V
Instruction MOVE_OBJECT v9, v0 refers to a register (v9) >= size (5)in method Landroid/support/constraint/solver/e;.a:()V

And, the last error messages:

Traceback (most recent call last):
  File "/tmp/redex.2fMxCo/redex.py", line 177, in run_pass
    subprocess.check_call(args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.2fMxCo/redex-all', '--apkdir', '/tmp/redex.2fMxCo/tmpin6uygec.redex_extracted_apk', '--outdir', '/tmp/redex.2fMxCo/tmpy2xbeoff.redex_dexen', '--config', '../../../rx_default.config', '--proguard-config=../../../proguard.cfg', '-Sproguard_map=../mapping/google/release/mapping.txt', '/tmp/redex.2fMxCo/tmpy2xbeoff.redex_dexen/dex0/classes.dex']' died with <Signals.SIGABRT: 6>.


thanks for your help.

**Comment by NTillmann** [comment]
Closing due to inactivity. Feel free to reopen with new information or a way for us to reproduce the issue.
