### ISSUE TITLE
API declarations must be interfaces

### ISSUE THREAD

**Issue by DummyCo** [facebook/redex#326]
Hi there! Thank you for that nice tool.
I'm getting next runtime exception on processed application launch attempt:

```
Fatal Exception: java.lang.RuntimeException: Unable to create application ***: java.lang.IllegalArgumentException: API declarations must be interfaces.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	   
Caused by java.lang.IllegalArgumentException: API declarations must be interfaces.
       at dbm.a(zipper is null:304)
       at bkm.<init>(sendMessage:20129)
       at bkq.<init>(selector:85)
       at ***.onCreate(gmd_memory:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by justinjhendrick** [comment]
Hmmm... I haven't seen an error like this before.

Which redex config are you using?

Could you help us narrow down which pass made this change? We can bisect which pass causes the problem by removing them from the redex config. Though, RegAlloc can't be removed safely (but I doubt it could cause this issue)

**Comment by NTillmann** [comment]
Closing due to inactivity. Feel free to reopen with new information or a way for us to reproduce the issue.
