### ISSUE TITLE
m_code == nulAssertion failed

### ISSUE THREAD

**Issue by tapthaker** [facebook/redex#336]
Getting an Error at https://github.com/facebook/redex/blob/master/libredex/DexClass.cpp#L470.

I saw m_code is not null, however I couldn't understand what could have caused this. Any ideas ?

```
Assertion failed: (m_code == nulAssertion failed: (m_code == nulAssertion failed: (m_code == nullptr), function balloon, file liAssertion failed: (m_code == nulAssertion failed: (m_code == nullptr), function balloon, file lilptr), function balloon, file libredex/DexClass.cpp, line 470.
bredex/DexClass.cpp, line 470.
Assertion failed: (m_code == nullptr), function balloon, file lilptr), function balloon, file libredex/DexClass.cpp, line 470.
bredex/DexClass.cpp, line 470.
bredex/DexClass.cpp, line 470.
lptr), function balloon, file libredex/DexClass.cpp, line 470.
0   redex-all                           0x00000001033a7e82 _Z23crash_backtrace_handleri + 50
0   redex-all                           0x00000001033a7e82 _Z23crash_backtrace_handleri + 50
0   redex-all                           0x00000001033a7e82 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff79b17f5a _sigtramp + 26
1   libsystem_platform.dylib            0x00007fff79b17f5a _sigtramp + 26
1   libsystem_platform.dylib            0x00007fff79b17f5a _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
2   ???                                 0x0000000000000000 0x0 + 0
2   ???                                 0x0000000000000000 0x0 + 0
Traceback (most recent call last):
  File "/tmp/redex.DGXnS9/redex.py", line 714, in <module>
    run_redex(args)
  File "/tmp/redex.DGXnS9/redex.py", line 630, in run_redex
    debugger)
```

**Comment by tapthaker** [comment]
@thezhangwei : Sorry, cannot do that. We found that the issue was with Proguard. We are able to fix this issue disabling proguard and only using ReDex.

**Comment by thezhangwei** [comment]
Thanks for the update. Should we consider this as resolved then?

**Comment by tapthaker** [comment]
Yes. Closing this issue.
