### ISSUE TITLE
Error -6

### ISSUE THREAD

**Issue by Jacoppy** [facebook/redex#362]
Hi, I am currently working with Instrumented Android application built on Soot.
I am encountering the following error after the instrumentation:
```
`service/dataflow/LiveRange.cpp:92: {anonymous}::UDChains {anonymous}::calculate_ud_chains(IRCode*): assertion `!defs.is_top() && defs.size() > 0' failed.
Found use without def when processing [0x7fd7a96c1920]MOVE_OBJECT v0, v17
/tmp/redex.mIsjIe/redex-all(+0x56954b)[0x55bc949fb54b]
/tmp/redex.mIsjIe/redex-all(_Z11assert_failPKcS0_jS0_S0_z+0xd4)[0x55bc949fb674]
/tmp/redex.mIsjIe/redex-all(_ZN10live_range18renumber_registersEP6IRCodeb+0x1da8)[0x55bc94980638]
/tmp/redex.mIsjIe/redex-all(+0x3ad3ea)[0x55bc9483f3ea]
/tmp/redex.mIsjIe/redex-all(+0x3ada1a)[0x55bc9483fa1a]
/tmp/redex.mIsjIe/redex-all(_ZZN9WorkQueueIP8DexClassDnN8regalloc14graph_coloring9Allocator5StatsEE7run_allERKS5_ENKUlP11WorkerStateIS1_DnS5_EmE_clESB_m+0x488)[0x55bc94840dd8]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1(+0x11bcd)[0x7fd7c9228bcd]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fd7c8fff6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fd7c7d9688f]
Failed to allocate Lcn/domob/android/a/a/a$2;.onGeolocationPermissionsShowPrompt:(Ljava/lang/String;Landroid/webkit/GeolocationPermissions$Callback;)V
CFG:
 Block B0: entry
   preds:
   [0x7fd7a96c0120] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v22
   [0x7fd7a96c0150] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v23
   [0x7fd7a96c0180] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v24
   [0x7fd7a96c4b10] POSITION: SourceFile:116
   [0x7fd7a96c01b0] OPCODE: MOVE_OBJECT v0, v22
   [0x7fd7a96c4b40] POSITION: SourceFile:116
   [0x7fd7a96c01e0] OPCODE: MOVE_OBJECT v1, v23
   [0x7fd7a96c4b70] POSITION: SourceFile:116
   [0x7fd7a96c0210] OPCODE: MOVE_OBJECT v2, v24
   [0x7fd7a96c4ba0] POSITION: SourceFile:116
   [0x7fd7a96c0240] OPCODE: INVOKE_SUPER v0, v1, v2, Landroid/webkit/WebChromeClient;.onGeolocationPermissionsShowPrompt:(Ljava/lang/String;Landroid/webkit/GeolocationPermissions$Callback;)V
   [0x7fd7a96c0270] OPCODE: NEW_INSTANCE Ljava/util/Random;
   [0x7fd7a96c2f50] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v3
   [0x7fd7a96c4bd0] DEBUG: DBG_START_LOCAL v3 $r2:Ljava/util/Random;;
   [0x7fd7a96c02a0] OPCODE: INVOKE_DIRECT v3, Ljava/util/Random;.<init>:()V
   [0x7fd7a96c02d0] OPCODE: CONST v5, 50
   [0x7fd7a96c0340] OPCODE: INVOKE_VIRTUAL v3, v5, Ljava/util/Random;.nextInt:(I)I
   [0x7fd7a96c03b0] OPCODE: MOVE_RESULT v4
   [0x7fd7a96c4c00] DEBUG: DBG_START_LOCAL v4 $i0:I;
   [0x7fd7a96c0420] OPCODE: IF_GEZ v4
   succs: (branch B2) (goto B1)
 Block B1:
   preds: (goto B0)
   [0x7fd7a96c0490] OPCODE: CONST v6, 0
   [0x7fd7a96c4c30] DEBUG: DBG_START_LOCAL v6 $z7:Z;
   [0x7fd7a96c0500] OPCODE: GOTO 
   succs: (goto B3)
 Block B2:
   preds: (branch B0)
   [0x7fd7a96c24e0] TARGET: SIMPLE 0x7fd7a96c0420
   [0x7fd7a96c0570] OPCODE: CONST v6, 1
   succs: (goto B3)
 Block B3:
   preds: (goto B1) (goto B2)
   [0x7fd7a96c2530] TARGET: SIMPLE 0x7fd7a96c0500
   [0x7fd7a96c05e0] OPCODE: MOVE v7, v6
   [0x7fd7a96c4c60] DEBUG: DBG_START_LOCAL v7 z0:Z;
   [0x7fd7a96c0650] OPCODE: CONST v5, 80
   [0x7fd7a96c06c0] OPCODE: INVOKE_VIRTUAL v3, v5, Ljava/util/Random;.nextInt:(I)I
   [0x7fd7a96c0730] OPCODE: MOVE_RESULT v8
   [0x7fd7a96c4c90] DEBUG: DBG_START_LOCAL v8 $i1:I;
   [0x7fd7a96c07a0] OPCODE: IF_GEZ v8
   succs: (branch B5) (goto B4)
 Block B4:
   preds: (goto B3)
   [0x7fd7a96c0810] OPCODE: CONST v9, 0
   [0x7fd7a96c4cc0] DEBUG: DBG_START_LOCAL v9 $z8:Z;
   [0x7fd7a96c0880] OPCODE: GOTO 
   succs: (goto B6)
 Block B5:
   preds: (branch B3)
   [0x7fd7a96c2580] TARGET: SIMPLE 0x7fd7a96c07a0
   [0x7fd7a96c08f0] OPCODE: CONST v9, 1
   succs: (goto B6)
 Block B6:
   preds: (goto B4) (goto B5)
   [0x7fd7a96c25d0] TARGET: SIMPLE 0x7fd7a96c0880
   [0x7fd7a96c0960] OPCODE: MOVE v10, v9
   [0x7fd7a96c4cf0] DEBUG: DBG_START_LOCAL v10 z1:Z;
   [0x7fd7a96c09d0] OPCODE: INVOKE_VIRTUAL v3, Ljava/util/Random;.nextBoolean:()Z
   [0x7fd7a96c0a40] OPCODE: MOVE_RESULT v11
   [0x7fd7a96c4d20] DEBUG: DBG_START_LOCAL v11 z3:Z;
   [0x7fd7a96c0ab0] OPCODE: INVOKE_VIRTUAL v3, Ljava/util/Random;.nextBoolean:()Z
   [0x7fd7a96c0b20] OPCODE: MOVE_RESULT v12
   [0x7fd7a96c4d50] DEBUG: DBG_START_LOCAL v12 z4:Z;
   [0x7fd7a96c0b90] OPCODE: INVOKE_VIRTUAL v3, Ljava/util/Random;.nextBoolean:()Z
   [0x7fd7a96c0c00] OPCODE: MOVE_RESULT v13
   [0x7fd7a96c4d80] DEBUG: DBG_START_LOCAL v13 z5:Z;
   [0x7fd7a96c0c70] OPCODE: INVOKE_VIRTUAL v3, Ljava/util/Random;.nextBoolean:()Z
   [0x7fd7a96c0ce0] OPCODE: MOVE_RESULT v14
   [0x7fd7a96c4db0] DEBUG: DBG_START_LOCAL v14 z6:Z;
   [0x7fd7a96c0d50] OPCODE: IF_NEZ v11
   succs: (branch B9) (goto B7)
 Block B7:
   preds: (goto B6)
   [0x7fd7a96c0dc0] OPCODE: IF_NEZ v12
   succs: (branch B9) (goto B8)
 Block B8:
   preds: (goto B7)
   [0x7fd7a96c0e30] OPCODE: IF_NEZ v13
   succs: (branch B32) (goto B9)
 Block B9:
   preds: (branch B6) (branch B7) (goto B8)
   [0x7fd7a96c2620] TARGET: SIMPLE 0x7fd7a96c0d50
   [0x7fd7a96c2670] TARGET: SIMPLE 0x7fd7a96c0dc0
   [0x7fd7a96c0ea0] OPCODE: IF_EQZ v12
   succs: (branch B12) (goto B10)
 Block B10:
   preds: (goto B9)
   [0x7fd7a96c0f10] OPCODE: IF_NEZ v11
   succs: (branch B12) (goto B11)
 Block B11:
   preds: (goto B10)
   [0x7fd7a96c0f80] OPCODE: IF_EQZ v13
   succs: (branch B32) (goto B12)
 Block B12:
   preds: (branch B9) (branch B10) (goto B11)
   [0x7fd7a96c2710] TARGET: SIMPLE 0x7fd7a96c0ea0
   [0x7fd7a96c2760] TARGET: SIMPLE 0x7fd7a96c0f10
   [0x7fd7a96c0ff0] OPCODE: IF_NEZ v13
   succs: (branch B15) (goto B13)
 Block B13:
   preds: (goto B12)
   [0x7fd7a96c1060] OPCODE: IF_NEZ v10
   succs: (branch B15) (goto B14)
 Block B14:
   preds: (goto B13)
   [0x7fd7a96c10d0] OPCODE: IF_NEZ v11
   succs: (branch B32) (goto B15)
 Block B15:
   preds: (branch B12) (branch B13) (goto B14)
   [0x7fd7a96c2800] TARGET: SIMPLE 0x7fd7a96c0ff0
   [0x7fd7a96c2850] TARGET: SIMPLE 0x7fd7a96c1060
   [0x7fd7a96c1140] OPCODE: IF_EQZ v12
   succs: (branch B17) (goto B16)
 Block B16:
   preds: (goto B15)
   [0x7fd7a96c11b0] OPCODE: IF_NEZ v14
   succs: (branch B32) (goto B17)
 Block B17:
   preds: (branch B15) (goto B16)
   [0x7fd7a96c28f0] TARGET: SIMPLE 0x7fd7a96c1140
   [0x7fd7a96c1220] OPCODE: IF_NEZ v13
   succs: (branch B20) (goto B18)
 Block B18:
   preds: (goto B17)
   [0x7fd7a96c1290] OPCODE: IF_EQZ v12
   succs: (branch B20) (goto B19)
 Block B19:
   preds: (goto B18)
   [0x7fd7a96c1300] OPCODE: IF_NEZ v14
   succs: (branch B32) (goto B20)
 Block B20:
   preds: (branch B17) (branch B18) (goto B19)
   [0x7fd7a96c2990] TARGET: SIMPLE 0x7fd7a96c1220
   [0x7fd7a96c29e0] TARGET: SIMPLE 0x7fd7a96c1290
   [0x7fd7a96c1370] OPCODE: IF_EQZ v12
   succs: (branch B22) (goto B21)
 Block B21:
   preds: (goto B20)
   [0x7fd7a96c13e0] OPCODE: IF_NEZ v13
   succs: (branch B32) (goto B22)
 Block B22:
   preds: (branch B20) (goto B21)
   [0x7fd7a96c2a80] TARGET: SIMPLE 0x7fd7a96c1370
   [0x7fd7a96c1450] OPCODE: IF_NEZ v11
   succs: (branch B25) (goto B23)
 Block B23:
   preds: (goto B22)
   [0x7fd7a96c14c0] OPCODE: IF_EQZ v12
   succs: (branch B25) (goto B24)
 Block B24:
   preds: (goto B23)
   [0x7fd7a96c1530] OPCODE: IF_NEZ v13
   succs: (branch B32) (goto B25)
 Block B25:
   preds: (branch B22) (branch B23) (goto B24)
   [0x7fd7a96c2b20] TARGET: SIMPLE 0x7fd7a96c1450
   [0x7fd7a96c2b70] TARGET: SIMPLE 0x7fd7a96c14c0
   [0x7fd7a96c15a0] OPCODE: IF_NEZ v7
   succs: (branch B28) (goto B26)
 Block B26:
   preds: (goto B25)
   [0x7fd7a96c1610] OPCODE: IF_NEZ v10
   succs: (branch B28) (goto B27)
 Block B27:
   preds: (goto B26)
   [0x7fd7a96c1680] OPCODE: GOTO 
   succs: (goto B32)
 Block B28:
   preds: (branch B25) (branch B26)
   [0x7fd7a96c2c10] TARGET: SIMPLE 0x7fd7a96c15a0
   [0x7fd7a96c2c60] TARGET: SIMPLE 0x7fd7a96c1610
   [0x7fd7a96c16f0] OPCODE: IF_NEZ v7
   succs: (branch B31) (goto B29)
 Block B29:
   preds: (goto B28)
   [0x7fd7a96c1760] OPCODE: IF_NEZ v10
   succs: (branch B31) (goto B30)
 Block B30:
   preds: (goto B29)
   [0x7fd7a96c17d0] OPCODE: GOTO 
   succs: (goto B32)
 Block B31:
   preds: (branch B28) (branch B29)
   [0x7fd7a96c2d00] TARGET: SIMPLE 0x7fd7a96c16f0
   [0x7fd7a96c2d50] TARGET: SIMPLE 0x7fd7a96c1760
   [0x7fd7a96c1840] OPCODE: NEW_INSTANCE Landroid/content/Intent;
   [0x7fd7a96c4000] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v15
   [0x7fd7a96c4de0] DEBUG: DBG_START_LOCAL v15 $r2:Landroid/content/Intent;;
   [0x7fd7a96c18b0] OPCODE: CONST_CLASS Lcom/yteu/hfdh/Bona;
   [0x7fd7a96c40b0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v18
   [0x7fd7a96c1920] OPCODE: MOVE_OBJECT v0, v17
   [0x7fd7a96c1990] OPCODE: MOVE_OBJECT v1, v18
   [0x7fd7a96c1a00] OPCODE: INVOKE_STATIC v0, v1, Lcom/yteu/hfdh/c/h;.a:(Landroid/content/Context;Ljava/lang/Class;)Ljava/lang/Class;
   [0x7fd7a96c1a70] OPCODE: MOVE_RESULT_OBJECT v16
   [0x7fd7a96c4e10] DEBUG: DBG_START_LOCAL v16 $r3:Ljava/lang/Class;;
   [0x7fd7a96c1ae0] OPCODE: MOVE_OBJECT v0, v17
   [0x7fd7a96c1b50] OPCODE: MOVE_OBJECT v1, v16
   [0x7fd7a96c1bc0] OPCODE: INVOKE_DIRECT v15, v0, v1, Landroid/content/Intent;.<init>:(Landroid/content/Context;Ljava/lang/Class;)V
   [0x7fd7a96c1c30] OPCODE: MOVE_OBJECT v0, v17
   [0x7fd7a96c1ca0] OPCODE: INVOKE_STATIC v0, Lcom/yteu/hfdh/c/h;.p:(Landroid/content/Context;)I
   [0x7fd7a96c1d10] OPCODE: MOVE_RESULT v19
   [0x7fd7a96c4e40] DEBUG: DBG_START_LOCAL v19 $i3:I;
   [0x7fd7a96c1d80] OPCODE: CONST_STRING "l"
   [0x7fd7a96c44e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v20
   [0x7fd7a96c1df0] OPCODE: MOVE_OBJECT v0, v20
   [0x7fd7a96c1e60] OPCODE: MOVE v1, v19
   [0x7fd7a96c1ed0] OPCODE: INVOKE_VIRTUAL v15, v0, v1, Landroid/content/Intent;.putExtra:(Ljava/lang/String;I)Landroid/content/Intent;
   [0x7fd7a96c1f40] OPCODE: CONST v5, 268435456
   [0x7fd7a96c1fb0] OPCODE: INVOKE_VIRTUAL v15, v5, Landroid/content/Intent;.addFlags:(I)Landroid/content/Intent;
   [0x7fd7a96c2020] OPCODE: MOVE_OBJECT v0, v17
   [0x7fd7a96c2050] OPCODE: INVOKE_VIRTUAL v0, v15, Landroid/content/Context;.startActivity:(Landroid/content/Intent;)V
   [0x7fd7a96c2080] OPCODE: MOVE_OBJECT v0, v17
   [0x7fd7a96c20f0] OPCODE: INVOKE_STATIC v0, Lcom/yteu/hfdh/c/h;.x:(Landroid/content/Context;)V
   [0x7fd7a96c2160] OPCODE: RETURN_VOID 
   succs:
 Block B32:
   preds: (branch B8) (branch B11) (branch B14) (branch B16) (branch B19) (branch B21) (branch B24) (goto B27) (goto B30)
   [0x7fd7a96c26c0] TARGET: SIMPLE 0x7fd7a96c0e30
   [0x7fd7a96c27b0] TARGET: SIMPLE 0x7fd7a96c0f80
   [0x7fd7a96c28a0] TARGET: SIMPLE 0x7fd7a96c10d0
   [0x7fd7a96c2940] TARGET: SIMPLE 0x7fd7a96c11b0
   [0x7fd7a96c2a30] TARGET: SIMPLE 0x7fd7a96c1300
   [0x7fd7a96c2ad0] TARGET: SIMPLE 0x7fd7a96c13e0
   [0x7fd7a96c2bc0] TARGET: SIMPLE 0x7fd7a96c1530
   [0x7fd7a96c2cb0] TARGET: SIMPLE 0x7fd7a96c1680
   [0x7fd7a96c2da0] TARGET: SIMPLE 0x7fd7a96c17d0
   [0x7fd7a96c21d0] OPCODE: RETURN_VOID 
   succs:
 Block B33:
   preds:
   [0x7fd7a96c4e70] POSITION: SourceFile:117
   [0x7fd7a96c2240] FALLTHROUGH
   [0x7fd7a96c4ea0] POSITION: SourceFile:117
   [0x7fd7a96c22b0] FALLTHROUGH
   [0x7fd7a96c4ed0] POSITION: SourceFile:117
   [0x7fd7a96c2320] FALLTHROUGH
   [0x7fd7a96c4f00] POSITION: SourceFile:117
   [0x7fd7a96c2390] FALLTHROUGH
   [0x7fd7a96c4f30] POSITION: SourceFile:117
   [0x7fd7a85ed140] FALLTHROUGH
   [0x7fd7a96c4f60] POSITION: SourceFile:117
   [0x7fd7a96c23c0] FALLTHROUGH
   [0x7fd7a96c4f90] POSITION: SourceFile:117
   [0x7fd7a96c2430] FALLTHROUGH
   succs:
 Block B34:
   preds:
   [0x7fd7a96c4fc0] DEBUG: DBG_END_LOCAL v16
   [0x7fd7a96c4ff0] DEBUG: DBG_END_LOCAL v7
   [0x7fd7a96c5020] DEBUG: DBG_END_LOCAL v14
   [0x7fd7a96c5050] DEBUG: DBG_END_LOCAL v12
   [0x7fd7a96c5080] DEBUG: DBG_END_LOCAL v13
   [0x7fd7a96c50b0] DEBUG: DBG_END_LOCAL v10
   [0x7fd7a96c50e0] DEBUG: DBG_END_LOCAL v19
   [0x7fd7a96c5110] DEBUG: DBG_END_LOCAL v15
   [0x7fd7a96c5140] DEBUG: DBG_END_LOCAL v6
   [0x7fd7a96c5170] DEBUG: DBG_END_LOCAL v4
   [0x7fd7a96c51a0] DEBUG: DBG_END_LOCAL v8
   [0x7fd7a96c51d0] DEBUG: DBG_END_LOCAL v3
   [0x7fd7a96c5200] DEBUG: DBG_END_LOCAL v11
   [0x7fd7a96c5230] DEBUG: DBG_END_LOCAL v9
   succs:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Redex assertion failure
/tmp/redex.mIsjIe/redex-all(+0x56954b)[0x55bc949fb54b]
/tmp/redex.mIsjIe/redex-all(_Z23crash_backtrace_handleri+0x8)[0x55bc949fb588]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7fd7c7cb3f20]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7fd7c7cb3e97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7fd7c7cb5801]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8b7)[0x7fd7c86a88b7]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a06)[0x7fd7c86aea06]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a41)[0x7fd7c86aea41]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0x49)[0x7fd7c86aecc9]
/tmp/redex.mIsjIe/redex-all(+0x3ad804)[0x55bc9483f804]
/tmp/redex.mIsjIe/redex-all(+0x3ada1a)[0x55bc9483fa1a]
/tmp/redex.mIsjIe/redex-all(_ZZN9WorkQueueIP8DexClassDnN8regalloc14graph_coloring9Allocator5StatsEE7run_allERKS5_ENKUlP11WorkerStateIS1_DnS5_EmE_clESB_m+0x488)[0x55bc94840dd8]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1(+0x11bcd)[0x7fd7c9228bcd]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fd7c8fff6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fd7c7d9688f]
Traceback (most recent call last):
  File "/tmp/redex.mIsjIe/redex.py", line 816, in <module>
    run_redex(args)
  File "/tmp/redex.mIsjIe/redex.py", line 794, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.mIsjIe/redex.py", line 214, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.mIsjIe/redex-gdb-d6KFuU.sh or under lldb by running /tmp/redex.mIsjIe/redex-lldb-Aca8Ij.sh
`
```

The application works correctly on all the emulators I tried . There is a way by which I can fix it? I tried already the configurations you suggested for https://github.com/facebook/redex/issues/343

**Comment by justinjhendrick** [comment]
I think this was fixed by 4ce26771deb69cb26dce69c48f327e22405d4d10
