### ISSUE TITLE
Error with dump_classes_from_hprof.py

### ISSUE THREAD

**Issue by Yves0** [facebook/redex#371]
```
➜  redex git:(master) ✗ python2 ./tools/hprof/dump_classes_from_hprof.py --hprof /tmp/exam_DUMP.hprof > /tmp/exam_classes.txt
Traceback (most recent call last):
  File "./tools/hprof/dump_classes_from_hprof.py", line 1267, in <module>
    hp = parse_filename(args.hprof)
  File "./tools/hprof/dump_classes_from_hprof.py", line 59, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "./tools/hprof/dump_classes_from_hprof.py", line 47, in parse_hprof_dump
    record = Record.read_from_stream(hprof_data, instream)
  File "./tools/hprof/dump_classes_from_hprof.py", line 172, in read_from_stream
    if tag == HprofTag.STRING.value:
AttributeError: 'int' object has no attribute 'value'
```

**Comment by Yves0** [comment]
you must install enum34 and run with python2
```
pip2 install enum34
```
