### ISSUE TITLE
launch app  crash : java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by anpingxiong** [facebook/redex#378]
```
irtualCore: ===========  64Bit Engine(Main) ===========
03-24 16:52:39.735 6840-6840/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.kwai.sogame, PID: 6840
                                                 java.lang.AbstractMethodError: abstract method "boolean android.content.ContentProvider.onCreate()"
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5326)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4863)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4803)
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:157)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5597)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)



```

launch app crash

` redex ./app-release.apk -o ./app-redex-signed.apk --sign -s *** -a *** -p *** -P proguard-rules.pro -c default.config`

no crash case:
`redex ./app-release.apk -o ./app-redex-signed.apk --sign -s *** -a *** -p *** -c default.config`

And default.config is:

```
{
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "BridgePass",
      "SynthPass",
      "FinalInlinePass",
      "DelSuperPass",
      "MethodInlinePass",
      "PeepholePass",
      "ConstantPropagationPass",
      "LocalDcePass",
      "RemoveUnreachablePass",
      "RemoveGotosPass",
      "DedupBlocksPass",
      "SingleImplPass",
      "ReorderInterfacesPass",
      "RemoveEmptyClassesPass",
      "InterDexPass",
      "ShortenSrcStringsPass",
      "RegAllocPass",
      "CopyPropagationPass",
      "LocalDcePass"
    ]
  },
  "InterDexPass" : {
     "normal_primary_dex": false,
       "coldstart_classes": "list_of_classes.txt"
  },
  "coldstart_classes": "list_of_classes.txt",
  "FinalInlinePass" : {
    "propagate_static_finals": true,
    "replace_encodable_clinits": true
  },
  "MethodInlinePass": {
    "throws": true,
    "multiple_callers": true,
    "black_list": []
  },
  "ConstantPropagationPassV3" : {
    "blacklist": [],
    "replace_moves_with_consts": true,
    "fold_arithmetic": true
  },
  "RegAllocPass" : {
    "live_range_splitting": "0"
  },
  "CopyPropagationPass" : {
    "eliminate_const_literals": false,
    "full_method_analysis": true
  },
  "PeepholePass" : {
    "disabled_peepholes": [
      "Replace_PutGet",
      "Replace_PutGetWide",
      "Replace_PutGetObject",
      "Replace_PutGetShort",
      "Replace_PutGetChar",
      "Replace_PutGetByte",
      "Replace_PutGetBoolean"
    ]
  },
  "keep_packages": [
    "Lcom/fasterxml/jackson/",
    "Lcom/google/dexmaker/mockito/"
  ],
  "keep_annotations": [
    "Lcom/google/common/annotations/VisibleForTesting;"
  ],
  "proguard_map_output": "redex_pg_mapping.txt",
  "stats_output": "stats.txt",
  "bytecode_offset_map": "bytecode_offset_map.txt",
  "line_number_map_v2": "redex-line-number-map-v2",
  "method_move_map" : "redex-moved-methods-map.txt",
  "string_sort_mode" : "class_order",
  "bytecode_sort_mode" : "class_order",
  "ir_type_checker": {
    "run_after_each_pass" : false,
    "polymorphic_constants" : false,
    "verify_moves" : false
  }
}
```

Help.
Thanks!

**Comment by anpingxiong** [comment]
launch app crash 

` redex ./app-release.apk  -o ./app-redex-signed.apk  --sign -s  *** -a ***  -p *** -P proguard-rules.pro  -c  default.config`

**Comment by anpingxiong** [comment]
no crash  case:
redex ./app-release.apk -o ./app-redex-signed.apk --sign -s *** -a *** -p ***  -c default.config

**Comment by anpingxiong** [comment]
And default.config is:

```
{
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "BridgePass",
      "SynthPass",
      "FinalInlinePass",
      "DelSuperPass",
      "MethodInlinePass",
      "PeepholePass",
      "ConstantPropagationPass",
      "LocalDcePass",
      "RemoveUnreachablePass",
      "RemoveGotosPass",
      "DedupBlocksPass",
      "SingleImplPass",
      "ReorderInterfacesPass",
      "RemoveEmptyClassesPass",
      "InterDexPass",
      "ShortenSrcStringsPass",
      "RegAllocPass",
      "CopyPropagationPass",
      "LocalDcePass"
    ]
  },
  "InterDexPass" : {
     "normal_primary_dex": false,
       "coldstart_classes": "list_of_classes.txt"
  },
  "coldstart_classes": "list_of_classes.txt",
  "FinalInlinePass" : {
    "propagate_static_finals": true,
    "replace_encodable_clinits": true
  },
  "MethodInlinePass": {
    "throws": true,
    "multiple_callers": true,
    "black_list": []
  },
  "ConstantPropagationPassV3" : {
    "blacklist": [],
    "replace_moves_with_consts": true,
    "fold_arithmetic": true
  },
  "RegAllocPass" : {
    "live_range_splitting": "0"
  },
  "CopyPropagationPass" : {
    "eliminate_const_literals": false,
    "full_method_analysis": true
  },
  "PeepholePass" : {
    "disabled_peepholes": [
      "Replace_PutGet",
      "Replace_PutGetWide",
      "Replace_PutGetObject",
      "Replace_PutGetShort",
      "Replace_PutGetChar",
      "Replace_PutGetByte",
      "Replace_PutGetBoolean"
    ]
  },
  "keep_packages": [
    "Lcom/fasterxml/jackson/",
    "Lcom/google/dexmaker/mockito/"
  ],
  "keep_annotations": [
    "Lcom/google/common/annotations/VisibleForTesting;"
  ],
  "proguard_map_output": "redex_pg_mapping.txt",
  "stats_output": "stats.txt",
  "bytecode_offset_map": "bytecode_offset_map.txt",
  "line_number_map_v2": "redex-line-number-map-v2",
  "method_move_map" : "redex-moved-methods-map.txt",
  "string_sort_mode" : "class_order",
  "bytecode_sort_mode" : "class_order",
  "ir_type_checker": {
    "run_after_each_pass" : false,
    "polymorphic_constants" : false,
    "verify_moves" : false
  }
}

```

**Comment by justinjhendrick** [comment]
When you add a proguard config, lots of new passes are enabled. You can tell by enabling trace

```
$ export TRACE=1
```
by default the logging goes to stdout, but you can send it to a file like this
```
$ export TRACEFILE=~/tmp/trace.txt
```

then running redex without progaurd will print when a pass didn't run because of the lack of a proguard config. One of those passes must have caused this problem. Could you narrow down which one?

**Comment by anpingxiong** [comment]
Thank you to answer。 I remove  RemoveUnreachablePass  ,and it‘s ok.  but i don’t know why

**Comment by anpingxiong** [comment]
Thank you to answer。 I remove RemoveUnreachablePass ,and it‘s ok. but i don’t know why

**Comment by anpingxiong** [comment]
> When you add a proguard config, lots of new passes are enabled. You can tell which ones by enabling trace logging
> 
> ```
> $ export TRACE=1
> ```
> by default the logging goes to stdout, but you can send it to a file like this
> 
> ```
> $ export TRACEFILE=~/tmp/trace.txt
> ```
> then running redex without progaurd will print when a pass didn't run because of the lack of a proguard config. One of those passes must have caused this problem. Could you narrow down which one?


Thank you to answer。 I remove RemoveUnreachablePass ,and it‘s ok. but i don’t know why

**Comment by justinjhendrick** [comment]
`RemoveUnreachablePass` removes classes, methods, and fields that are not reachable from any of the program "roots" that Redex knows about. When it removes something that causes a crash, it's usually because we didn't specify all the roots that it needs to know about. You do that by specifying proguard `-keep` rules for classes, methods, and fields that are accessed via reflection, native code, from the framework code, or from some other unexpected place.

**Comment by anpingxiong** [comment]
> `RemoveUnreachablePass` removes classes, methods, and fields that are not reachable from any of the program "roots" that Redex knows about. When it removes something that causes a crash, it's usually because we didn't specify all the roots that it needs to know about. You do that by specifying proguard `-keep` rules for classes, methods, and fields that are accessed via reflection, native code, from the framework code, or from some other unexpected place.

ok,thanks.

**Comment by justinjhendrick** [comment]
Seems resolved. Closing
