### ISSUE TITLE
Redex can't see folly even after installing it from brew

### ISSUE THREAD

**Issue by adelnizamutdinov** [facebook/redex#388]
```
redex app/build/outputs/apk/release/app-release.apk -o lol.apk
dyld: Library not loaded: /usr/local/lib/libfolly.57.dylib
  Referenced from: /usr/local/bin/redex-all
  Reason: image not found
Traceback (most recent call last):
  File "/tmp/redex.K3Z5lE/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/redex-all', '--apkdir', '/tmp/redex.K3Z5lE/tmpfkpbcipp.redex_extracted_apk', '--outdir', '/tmp/redex.K3Z5lE/tmpj8g_i7_t.redex_dexen', '/tmp/redex.K3Z5lE/tmpj8g_i7_t.redex_dexen/dex0/classes.dex']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.K3Z5lE/redex.py", line 640, in <module>
    run_redex(args)
  File "/tmp/redex.K3Z5lE/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.K3Z5lE/redex.py", line 165, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.K3Z5lE/redex-gdb-l5uzqmk5.sh or under lldb by running /tmp/redex.K3Z5lE/redex-lldb-rw5n_r7h.sh
```

I did `brew install folly`. What else can I do to make redex work? Thanks

**Comment by justinjhendrick** [comment]
It looks like you installed and built redex successfully but it crashed when you ran it.

Try rerunning it inside a debugger. You can pass `--gdb` or `--lldb` to drop into a debugger when the C++ binary starts running. Or, the error message created a script for you with the same inputs and gdb included: `/tmp/redex.K3Z5lE/redex-gdb-l5uzqmk5.sh` or `/tmp/redex.K3Z5lE/redex-lldb-rw5n_r7h.sh`

**Comment by justinjhendrick** [comment]
Then, once you reach the abort, you can print the stack frames and paste them here. I'll take a look

**Comment by adelnizamutdinov** [comment]
passing `--gdb` to `redex` results in a python error:

```
redex app/build/outputs/apk/release/app-release.apk --gdb -o lol.apk 
Traceback (most recent call last):
  File "/tmp/redex.cNy6ux/redex.py", line 640, in <module>
    run_redex(args)
  File "/tmp/redex.cNy6ux/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.cNy6ux/redex.py", line 158, in run_pass
    raise err
  File "/tmp/redex.cNy6ux/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gdb': 'gdb'
```

also there aren't such scripts generated by redex. `ls -a1 /tmp` shows:

```
.
..
.DS_Store
.keystone_install_lock
powerlog
```

**Comment by justinjhendrick** [comment]
I think redex is picky about the order of arguments

The help message shows that it wants `--gdb` and all other options before the input apk.
```
usage: redex.py [-h] [-o [OUT]] [-j JARPATHS] [--redex-binary [REDEX_BINARY]]
                [-c CONFIG] [--sign] [-s [KEYSTORE]] [-a [KEYALIAS]]
                [-p [KEYPASS]] [-u] [--unpack-dest UNPACK_DEST] [-w [WARN]]
                [-d] [--dev] [-m [PROGUARD_MAP]] [-q [PRINTSEEDS]]
                [--used-js-assets USED_JS_ASSETS] [-P PROGUARD_CONFIGS]
                [-k [KEEP]] [-S PASSTHRU] [-J PASSTHRU_JSON] [--lldb] [--gdb]
                [--ignore-zipalign] [--verify-none-mode]
                [--enable-instrument-pass] [--is-art-build]
                [--page-align-libs]
                [--side-effect-summaries SIDE_EFFECT_SUMMARIES]
                [--escape-summaries ESCAPE_SUMMARIES] [--stop-pass STOP_PASS]
                [--output-ir OUTPUT_IR]
                input_apk
```

Try changing the order so that the input apk is last and see what happens

**Comment by justinjhendrick** [comment]
And as far as I know, we don't depend on folly. What leads you to believe we need folly?

**Comment by adelnizamutdinov** [comment]
aha!

```
Process 1877 launched: '/usr/local/bin/redex-all' (x86_64)
dyld: Library not loaded: /usr/local/lib/libfolly.57.dylib
  Referenced from: /usr/local/bin/redex-all
  Reason: image not found
Process 1877 stopped
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001001df456 dyld`__abort_with_payload + 10
dyld`__abort_with_payload:
->  0x1001df456 <+10>: jae    0x1001df460               ; <+20>
    0x1001df458 <+12>: movq   %rax, %rdi
    0x1001df45b <+15>: jmp    0x1001dea5d               ; cerror_nocancel
    0x1001df460 <+20>: retq   
Target 0: (redex-all) stopped.
```

I had libfolly dylib in my `/usr/local/lib`, I also copied it as `libfollly57.dylib`

![image](https://user-images.githubusercontent.com/1594148/54853472-0377ce00-4d01-11e9-8285-1c210dd3ce59.png)

but it still doesn't work

**Comment by adelnizamutdinov** [comment]
> What leads you to believe we need folly?

this

`dyld: Library not loaded: /usr/local/lib/libfolly.57.dylib`

**Comment by justinjhendrick** [comment]
hmmm... Weird. I don't know where that dependency is coming from

**Comment by Feng23** [comment]
Can you share how do you build the `redex` tool?

**Comment by justinjhendrick** [comment]
Is the bash environment variable `LD_PRELOAD` set to anything?

**Comment by justinjhendrick** [comment]
What does `otool -L redex-all` show? Here's mine at revision 7e09e7bf14cd73c8a718d5c7f6fa47d96853f1af

```
$ otool -L redex-all
redex-all:
	/usr/local/opt/boost/lib/libboost_iostreams-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/local/opt/jsoncpp/lib/libjsoncpp.11.dylib (compatibility version 11.0.0, current version 1.8.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

**Comment by newobj** [comment]
Which commit did you build redex from?

**Comment by justinjhendrick** [comment]
Any resolution here? Did you get redex to work?

**Comment by adelnizamutdinov** [comment]
sorry, no =/ gave up on redex, we can probably close this
