### ISSUE TITLE
I use the ANDROID_SDK=/path/to/android/sdk redex [... arguments ...] 

### ISSUE THREAD

**Issue by microsoftBoy** [facebook/redex#421]
shuai@ubuntu:~/Desktop/file$ find /opt/android/android-sdk-linux/ -name zipalign/opt/android/android-sdk-linux/build-tools/29.0.2/zipalign
shuai@ubuntu:~/Desktop/file$ ANDROID_HOME=/opt/android/android-sdk-linux redex release.apk -o out.apk
WARNING: No inliner config
Couldn't find zipalign. See README.md to resolve this.
Traceback (most recent call last):
  File "/tmp/redex.nKk8Xg/redex.py", line 932, in <module>
    run_redex(args)
  File "/tmp/redex.nKk8Xg/redex.py", line 916, in run_redex
    finalize_redex(state)
  File "/tmp/redex.nKk8Xg/redex.py", line 888, in finalize_redex
    state.args.page_align_libs,
  File "/tmp/redex.nKk8Xg/redex.py", line 383, in create_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
  File "/tmp/redex.nKk8Xg/redex.py", line 330, in zipalign
    raise Exception("Zipalign failed to run")
Exception: Zipalign failed to run
shuai@ubuntu:~/Desktop/file$

**Comment by int3** [comment]
Have you tried the steps in the README?
