### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type RedexException: libredex/IROpcode.cpp:34: opcode::Ref opcode::ref(IROpcode): assertion `false' failed.

### ISSUE THREAD

**Issue by hunterGao** [facebook/redex#431]
libc++abi.dylib: terminating with uncaught exception of type RedexException: libredex/IROpcode.cpp:34: opcode::Ref opcode::ref(IROpcode): assertion `false' failed.
Unexpected opcode 0xd4b0
0   redex-all                           0x000000010e2bfcf2 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff625fcf5a _sigtramp + 26
2   ???                                 0x0000000000020008 0x0 + 131080
3   libsystem_c.dylib                   0x00007fff6239a1ae abort + 127
4   libc++abi.dylib                     0x00007fff60294f8f __cxa_bad_cast + 0
5   libc++abi.dylib                     0x00007fff60295113 _ZL25default_terminate_handlerv + 241
6   libobjc.A.dylib                     0x00007fff616d6eab _ZL15_objc_terminatev + 105
7   libc++abi.dylib                     0x00007fff602b07c9 _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff602b026f _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
9   redex-all                           0x000000010e2c0073 _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 291
10  redex-all                           0x000000010e357083 _ZN6opcode3refE8IROpcode + 83
11  redex-all                           0x000000010e2aabb0 _ZN3cfg16ControlFlowGraph34primary_instruction_of_move_resultERKNS_23InstructionIteratorImplILb0EEE + 176
12  redex-all                           0x000000010de78dfd _ZN8cse_impl30CommonSubexpressionElimination5patchEbP7DexTypeP11DexTypeListb + 6173
13  redex-all                           0x000000010dea4b64 _ZZN34CommonSubexpressionEliminationPass8run_passERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFilesR11PassManagerENK3$_6clEP9DexMethod + 372
14  redex-all                           0x000000010dea3e2c _ZNSt3__110__function6__funcIZN4walk8parallel14reduce_methodsIN8cse_impl5StatsENS_6vectorIP8DexClassNS_9allocatorIS9_EEEEZN34CommonSubexpressionEliminationPass8run_passERNS7_I8DexStoreNSA_ISE_EEEER11ConfigFilesR11PassManagerE3$_6ZNSD_8run_passESH_SJ_SL_E3$_7EET_RKT0_T1_T2_RKSO_mEUlP11WorkerStateIS9_DnS6_ES9_E_NSA_ISZ_EEFS6_SY_S9_EEclEOSY_OS9_ + 268
15  redex-all                           0x000000010dea6a83 _ZN9WorkQueueIP8DexClassDnN8cse_impl5StatsEE7consumeEP11WorkerStateIS1_DnS3_ES1_ + 179
16  redex-all                           0x000000010dea67fb _ZZN9WorkQueueIP8DexClassDnN8cse_impl5StatsEE7run_allERKS3_ENKUlP11WorkerStateIS1_DnS3_EmE_clES9_m + 219
17  libboost_thread-mt.dylib            0x000000010f510758 _ZN5boost12_GLOBAL__N_112thread_proxyEPv + 136
18  libsystem_pthread.dylib             0x00007fff62606661 _pthread_body + 340
19  libsystem_pthread.dylib             0x00007fff6260650d _pthread_body + 0
20  libsystem_pthread.dylib             0x00007fff62605bf9 thread_start + 13
Traceback (most recent call last):
  File "/tmp/redex.MgAGvP/redex.py", line 233, in run_redex_binary
    subprocess.check_call(args, env=env, pass_fds=(logger.trace_fp.fileno(),))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.MgAGvP/redex-all', '--apkdir', '/tmp/redex.MgAGvP/tmpr58opb8l.redex_extracted_apk', '--outdir', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen', '--config', 'interdex.config', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen/dex0/classes.dex', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen/dex1/classes2.dex', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen/dex2/classes3.dex', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen/dex3/classes4.dex', '/tmp/redex.MgAGvP/tmphnlxxtoq.redex_dexen/dex4/classes5.dex']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.MgAGvP/redex.py", line 934, in <module>
    run_redex(args)
  File "/tmp/redex.MgAGvP/redex.py", line 912, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.MgAGvP/redex.py", line 249, in run_redex_binary
    % script_filenames
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.MgAGvP/redex-gdb-l3pays_g.sh or under lldb by running /tmp/redex.MgAGvP/redex-lldb-r2kye5u9.sh

**Comment by ssj933** [comment]
Hi! Sorry for late comment. Could I ask what is your DEX code version? Because DEX 38 have added some new opcodes and I don't think we currently support that yet, so I am suspecting that might be a reason if you are on or above DEX 38.

**Comment by justinjhendrick** [comment]
Closing due to inactivity
