### ISSUE TITLE
interdex error

### ISSUE THREAD

**Issue by Fover23** [facebook/redex#432]
I use redex after apk with R8 proguard.
my config file is:
```json
{
    "redex": {
        "passes": [
            "InterDexPass"
        ],
        "InterDexPass": {
            "static_prune": "0",
            "emit_canaries": "1",
            "coldstart_classes": "list_of_classes.txt"
        }
    }
}
```

the error is:
```bash
WARNING: No inliner config
ABORT! Inconsistency found in Dex code for Lc/e;.a:()Z.
 Encountered overwrite of `this` register by CONST v0, 0
Code:
[0x7fc274612a40] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v0
[0x7fc274612a70] OPCODE: CONST v0, 0
[0x7fc275b00720] OPCODE: THROW v0

Traceback (most recent call last):
  File "/tmp/redex.cbT87f/redex.py", line 233, in run_redex_binary
    subprocess.check_call(args, env=env, pass_fds=(logger.trace_fp.fileno(),))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.cbT87f/redex-all', '--apkdir', '/tmp/redex.cbT87f/tmpdjfj_m4y.redex_extracted_apk', '--outdir', '/tmp/redex.cbT87f/tmpto_tdfi3.redex_dexen', '--config', 'redexConfig.config', '/tmp/redex.cbT87f/tmpto_tdfi3.redex_dexen/dex0/classes.dex', '/tmp/redex.cbT87f/tmpto_tdfi3.redex_dexen/dex1/classes2.dex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.cbT87f/redex.py", line 934, in <module>
    run_redex(args)
  File "/tmp/redex.cbT87f/redex.py", line 912, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.cbT87f/redex.py", line 249, in run_redex_binary
    % script_filenames
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.cbT87f/redex-gdb-043mmffj.sh or under lldb by running /tmp/redex.cbT87f/redex-lldb-er8geuur.sh
```

**Comment by ssj933** [comment]
Could you try adding a RegAllocPass at the end and check if this can be resolved?
Overwriting `this` register may [expose bug](https://github.com/facebook/redex/blob/master/libredex/RedexOptions.h#L44) in low Android OS version.

**Comment by Fover23** [comment]
> 
> 
> Could you try adding a RegAllocPass at the end and check if this can be resolved?
> Overwriting `this` register may [expose bug](https://github.com/facebook/redex/blob/master/libredex/RedexOptions.h#L44) in low Android OS version.

yeah.add RegAllocPass  to config file,it work~ Thank you.
