### ISSUE TITLE
ABORT! Inconsistency found in Dex code for Landroid/support/v4/app/Fragment

### ISSUE THREAD

**Issue by AndroidInternal** [facebook/redex#433]
./redex -o out.apk /Users/xxx/github/transfrom/app/build/outputs/apk/debug/app-debug.apk  -c ~/temp/redex/default.config

Trace output will go to ./trace.txt
Trace settings:
TRACEFILE=3
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
WARNING: No inliner config
ABORT! Inconsistency found in Dex code for Landroid/support/v4/app/Fragment;.findFragmentByWho:(Ljava/lang/String;)Landroid/support/v4/app/Fragment;.
 Encountered overwrite of `this` register by MOVE_RESULT_OBJECT v1
Code:
[0x7fc474428ec0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v1
[0x7fc474428ee0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v2
[0x7fc474427600] DEBUG: DBG_SET_PROLOGUE_END
[0x7fc474427620] POSITION: Fragment.java:2282
[0x7fc474428e60] OPCODE: IGET_OBJECT v1, Landroid/support/v4/app/Fragment;.mWho:Ljava/lang/String;
[0x7fc474428220] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fc474428e80] OPCODE: INVOKE_VIRTUAL v2, v0, Ljava/lang/String;.equals:(Ljava/lang/Object;)Z
[0x7fc474428d40] OPCODE: MOVE_RESULT v0
[0x7fc474428d60] OPCODE: IF_EQZ v0
[0x7fc475a000a0] TARGET: SIMPLE 0x7fc4718ae1c0
[0x7fc475a01680] TARGET: SIMPLE 0x7fc47426cf70
[0x7fc4744275a0] POSITION: Fragment.java:2288
[0x7fc4744275c0] DEBUG: DBG_END_LOCAL v1
[0x7fc474428a40] OPCODE: RETURN_OBJECT v1
[0x7fc475a00c10] TARGET: SIMPLE 0x7fc474428d60
[0x7fc474427540] POSITION: Fragment.java:2285
[0x7fc474427560] DEBUG: DBG_RESTART_LOCAL v1
[0x7fc474428a60] OPCODE: IGET_OBJECT v1, Landroid/support/v4/app/Fragment;.mChildFragmentManager:Landroid/support/v4/app/FragmentManagerImpl;
[0x7fc474427ae0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fc4744232b0] OPCODE: IF_EQZ v0
[0x7fc474427480] POSITION: Fragment.java:2286
[0x7fc4744232d0] OPCODE: IGET_OBJECT v1, Landroid/support/v4/app/Fragment;.mChildFragmentManager:Landroid/support/v4/app/FragmentManagerImpl;
[0x7fc474427b00] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fc474428800] OPCODE: INVOKE_VIRTUAL v0, v2, Landroid/support/v4/app/FragmentManagerImpl;.findFragmentByWho:(Ljava/lang/String;)Landroid/support/v4/app/Fragment;
[0x7fc474428820] OPCODE: MOVE_RESULT_OBJECT v1
[0x7fc47426cf70] OPCODE: GOTO
[0x7fc47426c350] TARGET: SIMPLE 0x7fc4744232b0
[0x7fc4744274a0] POSITION: Fragment.java:2288
[0x7fc474428700] OPCODE: CONST v1, 0
[0x7fc4718ae1c0] OPCODE: GOTO

Traceback (most recent call last):
  File "/tmp/redex.ArRiDI/redex.py", line 233, in run_redex_binary
    subprocess.check_call(args, env=env, pass_fds=(logger.trace_fp.fileno(),))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.ArRiDI/redex-all', '--apkdir', '/tmp/redex.ArRiDI/tmp2rg5wrze.redex_extracted_apk', '--outdir', '/tmp/redex.ArRiDI/tmpr1n29upq.redex_dexen', '--config', '/Users/lirui/temp/redex/default.config', '/tmp/redex.ArRiDI/tmpr1n29upq.redex_dexen/dex0/classes.dex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.ArRiDI/redex.py", line 934, in <module>
    run_redex(args)
  File "/tmp/redex.ArRiDI/redex.py", line 912, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.ArRiDI/redex.py", line 249, in run_redex_binary
    % script_filenames
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.ArRiDI/redex-gdb-od8gwo43.sh or under lldb by running /tmp/redex.ArRiDI/redex-lldb-jtf5rjcl.sh

**default.config**

```
{
"redex" : {
  "passes" : [
    "ShortenSrcStringsPass"
    ]
}
}
```

**Comment by AndroidInternal** [comment]
trace.txt

Using config /Users/xxx/temp/redex/default.config
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 0.20 seconds
Running redex-all on 1 dex files 
Running redex binary at /tmp/redex.ImKeXy/redex-all
dup_class_whitelist: { 
  Lcom/facebook/soloader/MergedSoMapping;
  Ljunit/framework/TestSuite;
  L$r8$java8methods$utility
}
Loading classes from dex from /tmp/redex.ImKeXy/tmpiuupw2xg.redex_dexen/dex0/classes.dex
        Load classes from dexes completed in 0.2 seconds
        Deobfuscating dex elements completed in 0.0 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 0.0 seconds
        No Optimizations Rules completed in 0.1 seconds
        Initializing reachable classes completed in 0.0 seconds
    Redex_frontend completed in 0.4 seconds
        API Level Checker completed in 0.0 seconds
Evaluating ShortenSrcStringsPass...
        ShortenSrcStringsPass (eval) completed in 0.0 seconds
        Hasher completed in 0.0 seconds
Running ShortenSrcStringsPass...
src strings shortened 513, 11441 bytes saved
            Hasher completed in 0.0 seconds
        ShortenSrcStringsPass (run) completed in 0.0 seconds
Running IRTypeChecker...

**Comment by AndroidInternal** [comment]
Seems above process abort problem can be solved by add **RegAllocPass**

For example , my working config is 
```
{
"redex" : {
  "passes" : [
    "RegAllocPass",
    "ShortenSrcStringsPass"
    ]
}
}
```

But the official document [https://fbredex.com/docs/configuring](https://fbredex.com/docs/configuring)

> A Simple Example


```
{
"redex" : {
  "passes" : [
    "ReBindRefsPass",
    "BridgePass",
    "SynthPass",
    "FinalInlinePass",
    "DelSuperPass",
    "SingleImplPass",
    "MethodInlinePass",
    "StaticReloPass",
    "RemoveEmptyClassesPass",
    "ShortenSrcStringsPass"
  ]
}
}

```

This official example is not working in my enviroment,and there isn't **RegAllocPass**

Hope a detailed explanation for this situation..Thanks

**Comment by Feng23** [comment]
Sorry the documentation is outdated, we'll update it. You can try the [default config](https://github.com/facebook/redex/blob/master/config/default.config) in our code base.

Adding `RegAllocPass` is the right solution. We raise the error intentionally because overriding `this` register may [expose a bug](https://github.com/facebook/redex/blob/master/libredex/RedexOptions.h#L44) in lower Android OS versions

**Comment by justinjhendrick** [comment]
Thanks for the heads-up. RegAlloc is a required pass and we need to update the documentation to reflect that.

**Comment by justinjhendrick** [comment]
Seems resolved
