### ISSUE TITLE
redex-all crashed with exit code -6!  .assertion `scopes.size() > 0' failed

### ISSUE THREAD

**Issue by SireAI** [facebook/redex#437]
run proguard  

void ClassScopes::build_interface_scopes(): assertion `scopes.size() > 0' failed

libc++abi.dylib: terminating with uncaught exception of type RedexException: libredex/VirtualScope.cpp:886: void ClassScopes::build_interface_scopes(): assertion `scopes.size() > 0' failed.

0   redex-all                           0x0000000103050b42 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff6e8feb5d _sigtramp + 29
2   libc++abi.dylib                     0x00007fff6b9a0998 GCC_except_table51 + 216
3   libsystem_c.dylib                   0x00007fff6e7b86a6 abort + 127
4   libc++abi.dylib                     0x00007fff6b993641 __cxa_bad_cast + 0
5   libc++abi.dylib                     0x00007fff6b9937c7 _ZL25default_terminate_handlerv + 243
6   libobjc.A.dylib                     0x00007fff6cf46eeb _ZL15_objc_terminatev + 105
7   libc++abi.dylib                     0x00007fff6b99f19e _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff6b99ef86 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff6b991f99 __cxa_get_globals + 0
10  redex-all                           0x0000000103050ec3 _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 291
11  redex-all                           0x0000000103212a6d _ZN11ClassScopes22build_interface_scopesEv + 989
12  redex-all                           0x00000001032120db _ZN11ClassScopesC2ERKNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEE + 603
13  redex-all                           0x00000001032090b9 _ZN10TypeSystemC2ERKNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEE + 25
14  redex-all                           0x0000000102c9f794 _ZN17FinalInlinePassV28run_passERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFilesR11PassManager + 1604
15  redex-all                           0x0000000103119efe _ZN11PassManager10run_passesERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFiles + 6158
16  redex-all                           0x0000000102ffd05b main + 5531
17  libdyld.dylib                       0x00007fff6e7133d5 start + 1
Traceback (most recent call last):
  File "/tmp/redex.5UV5op/redex.py", line 1020, in <module>
    run_redex(args)
  File "/tmp/redex.5UV5op/redex.py", line 998, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.5UV5op/redex.py", line 323, in run_redex_binary
    % script_filenames
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.5UV5op/redex-gdb-t7cxy2ja.sh or under lldb by running /tmp/redex.5UV5op/redex-lldb-ddg10eqe.sh

**Comment by yuxuanchen1997** [comment]
How are you running redex? Can you share the full command you are using?

**Comment by SireAI** [comment]
redex  -c default.config  input.apk  -o output.apk -P proguard-rules.pro  - m mapping.txt --sign -s debug.keystore -a test -p 123456

**Comment by emma0303** [comment]
Just commented on the other issue where you mentioned this:

The issue that you mentioned above usually happens if the input apk is missing referenced classes .. Is the input.apk ok?

**Comment by SireAI** [comment]
yes,the input.apk works well in the phone.I have tried several times. @emma0303

**Comment by zlrab** [comment]
I encountered the same problem @emma0303 
my proguard:
```
-dontwarn com.facebook.ads.internal.**
-keeppackagenames com.facebook.*
-keep public class com.facebook.ads.** {
   public protected *;
}
```
