### ISSUE TITLE
Trying to encode too many field refs in dex 2: 65540 (limit: 65536)

### ISSUE THREAD

**Issue by sozel** [facebook/redex#441]
Simple redex call fails on (production) signed APK with the error below:

I've tried to change this limit and even completely remove assertions in DexOutput.cpp however after compiling (make); I don't know how my changes seem to be reverted all the time.  

What would be a proper way (instruction steps) to change this limit or assertions?
Thank you

`libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::error_info_injector<RedexException>: libredex/DexOutput.cpp:796: void DexOutput::generate_method_data(): assertion 'dodx->field_to_idx().size() <= kMaxFieldRefs' failed.
Trying to encode too many field refs in dex 2: 65540 (limit: 65536)
0   redex-all                           0x000000010b6313b2 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff6cd89b5d _sigtramp + 29
2   libc++abi.dylib                     0x00007fff69e2c998 GCC_except_table51 + 216
3   libsystem_c.dylib                   0x00007fff6cc436a6 abort + 127
4   libc++abi.dylib                     0x00007fff69e1f641 __cxa_bad_cast + 0
5   libc++abi.dylib                     0x00007fff69e1f7c7 _ZL25default_terminate_handlerv + 243
6   libobjc.A.dylib                     0x00007fff6b3d2eeb _ZL15_objc_terminatev + 105
7   libc++abi.dylib                     0x00007fff69e2b19e _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff69e2af86 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff69e1df99 __cxa_get_globals + 0
10  redex-all                           0x000000010b6319d9 _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 985
11  redex-all                           0x000000010b666ea0 _ZN9DexOutput20generate_method_dataEv + 544
12  redex-all                           0x000000010b66ea9e _ZN9DexOutput7prepareE8SortModeRKNSt3__16vectorIS0_NS1_9allocatorIS0_EEEERK11ConfigFilesRKNS1_12basic_stringIcNS1_11char_traitsIcEENS3_IcEEEE + 510
13  redex-all                           0x000000010b670a6a _Z20write_classes_to_dexRK12RedexOptionsRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEPNS2_6vectorIP8DexClassNS6_ISD_EEEEPNS2_13unordered_mapIP9DexStringN8facebook7LocatorENS2_4hashISJ_EENS2_8equal_toISJ_EENS6_INS2_4pairIKSJ_SL_EEEEEEbmmRK11ConfigFilesP14PositionMapperPNSH_IP9DexMethodyNSM_IS12_EENSO_IS12_EENS6_INSQ_IKS12_yEEEEEEPNSH_IP7DexCodeNSB_I13DebugLineItemNS6_IS1C_EEEENSM_IS1B_EENSO_IS1B_EENS6_INSQ_IKS1B_S1E_EEEEEEP12IODIMetadataSA_PK12PostLowering + 1338
14  redex-all                           0x000000010b5eb7f5 _ZN12_GLOBAL__N_113redex_backendERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11ConfigFilesR11PassManagerRNS0_6vectorI8DexStoreNS4_ISF_EEEERN4Json5ValueE + 3541
15  redex-all                           0x000000010b5e29bc main + 1500
16  libdyld.dylib                       0x00007fff6cb9e3d5 start + 1
Traceback (most recent call last):
  File "/tmp/redex.gMjfZA/redex.py", line 1143, in <module>
    run_redex(args)
  File "/tmp/redex.gMjfZA/redex.py", line 1121, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.gMjfZA/redex.py", line 445, in run_redex_binary
    if run():
  File "/tmp/redex.gMjfZA/redex.py", line 430, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.gMjfZA/redex-gdb-hl4dd435.sh or under lldb by running /tmp/redex.gMjfZA/redex-lldb-2x3xaadd.sh
`

**Comment by emma0303** [comment]
While you would be able to do work around this limit inside redex, we enforce this limit because that is the number of references that can be invoked by the code within a single dex. 

What is your use case? Do you have multidex enabled?

**Comment by justinjhendrick** [comment]
Closing due to inactivity
