### ISSUE TITLE
Redex crashes when using proguard-rules

### ISSUE THREAD

**Issue by pashamcr** [facebook/redex#456]
I'm sorry I'm new to using Redex, don't judge strictly. I can not use proguard-rules, this may be the result of using gcc9, clang for compilation redex, or not all proguardrules are accepted by redex?
For example, I need to leave kotlinx / coroutines / internal / MainDispatcherFactory
an attempt to apply coroutines.pro from https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.3.3/kotlinx-coroutines-core-1.3.3.jar was unsuccessful:
```
ANDROID_SDK=/home/pasha/Android/Sdk ./redex.py -P coroutines.pro -c default.config xxx.apk -o xxx_r.apk --sign -s ~/.android/debug.keystore -a androiddebugkey -p android 
...
terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
  what():  libredex/VirtualScope.cpp:887: void ClassScopes::build_interface_scopes(): assertion `scopes.size() > 0' failed.

/home/pasha/work/redex/redex-all(+0x85a098)[0x55c0c6e5f098]
/home/pasha/work/redex/redex-all(_Z23crash_backtrace_handleri+0x8)[0x55c0c6e5f768]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a100)[0x7fac9e6ff100]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x141)[0x7fac9e6ff081]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7fac9e6ea535]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9a693)[0x7fac9ea80693]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa6036)[0x7fac9ea8c036]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa60a1)[0x7fac9ea8c0a1]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa62f5)[0x7fac9ea8c2f5]
/home/pasha/work/redex/redex-all(+0x37ce13)[0x55c0c6981e13]
/home/pasha/work/redex/redex-all(_ZN11ClassScopes22build_interface_scopesEv+0xc32)[0x55c0c6febcc2]
/home/pasha/work/redex/redex-all(_ZN11ClassScopesC2ERKSt6vectorIP8DexClassSaIS2_EE+0x274)[0x55c0c6ff16f4]
/home/pasha/work/redex/redex-all(_ZN10TypeSystemC2ERKSt6vectorIP8DexClassSaIS2_EE+0x27)[0x55c0c6fe5fe7]
/home/pasha/work/redex/redex-all(_ZN17FinalInlinePassV28run_passERSt6vectorI8DexStoreSaIS1_EER11ConfigFilesR11PassManager+0x76d)[0x55c0c6a99a9d]
/home/pasha/work/redex/redex-all(_ZN11PassManager10run_passesERSt6vectorI8DexStoreSaIS1_EER11ConfigFiles+0xee0)[0x55c0c6f24370]
/home/pasha/work/redex/redex-all(main+0x333)[0x55c0c69a93e3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fac9e6ebbbb]
/home/pasha/work/redex/redex-all(_start+0x2a)[0x55c0c69b580a]

/home/pasha/work/redex/redex-all(+0x85a098)[0x55c0c6e5f098]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_Z23crash_backtrace_handleri+0x8)[0x55c0c6e5f768]
  ??
    ??:0
/lib/x86_64-linux-gnu/libc.so.6(+0x3a100)[0x7fac9e6ff100]
  ??
    ??:0
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x141)[0x7fac9e6ff081]
  ??
    ??:0
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7fac9e6ea535]
  ??
    ??:0
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9a693)[0x7fac9ea80693]
  ??
    ??:0
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa6036)[0x7fac9ea8c036]
  ??
    ??:0
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa60a1)[0x7fac9ea8c0a1]
  ??
    ??:0
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa62f5)[0x7fac9ea8c2f5]
  ??
    ??:0
/home/pasha/work/redex/redex-all(+0x37ce13)[0x55c0c6981e13]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_ZN11ClassScopes22build_interface_scopesEv+0xc32)[0x55c0c6febcc2]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_ZN11ClassScopesC2ERKSt6vectorIP8DexClassSaIS2_EE+0x274)[0x55c0c6ff16f4]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_ZN10TypeSystemC2ERKSt6vectorIP8DexClassSaIS2_EE+0x27)[0x55c0c6fe5fe7]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_ZN17FinalInlinePassV28run_passERSt6vectorI8DexStoreSaIS1_EER11ConfigFilesR11PassManager+0x76d)[0x55c0c6a99a9d]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_ZN11PassManager10run_passesERSt6vectorI8DexStoreSaIS1_EER11ConfigFiles+0xee0)[0x55c0c6f24370]
  ??
    ??:0
/home/pasha/work/redex/redex-all(main+0x333)[0x55c0c69a93e3]
  ??
    ??:0
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fac9e6ebbbb]
  ??
    ??:0
/home/pasha/work/redex/redex-all(_start+0x2a)[0x55c0c69b580a]
  ??
    ??:0

Traceback (most recent call last):
  File "./redex.py", line 1139, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/home/pasha/work/redex/pyredex/utils.py", line 46, in with_temp_cleanup
    fn()
  File "./redex.py", line 1139, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "./redex.py", line 1118, in run_redex
    run_redex_binary(state)
  File "./redex.py", line 439, in run_redex_binary
    if run():
  File "./redex.py", line 424, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex-gdb-fr5j5uvm.sh or under lldb by running /tmp/redex-lldb-rks4nm52.sh
```
...now tried, not accepting any proguard-rules at all

**Comment by justinjhendrick** [comment]
When you add proguard rules, Redex enables some more optimization passes.

It seems that FinalInlinePassV2 (one of the passes enabled by adding proguard rules) is crashing. Try removing FinalInlinePassV2 from your config file and see if that fixes the crash?

**Comment by NTillmann** [comment]
closing due to age
