### ISSUE TITLE
RuntimeError: redex-all crashed with exit code 1! 

### ISSUE THREAD

**Issue by Dwan-xie** [facebook/redex#475]
commond line:
redex -c /Users/x/Documents/redex/config/default.config -o /Users/x/Desktop/final/redex.apk /Users/x/Desktop/pregnancy.apk 

ABORT! Inconsistency found in Dex code for Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V.
 Type error in method Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V at instruction 'INVOKE_VIRTUAL v5, Lcom/babytree/business/base/BizBaseActivity;.H_:()Ljava/lang/String;' @ 0x7ffdf64e6a90 for 
illegal access to protected Lcom/babytree/business/base/BizBaseActivity;.H_:()Ljava/lang/String;
 from Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V
Code:
[0x7ffdf64e6ef0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v9
[0x7ffdf64e6d10] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v10
[0x7ffdf64e6d30] OPCODE: CONST_STRING "onClick"
[0x7ffdf64e9f10] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v6
[0x7ffdf64e6b90] OPCODE: CONST_STRING "(Landroid/view/View;)V"
[0x7ffdf64e9f70] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v7
[0x7ffdf64e6bb0] OPCODE: CONST_CLASS Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;
[0x7ffdf64e9fd0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v4
[0x7ffdf64e56f0] OPCODE: INVOKE_STATIC v6, v7, v4, Lcom/babytree/baf/hotfix/lib/internal/instantrun/PatchProxy;.isSupport:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;)Z
[0x7ffdf64e5710] OPCODE: MOVE_RESULT v1
[0x7ffdf64dd450] OPCODE: CONST v0, 0
[0x7ffdf64dd470] OPCODE: CONST v3, 1
[0x7ffdf64e70d0] OPCODE: IF_EQZ v1
[0x7ffdf64e70f0] OPCODE: NEW_ARRAY v3, [Ljava/lang/Object;
[0x7ffdf64ea100] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
[0x7ffdf64e5f30] OPCODE: APUT_OBJECT v10, v2, v0
[0x7ffdf64e6e90] OPCODE: CONST v5, 0
[0x7ffdf64e6e50] OPCODE: MOVE_OBJECT v3, v9
[0x7ffdf64e5c90] OPCODE: INVOKE_STATIC v2, v3, v4, v5, v6, v7, Lcom/babytree/baf/hotfix/lib/internal/instantrun/PatchProxy;.accessDispatchVoid:([Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Class;ZLjava/lang/String;Ljava/lang/String;)V
[0x7ffdf64e5cb0] OPCODE: RETURN_VOID 
[0x7ffe06ad5c10] TARGET: SIMPLE 0x7ffdf64e70d0
[0x7ffdf64eb440] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:177)
[0x7ffdf64e5bd0] OPCODE: IGET_OBJECT v9, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.a:Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;
[0x7ffdf64ea390] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v5
[0x7ffdf64e5bf0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.a:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Ljava/util/ArrayList;
[0x7ffdf64e5ab0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e5ad0] OPCODE: IF_EQZ v0
[0x7ffdf64e58f0] OPCODE: INVOKE_VIRTUAL v0, Ljava/util/ArrayList;.size:()I
[0x7ffdf64e57b0] OPCODE: MOVE_RESULT v0
[0x7ffdf64e57d0] OPCODE: IF_LEZ v0
[0x7ffdf64eb460] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:178)
[0x7ffdf64e6a90] OPCODE: INVOKE_VIRTUAL v5, Lcom/babytree/business/base/BizBaseActivity;.H_:()Ljava/lang/String;
[0x7ffdf64e69b0] OPCODE: MOVE_RESULT_OBJECT v6
[0x7ffdf64eb480] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:179)
[0x7ffdf64e69d0] OPCODE: INVOKE_STATIC Lcom/babytree/platform/h/b;.a:()Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffdf64dd2c0] OPCODE: MOVE_RESULT_OBJECT v1
[0x7ffdf64dd2e0] OPCODE: CONST v0, 31751
[0x7ffdf64e7740] OPCODE: INVOKE_VIRTUAL v1, v0, Lcom/babytree/business/bridge/tracker/b$a;.c:(I)Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffdf64e7760] OPCODE: MOVE_RESULT_OBJECT v1
[0x7ffe0f512750] OPCODE: CONST_STRING "TL_CJ_DETAIL"
[0x7ffe0eef20f0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffe0eee6970] OPCODE: INVOKE_VIRTUAL v1, v0, Lcom/babytree/business/bridge/tracker/b$a;.i:(Ljava/lang/String;)Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffe0f512450] OPCODE: CONST_STRING "03"
[0x7ffe0eef2700] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffe0f512470] OPCODE: INVOKE_VIRTUAL v1, v0, Lcom/babytree/business/bridge/tracker/b$a;.b:(Ljava/lang/String;)Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffdf64dd240] OPCODE: CONST_STRING "trace_id"
[0x7ffe0eef27a0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v4
[0x7ffdf64eb4a0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:180)
[0x7ffe0eee87b0] OPCODE: INVOKE_VIRTUAL v1, v4, v6, Lcom/babytree/business/bridge/tracker/b$a;.a:(Ljava/lang/String;Ljava/lang/String;)Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffe0f5ad9d0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffe0eee87f0] OPCODE: INVOKE_VIRTUAL v0, Lcom/babytree/business/bridge/tracker/b$a;.b:()Lcom/babytree/business/bridge/tracker/b$a;
[0x7ffe0f5ada70] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffe0eee8810] OPCODE: INVOKE_VIRTUAL v0, Lcom/babytree/business/bridge/tracker/b$a;.e:()V
[0x7ffdf64eb4c0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:181)
[0x7ffe0f5ad7f0] OPCODE: NEW_INSTANCE Lorg/json/JSONArray;
[0x7ffe0eef2490] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v8
[0x7ffe0eee8850] OPCODE: INVOKE_DIRECT v8, Lorg/json/JSONArray;.<init>:()V
[0x7ffe0eee8870] OPCODE: CONST v1, 0
[0x7ffe09676670] TARGET: SIMPLE 0x7ffdf911f500
[0x7ffdf64eb4e0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:182)
[0x7ffe0eee8830] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.a:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Ljava/util/ArrayList;
[0x7ffe0eee88d0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffe0eee88f0] OPCODE: INVOKE_VIRTUAL v0, Ljava/util/ArrayList;.size:()I
[0x7ffe0eee89d0] OPCODE: MOVE_RESULT v0
[0x7ffe0eee89b0] OPCODE: IF_GE v1, v0
[0x7ffdf64eb500] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:183)
[0x7ffe0eee8a10] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.a:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Ljava/util/ArrayList;
[0x7ffe0eee8910] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffe0f5ad8f0] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/util/ArrayList;.get:(I)Ljava/lang/Object;
[0x7ffe0eee8a30] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffe0eee8a50] OPCODE: CHECK_CAST v0, Lcom/babytree/platform/ui/activity/duotu/modle/a;
[0x7ffdf64ea6f0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffe0eee8a70] OPCODE: IGET_OBJECT v0, Lcom/babytree/platform/ui/activity/duotu/modle/a;.b:Ljava/lang/String;
[0x7ffdf64ea750] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffe0f5adbd0] OPCODE: INVOKE_VIRTUAL v8, v0, Lorg/json/JSONArray;.put:(Ljava/lang/Object;)Lorg/json/JSONArray;
[0x7ffe0eee8ba0] OPCODE: ADD_INT_LIT8 v1, v1, 1
[0x7ffdf911f500] OPCODE: GOTO 
[0x7ffdf87f1530] TARGET: SIMPLE 0x7ffe0eee89b0
[0x7ffdf64eb520] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:185)
[0x7ffe0f5adcf0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.d:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffe0f5add10] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e8570] OPCODE: INVOKE_STATIC v0, Lcom/babytree/platform/util/info/d;.V:(Landroid/content/Context;)I
[0x7ffdf64e85d0] OPCODE: MOVE_RESULT v1
[0x7ffdf64e8630] OPCODE: CONST v0, 2
[0x7ffdf64e8690] OPCODE: IF_NE v1, v0
[0x7ffdf64eb540] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:188)
[0x7ffdf64e8750] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.e:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffdf64e87b0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e8810] OPCODE: INVOKE_STATIC v0, Lcom/babytree/platform/util/ak;.q:(Landroid/content/Context;)Z
[0x7ffdf64e8870] OPCODE: MOVE_RESULT v0
[0x7ffdf64e88d0] OPCODE: IF_EQZ v0
[0x7ffdf64eb560] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:189)
[0x7ffe0eee87d0] OPCODE: INVOKE_STATIC Lcom/babytree/apps/pregnancy/l/a;.a:()Lcom/babytree/apps/pregnancy/l/a;
[0x7ffe0eee8c40] OPCODE: MOVE_RESULT_OBJECT v1
[0x7ffdf64e8930] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.f:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffdf64e8990] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e89f0] OPCODE: INVOKE_STATIC v0, Lcom/babytree/platform/util/info/d;.o:(Landroid/content/Context;)Ljava/lang/String;
[0x7ffdf64e8a50] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e8ab0] OPCODE: INVOKE_VIRTUAL v1, v0, Lcom/babytree/apps/pregnancy/l/a;.a:(Ljava/lang/String;)V
[0x7ffdf64e8b10] OPCODE: RETURN_VOID 
[0x7ffe117a3190] TARGET: SIMPLE 0x7ffdf64e8690
[0x7ffdf64eb6a0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:204)
[0x7ffdf64e9b90] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.j:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffdf64e9bf0] OPCODE: MOVE_RESULT_OBJECT v1
[0x7ffdf64e9c50] OPCODE: CONST_STRING "怀孕后才可分享产检经历哟~"
[0x7ffdf64eb3e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffdf64e9cb0] OPCODE: INVOKE_STATIC v1, v0, Lcom/babytree/platform/util/ah;.a:(Landroid/content/Context;Ljava/lang/String;)V
[0x7ffe022d9360] OPCODE: RETURN_VOID 
[0x7ffe0968c7d0] TARGET: SIMPLE 0x7ffdf64e88d0
[0x7ffdf64eb580] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:192)
[0x7ffdf64e8b70] OPCODE: NEW_INSTANCE Landroid/os/Bundle;
[0x7ffdf64eab50] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
[0x7ffdf64e8bd0] OPCODE: INVOKE_DIRECT v2, Landroid/os/Bundle;.<init>:()V
[0x7ffdf64e8c30] OPCODE: CONST_STRING "topic_from"
[0x7ffdf64eabd0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7ffdf64e8c90] OPCODE: CONST v0, 7
[0x7ffdf64eb5a0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:193)
[0x7ffdf64e8cf0] OPCODE: INVOKE_VIRTUAL v2, v1, v0, Landroid/os/Bundle;.putInt:(Ljava/lang/String;I)V
[0x7ffdf64e8d50] OPCODE: CONST_STRING "topic_title"
[0x7ffdf64eac90] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v7
[0x7ffdf64eb5c0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:194)
[0x7ffdf64e8db0] OPCODE: NEW_INSTANCE Ljava/lang/StringBuilder;
[0x7ffdf64eacf0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7ffdf64e8e10] OPCODE: INVOKE_DIRECT v1, Ljava/lang/StringBuilder;.<init>:()V
[0x7ffdf64e8ed0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.g:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffdf64e7230] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e7290] OPCODE: INVOKE_STATIC v0, Lcom/babytree/platform/util/info/d;.q:(Landroid/content/Context;)Ljava/lang/String;
[0x7ffdf64e72f0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e7350] OPCODE: INVOKE_VIRTUAL v1, v0, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
[0x7ffdf64e73b0] OPCODE: CONST_STRING " "
[0x7ffdf64eadb0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffdf64e7410] OPCODE: INVOKE_VIRTUAL v1, v0, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
[0x7ffdf64e74d0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.h:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Lcom/babytree/apps/pregnancy/model/ExamineTipBean;
[0x7ffdf64e8f30] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e8f90] OPCODE: INVOKE_VIRTUAL v0, Lcom/babytree/apps/pregnancy/model/ExamineTipBean;.c:()Ljava/lang/String;
[0x7ffdf64e8ff0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e9050] OPCODE: INVOKE_VIRTUAL v1, v0, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
[0x7ffdf64e90b0] OPCODE: INVOKE_VIRTUAL v1, Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;
[0x7ffdf64e9110] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e9170] OPCODE: INVOKE_VIRTUAL v2, v7, v0, Landroid/os/Bundle;.putString:(Ljava/lang/String;Ljava/lang/String;)V
[0x7ffdf64e91d0] OPCODE: CONST_STRING "topic_post_images"
[0x7ffe0eef9f00] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7ffdf64eb5e0] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:195)
[0x7ffdf64e9230] OPCODE: INVOKE_VIRTUAL v8, Lorg/json/JSONArray;.toString:()Ljava/lang/String;
[0x7ffdf64e9290] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e92f0] OPCODE: INVOKE_VIRTUAL v2, v1, v0, Landroid/os/Bundle;.putString:(Ljava/lang/String;Ljava/lang/String;)V
[0x7ffdf64eb600] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:196)
[0x7ffdf64e93b0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.h:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Lcom/babytree/apps/pregnancy/model/ExamineTipBean;
[0x7ffdf64e9410] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e9470] OPCODE: INVOKE_VIRTUAL v0, Lcom/babytree/apps/pregnancy/model/ExamineTipBean;.a:()Ljava/lang/String;
[0x7ffdf64e94d0] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e9530] OPCODE: INVOKE_STATIC v0, Ljava/lang/Integer;.parseInt:(Ljava/lang/String;)I
[0x7ffdf64e9590] OPCODE: MOVE_RESULT v1
[0x7ffdf64e95f0] OPCODE: SUB_INT v1, v1, v3
[0x7ffdf64e9650] OPCODE: IF_GEZ v1
[0x7ffdf64e96b0] OPCODE: CONST v1, 0
[0x7ffe096be330] TARGET: SIMPLE 0x7ffdf64e9650
[0x7ffdf64e9710] OPCODE: CONST_STRING "topic_post_examine_step"
[0x7ffdf64eb080] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7ffdf64eb620] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:199)
[0x7ffdf64e9770] OPCODE: INVOKE_VIRTUAL v2, v0, v1, Landroid/os/Bundle;.putInt:(Ljava/lang/String;I)V
[0x7ffdf64eb640] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:200)
[0x7ffdf64e9830] OPCODE: INVOKE_VIRTUAL v2, v4, v6, Landroid/os/Bundle;.putString:(Ljava/lang/String;Ljava/lang/String;)V
[0x7ffdf64eb660] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:201)
[0x7ffdf64e98f0] OPCODE: INVOKE_STATIC v5, Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;.i:(Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity;)Landroid/app/Activity;
[0x7ffdf64e9950] OPCODE: MOVE_RESULT_OBJECT v0
[0x7ffdf64e99b0] OPCODE: INVOKE_STATIC v0, v2, Lcom/babytree/apps/pregnancy/arouter/d;.a:(Landroid/content/Context;Landroid/os/Bundle;)V
[0x7ffdf64eb680] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:202)
[0x7ffdf64e9a70] OPCODE: INVOKE_VIRTUAL v5, Lcom/babytree/business/base/BizBaseActivity;.finish:()V
[0x7ffe0391c050] TARGET: SIMPLE 0x7ffdf64e57d0
[0x7ffdf63d78f0] TARGET: SIMPLE 0x7ffdf64e5ad0
[0x7ffe117a6310] POSITION: Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V(ExamineDetailActivity.java:204)
[0x7ffdf64e9d10] OPCODE: RETURN_VOID 

Traceback (most recent call last):
  File "/tmp/redex.ZJ3RiX/redex.py", line 1021, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.ZJ3RiX/pyredex/utils.py", line 56, in with_temp_cleanup
    fn()
  File "/tmp/redex.ZJ3RiX/redex.py", line 1021, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.ZJ3RiX/redex.py", line 1000, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.ZJ3RiX/redex.py", line 481, in run_redex_binary
    if run():
  File "/tmp/redex.ZJ3RiX/redex.py", line 466, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.ZJ3RiX/redex-gdb-kkdb7mvo.sh or under lldb by running /tmp/redex.ZJ3RiX/redex-lldb-0ottvxl2.sh

**Comment by Dwan-xie** [comment]
And i can‘t find /tmp/redex.ZJ3RiX/redex-gdb-kkdb7mvo.sh

**Comment by dcaspi** [comment]
Hey @Dwan-xie 

Can you please run `dexdump -d` on your input dex and attach the output file here?

It doesn't have to be the whole output, as long as it includes:
1. The content of `Lcom/babytree/apps/pregnancy/activity/ExamineDetailActivity$3;.onClick:(Landroid/view/View;)V`
2. The metadata of `Lcom/babytree/business/base/BizBaseActivity;`

**Comment by Dwan-xie** [comment]
@dcaspi 
After run `dexdump -d ` my input apk, The dump file is too big more than 150mb
And i can't ExamineDetailActivity in the file, Just find BizBaseActivity.
Should i dexdump for dex？not the apk？

**Comment by emma0303** [comment]
This sounds like a bug we've fixed yesterday. @Dwan-xie can you pull latest redex version and retry? Thanks

**Comment by Dwan-xie** [comment]
@emma0303 
I pull latest redex version, Commit id  `c3996fd1afb6f316fd63b8cb9662f7bf1fd3170d`
The log like first one.
commnd line:
redex xiewanwan$ redex -c /Users/x/Documents/redex/config/default.config -o /Users/x/Desktop/final/redex.apk /Users/x/Desktop/pregnancy.apk

ABORT! Inconsistency found in Dex code for Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V.
 Type error in method Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V at instruction 'INVOKE_VIRTUAL v1, Lcom/babytree/business/bluetooth/bleprofile/BleProfileService;.c:()Lcom/babytree/business/bluetooth/bleprofile/BleProfileService$a;' @ 0x7fa688fd46f0 for 
illegal access to protected Lcom/babytree/business/bluetooth/bleprofile/BleProfileService;.c:()Lcom/babytree/business/bluetooth/bleprofile/BleProfileService$a;
 from Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V
Code:
[0x7fa688fd30f0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v7
[0x7fa688fd3150] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v8
[0x7fa688fd31b0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v9
[0x7fa688fd31d0] OPCODE: CONST_STRING "onReceive"
[0x7fa688fd4a80] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v5
[0x7fa688fd3690] OPCODE: CONST_STRING "(Landroid/content/Context;Landroid/content/Intent;)V"
[0x7fa688fd4ae0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v6
[0x7fa688fd2220] OPCODE: CONST_CLASS Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;
[0x7fa688fd4b40] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v3
[0x7fa688fd2240] OPCODE: INVOKE_STATIC v5, v6, v3, Lcom/babytree/baf/hotfix/lib/internal/instantrun/PatchProxy;.isSupport:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;)Z
[0x7fa6841036e0] OPCODE: MOVE_RESULT v0
[0x7fa684103740] OPCODE: IF_EQZ v0
[0x7fa688fd2900] OPCODE: CONST v0, 2
[0x7fa688fd2920] OPCODE: NEW_ARRAY v0, [Ljava/lang/Object;
[0x7fa688fd4c50] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7fa688fd40f0] OPCODE: CONST v0, 0
[0x7fa688fd4150] OPCODE: APUT_OBJECT v8, v1, v0
[0x7fa688fd41b0] OPCODE: CONST v0, 1
[0x7fa688fd4210] OPCODE: APUT_OBJECT v9, v1, v0
[0x7fa688fd42d0] OPCODE: CONST v4, 0
[0x7fa688fd43f0] OPCODE: MOVE_OBJECT v2, v7
[0x7fa688fd4450] OPCODE: INVOKE_STATIC v1, v2, v3, v4, v5, v6, Lcom/babytree/baf/hotfix/lib/internal/instantrun/PatchProxy;.accessDispatchVoid:([Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Class;ZLjava/lang/String;Ljava/lang/String;)V
[0x7fa688fd44b0] OPCODE: RETURN_VOID 
[0x7fa69c3afe50] TARGET: SIMPLE 0x7fa684103740
[0x7fa688fd5170] POSITION: Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V(WBYService.java:101)
[0x7fa688fd4510] OPCODE: IGET_OBJECT v7, Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.a:Lcom/babytree/apps/pregnancy/weight/wby/WBYService;
[0x7fa688fd4f70] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7fa688fd4570] OPCODE: INVOKE_STATIC v1, Lcom/babytree/apps/pregnancy/weight/wby/WBYService;.a:(Lcom/babytree/apps/pregnancy/weight/wby/WBYService;)Z
[0x7fa688fd45d0] OPCODE: MOVE_RESULT v0
[0x7fa688fd4630] OPCODE: IF_EQZ v0
[0x7fa688fd5190] POSITION: Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V(WBYService.java:102)
[0x7fa688fd46f0] OPCODE: INVOKE_VIRTUAL v1, Lcom/babytree/business/bluetooth/bleprofile/BleProfileService;.c:()Lcom/babytree/business/bluetooth/bleprofile/BleProfileService$a;
[0x7fa688fd4750] OPCODE: MOVE_RESULT_OBJECT v0
[0x7fa688fd47b0] OPCODE: INVOKE_VIRTUAL v0, Lcom/babytree/business/bluetooth/bleprofile/BleProfileService$a;.d:()V
[0x7fa689900fe0] POSITION: Lcom/babytree/apps/pregnancy/weight/wby/WBYService$1;.onReceive:(Landroid/content/Context;Landroid/content/Intent;)V(WBYService.java:104)
[0x7fa688fd4930] OPCODE: RETURN_VOID 
[0x7fa6952f2f60] TARGET: SIMPLE 0x7fa688fd4630
[0x7fa688fd48d0] OPCODE: INVOKE_VIRTUAL v1, Lcom/babytree/apps/pregnancy/weight/wby/WBYService;.stopSelf:()V
[0x7fa6a2f6b9d0] OPCODE: RETURN_VOID 

Traceback (most recent call last):
  File "/tmp/redex.OBomvp/redex.py", line 1021, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.OBomvp/pyredex/utils.py", line 56, in with_temp_cleanup
    fn()
  File "/tmp/redex.OBomvp/redex.py", line 1021, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.OBomvp/redex.py", line 1000, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.OBomvp/redex.py", line 481, in run_redex_binary
    if run():
  File "/tmp/redex.OBomvp/redex.py", line 466, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.OBomvp/redex-gdb-6ovlgwjh.sh or under lldb by running /tmp/redex.OBomvp/redex-lldb-wkif_tjs.sh

**Comment by Dwan-xie** [comment]
I think i find the reason, The apk have dex protect. 
I use a original apk to run the redex. it's work!
So i close this issue and  thanks for your help!
