### ISSUE TITLE
dump_classes_from_hprof.py get AssertionError

### ISSUE THREAD

**Issue by zhangkevd** [facebook/redex#482]
system:Ubuntu20
python:python 2.7.18rc1
branch:stable

when i use Interdex, 'pass the heap dump to the python script for parsing and printing out the class list '
i run this：
` python ~/git/redex/tools/hprof/dump_classes_from_hprof.py --hprof wk.hprof > list_of_classes.txt`
get this
`
Traceback (most recent call last):
  File "/home/xx/git/redex/tools/hprof/dump_classes_from_hprof.py", line 1432, in <module>
    hp = parse_filename(args.hprof)
  File "/home/xx/git/redex/tools/hprof/dump_classes_from_hprof.py", line 58, in parse_filename
    return parse_hprof_dump(open(filename, "rb"))
  File "/home/xx/git/redex/tools/hprof/dump_classes_from_hprof.py", line 48, in parse_hprof_dump
    hprof_data.resolve()
  File "/home/xx/git/redex/tools/hprof/dump_classes_from_hprof.py", line 965, in resolve
    clazz.resolve(self)
  File "/home/xx/git/redex/tools/hprof/dump_classes_from_hprof.py", line 616, in resolve
    assert name not in self.fields.__dict__
AssertionError
`

i find this same issues #119 ,but it seems to go and didn't fix

**Comment by zhangkevd** [comment]
i fixed!
it only can parse Android 4.x devices hprof file
