### ISSUE TITLE
RuntimeError: redex-all crashed with exit code 1

### ISSUE THREAD

**Issue by hf529270451** [facebook/redex#487]
`WARNING: No inliner config
ABORT! Inconsistency found in Dex code for Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;.
 Type error in method Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase; at instruction 'INVOKE_DIRECT v0, Landroid/support/v4/media/AudioAttributesImplBase;.<init>:()V' @ 0x7f8d56c51570 for 
illegal access to package-private Landroid/support/v4/media/AudioAttributesImplBase;.<init>:()V
 from Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;
Code:
CFG:
 Block B0: entry
   preds:
   [0x7f8d56c6cfd0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v3
   [0x7f8d4131ad60] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:11)
   [0x7f8d56c6cff0] OPCODE: NEW_INSTANCE Landroid/support/v4/media/AudioAttributesImplBase;
   [0x7f8d4131bac0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
   [0x7f8d56c51570] OPCODE: INVOKE_DIRECT v0, Landroid/support/v4/media/AudioAttributesImplBase;.<init>:()V
   [0x7f8d4131ad80] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:12)
   [0x7f8d4131ada0] DEBUG: DBG_START_LOCAL v0 obj:Landroid/support/v4/media/AudioAttributesImplBase;
   [0x7f8d56c67750] OPCODE: IGET v0, Landroid/support/v4/media/AudioAttributesImplBase;.mUsage:I
   [0x7f8d4131a7b0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v1
   [0x7f8d56c67770] OPCODE: CONST v2, 1
   [0x7f8d41137010] OPCODE: INVOKE_VIRTUAL v3, v1, v2, Landroidx/versionedparcelable/VersionedParcel;.readInt:(II)I
   [0x7f8d41137030] OPCODE: MOVE_RESULT v1
   [0x7f8d41138410] OPCODE: IPUT v1, v0, Landroid/support/v4/media/AudioAttributesImplBase;.mUsage:I
   [0x7f8d56f7be60] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:13)
   [0x7f8d41138430] OPCODE: IGET v0, Landroid/support/v4/media/AudioAttributesImplBase;.mContentType:I
   [0x7f8d4131a9f0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v1
   [0x7f8d41139d40] OPCODE: CONST v2, 2
   [0x7f8d56c6cd50] OPCODE: INVOKE_VIRTUAL v3, v1, v2, Landroidx/versionedparcelable/VersionedParcel;.readInt:(II)I
   [0x7f8d41139d60] OPCODE: MOVE_RESULT v1
   [0x7f8d56c6cd70] OPCODE: IPUT v1, v0, Landroid/support/v4/media/AudioAttributesImplBase;.mContentType:I
   [0x7f8d56f7be80] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:14)
   [0x7f8d4131a1b0] OPCODE: IGET v0, Landroid/support/v4/media/AudioAttributesImplBase;.mFlags:I
   [0x7f8d56f64600] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v1
   [0x7f8d56f257d0] OPCODE: CONST v2, 3
   [0x7f8d41319d10] OPCODE: INVOKE_VIRTUAL v3, v1, v2, Landroidx/versionedparcelable/VersionedParcel;.readInt:(II)I
   [0x7f8d41319d30] OPCODE: MOVE_RESULT v1
   [0x7f8d4131b200] OPCODE: IPUT v1, v0, Landroid/support/v4/media/AudioAttributesImplBase;.mFlags:I
   [0x7f8d56f7bea0] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:15)
   [0x7f8d4131b220] OPCODE: IGET v0, Landroid/support/v4/media/AudioAttributesImplBase;.mLegacyStream:I
   [0x7f8d4131e0a0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v1
   [0x7f8d4131b680] OPCODE: CONST v2, 4
   [0x7f8d4131b6a0] OPCODE: INVOKE_VIRTUAL v3, v1, v2, Landroidx/versionedparcelable/VersionedParcel;.readInt:(II)I
   [0x7f8d4131b8c0] OPCODE: MOVE_RESULT v1
   [0x7f8d4131b8e0] OPCODE: IPUT v1, v0, Landroid/support/v4/media/AudioAttributesImplBase;.mLegacyStream:I
   [0x7f8d56f7bec0] POSITION: Landroidx/media/AudioAttributesImplBaseParcelizer;.read:(Landroidx/versionedparcelable/VersionedParcel;)Landroid/support/v4/media/AudioAttributesImplBase;(AudioAttributesImplBaseParcelizer.java:16)
   [0x7f8d4131a670] OPCODE: RETURN_OBJECT v0
   succs:

libc++abi.dylib: terminating with uncaught exception of type boost::wrapexcept<sparta::undefined_operation>: std::exception
libc++abi.dylib: terminating with uncaught exception of type boost::wrapexcept<sparta::undefined_operation>: std::exception
Traceback (most recent call last):
  File "/tmp/redex.uyw6U2/redex.py", line 1033, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.uyw6U2/pyredex/utils.py", line 56, in with_temp_cleanup
    fn()
  File "/tmp/redex.uyw6U2/redex.py", line 1033, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.uyw6U2/redex.py", line 1012, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.uyw6U2/redex.py", line 485, in run_redex_binary
    if run():
  File "/tmp/redex.uyw6U2/redex.py", line 470, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.uyw6U2/redex-gdb-f8tjrcqf.sh or under lldb by running /tmp/redex.uyw6U2/redex-lldb-zz4xhd7i.sh
`

default.config
`{
  "redex" : {
 "passes" : [
      "InterDexPass"
    ],
    "coldstart_classes":"list_of_classes5.txt"
  }
}`

**Comment by agampe** [comment]
Your input is broken, then. `InterDexPass` does not change package names, it has immediate effect on accessibility.

As a workaround, add `MakePublicPass` at the end. It will, with a sledge hammer, make everything public and solve the issue.
