### ISSUE TITLE
make[1]: *** [libredex/RefChecker.lo] Error 1

### ISSUE THREAD

**Issue by DuanTzXavier** [facebook/redex#494]
when i build redex with command:
`autoreconf -ivf && ./configure && make -j4`
get some errors:
```
In file included from libredex/RefChecker.cpp:8:
./libredex/RefChecker.h:49:39: error: expected identifier
  enum class MaybeBoolean : uint8_t { FALSE, TRUE, UNKNOWN };
                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/boolean.h:85:17: note: 
      expanded from macro 'FALSE'
#define FALSE   0
                ^
In file included from libredex/RefChecker.cpp:8:
./libredex/RefChecker.h:49:46: error: expected identifier
  enum class MaybeBoolean : uint8_t { FALSE, TRUE, UNKNOWN };
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/boolean.h:81:17: note: 
      expanded from macro 'TRUE'
#define TRUE    1
                ^
In file included from libredex/RefChecker.cpp:8:
./libredex/RefChecker.h:51:34: error: expected unqualified-id
    return value ? MaybeBoolean::TRUE : MaybeBoolean::FALSE;
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/boolean.h:81:17: note: 
      expanded from macro 'TRUE'
#define TRUE    1
                ^
In file included from libredex/RefChecker.cpp:8:
./libredex/RefChecker.h:51:34: error: expected ':'
    return value ? MaybeBoolean::TRUE : MaybeBoolean::FALSE;
                                 ^
                                 : 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/boolean.h:81:17: note: 
      expanded from macro 'TRUE'
#define TRUE    1
                ^
./libredex/RefChecker.h:51:18: note: to match this '?'
    return value ? MaybeBoolean::TRUE : MaybeBoolean::FALSE;
                 ^
./libredex/RefChecker.h:55:43: error: expected unqualified-id
    return maybe_boolean != MaybeBoolean::FALSE;
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/boolean.h:85:17: note: 
      expanded from macro 'FALSE'
#define FALSE   0
                ^
5 errors generated.
make[1]: *** [libredex/RefChecker.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

here is my env:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@5/5.5.0_3/libexec/gcc/x86_64-apple-darwin17.7.0/5.5.0/lto-wrapper
Target: x86_64-apple-darwin17.7.0
Configured with: ../configure --build=x86_64-apple-darwin17.7.0 --prefix=/usr/local/Cellar/gcc@5/5.5.0_3 --libdir=/usr/local/Cellar/gcc@5/5.5.0_3/lib/gcc/5 --enable-languages=c,c++,fortran,objc,obj-c++ --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --disable-werror --disable-nls --with-pkgversion='Homebrew GCC 5.5.0_3' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --enable-multilib
Thread model: posix
gcc version 5.5.0 (Homebrew GCC 5.5.0_3) 
```

**Comment by justinjhendrick** [comment]
It seems like you have some system headers that define `FALSE` and `TRUE`. And `RefChecker.h` tries to define those as enums, which isn't going to work. We've got a name collision.

@NTillmann, it looks like your recent commit 44cccbb147208da4fac59d4f4f7f0205a7231abc introduced this (D22250215). Could you fix it, please?

**Comment by justinjhendrick** [comment]
@DuanTzXavier, while NTillman is fixing this you could workaround the issue by rebasing to a revision before 44cccbb147208da4fac59d4f4f7f0205a7231abc, such as 195379235256b76d228a67a66e3d01919aa2d86a

**Comment by DuanTzXavier** [comment]
I reset --hard at 195379235256b76d228a67a66e3d01919aa2d86a fix this problem

**Comment by DuanTzXavier** [comment]
I have installed the `redex` command,
but when I run the test ,got error :
```
	mv -f $depbase.Tpo $depbase.Po
In file included from SynthTest.cpp:16:
In file included from ../../libredex/ControlFlow.h:18:
In file included from ../../libredex/IRCode.h:16:
In file included from ../../libredex/DexClass.h:24:
../../libredex/DexDebugInstruction.h:12:10: fatal error: 'DexDefs.h' file not found
#include "DexDefs.h"
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [SynthTest.o] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```
same as https://github.com/facebook/redex/issues/447

And when I run command `redex input.apk -o out.apk` ,some apps could success output a new apk file , But My company's app couldn't . we use the mutidex. The Method size can't be more than 65535, But error :

```
Running IRTypeChecker...
        IRTypeChecker completed in 9.6 seconds
    Running optimization passes completed in 139.4 seconds
        Instruction lowering completed in 3.6 seconds
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::error_info_injector<RedexException>: libredex/DexOutput.cpp:846: void DexOutput::generate_method_data(): assertion `dodx->field_to_idx().size() <= kMaxFieldRefs' failed.
Trying to encode too many field refs in dex 22: 65542 (limit: 65536)
0   redex-all                           0x000000010ac58332 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff73aae5fd _sigtramp + 29
2   ???                                 0x0000000000000400 0x0 + 1024
3   libsystem_c.dylib                   0x00007fff73984808 abort + 120
4   libc++abi.dylib                     0x00007fff70be4458 abort_message + 231
5   libc++abi.dylib                     0x00007fff70bd58a7 _ZL28demangling_terminate_handlerv + 238
6   libobjc.A.dylib                     0x00007fff727105b1 _ZL15_objc_terminatev + 104
7   libc++abi.dylib                     0x00007fff70be3887 _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff70be61a2 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff70be6169 _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
10  redex-all                           0x000000010ac58929 _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 905
11  redex-all                           0x000000010aca7455 _ZN9DexOutput20generate_method_dataEv + 453
12  redex-all                           0x000000010acb04f8 _ZN9DexOutput7prepareE8SortModeRKNSt3__16vectorIS0_NS1_9allocatorIS0_EEEERK11ConfigFilesRKNS1_12basic_stringIcNS1_11char_traitsIcEENS3_IcEEEE + 920
13  redex-all                           0x000000010acb2a77 _Z20write_classes_to_dexRK12RedexOptionsRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEPNS2_6vectorIP8DexClassNS6_ISD_EEEEPNS2_13unordered_mapIP9DexStringN8facebook7LocatorENS2_4hashISJ_EENS2_8equal_toISJ_EENS6_INS2_4pairIKSJ_SL_EEEEEEmmRK11ConfigFilesP14PositionMapperPNSH_IP9DexMethodyNSM_IS12_EENSO_IS12_EENS6_INSQ_IKS12_yEEEEEEPNSH_IP7DexCodeNSB_I13DebugLineItemNS6_IS1C_EEEENSM_IS1B_EENSO_IS1B_EENS6_INSQ_IKS1B_S1E_EEEEEEP12IODIMetadataSA_PK12PostLoweringi + 2359
14  redex-all                           0x000000010ac02af0 _ZN12_GLOBAL__N_113redex_backendERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11ConfigFilesR11PassManagerRNS0_6vectorI8DexStoreNS4_ISF_EEEERN4Json5ValueE + 2144
15  redex-all                           0x000000010abfb8c3 main + 6275
16  libdyld.dylib                       0x00007fff738b5cc9 start + 1
Traceback (most recent call last):
  File "/tmp/redex.ABGlxd/redex.py", line 1049, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.ABGlxd/pyredex/utils.py", line 56, in with_temp_cleanup
    fn()
  File "/tmp/redex.ABGlxd/redex.py", line 1049, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.ABGlxd/redex.py", line 1028, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.ABGlxd/redex.py", line 494, in run_redex_binary
    if run():
  File "/tmp/redex.ABGlxd/redex.py", line 479, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.ABGlxd/redex-gdb-d1esx3kh.sh or under lldb by running /tmp/redex.ABGlxd/redex-lldb-5ldyoy95.sh
```
same as https://github.com/facebook/redex/issues/441

**Comment by NTillmann** [comment]
@DuanTzXavier: The commit https://github.com/facebook/redex/commit/401d9cc49eff99f2dbdb2444ec0fe1f412aa8468 should have fixed your original issue. That's why I am closing this issue. Feel free to re-open if the original issue persists.

For the other issue you mention, can you please open a separate issue?

Thanks!
