### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Codeskiin** [facebook/redex#533]
I am using windows 10 and I have extracted redex-all.exe binary through ming64 shell. when I am trying to run python redex.py 1.apk -o 2.apk --ignore-zipalign , I am getting error like this :  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified.
Until  Redex_backend completed in 1.7 seconds and Freeing global memory completed in 0.1 seconds processes, everything is working fine. Issue starts with,

`Traceback (most recent call last):
  File "redex.py", line 1071, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "C:\Users\khush Manvar\gitt\redex\pyredex\utils.py", line 56, in with_temp_cleanup
    fn()
  File "redex.py", line 1071, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "redex.py", line 1056, in run_redex
    finalize_redex(state)
  File "redex.py", line 1036, in finalize_redex
    copy_all_file_to_out_dir(
  File "redex.py", line 593, in copy_all_file_to_out_dir
    copy_file_to_out_dir(
  File "redex.py", line 581, in copy_file_to_out_dir
    subprocess.check_call(["cp", tmp_path, output_path])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

I have attached screenshots of my logs.
![1](https://user-images.githubusercontent.com/54769548/90977963-868cfb80-e567-11ea-95ea-ea588f0b2056.png)
![2](https://user-images.githubusercontent.com/54769548/90977965-8a208280-e567-11ea-9c9e-704d14cedf90.png)
![3](https://user-images.githubusercontent.com/54769548/90977967-8bea4600-e567-11ea-9758-e30fd48652f0.png)
![4](https://user-images.githubusercontent.com/54769548/90977968-8d1b7300-e567-11ea-9477-23fbfd52a03c.png)

Thank you!

**Comment by agampe** [comment]
Try after ddfd9789. You only need to update/copy the `redex.py` script, the binary should not need a recompile.

**Comment by Codeskiin** [comment]
@agampe , It's now working , thank you for your reply. So now I am closing this issue.
