### ISSUE TITLE
redex-all crashed with exit code 127

### ISSUE THREAD

**Issue by daichen** [facebook/redex#580]
I have already use setup_oss_toolchain.sh set the toolchian, and the boost library are install in /usr/local/lib

But it will always say can't find libboost

dc@dc-OptiPlex-7060:~/work/redex$ python3 redex.py ~/mms-12.2.3.1-universal.apk -o aa.apk
WARNING:root:No android_sdk_api_XX_file parameters found!
/home/dc/work/redex/redex-all: error while loading shared libraries: libboost_iostreams.so.1.71.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "redex.py", line 1137, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/home/dc/work/redex/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "redex.py", line 1137, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "redex.py", line 1116, in run_redex
    run_redex_binary(state, term_handler, exception_formatter)
  File "redex.py", line 522, in run_redex_binary
    if run():
  File "redex.py", line 508, in run
    raise RuntimeError(msg)
RuntimeError: redex-all crashed with exit code 127! You can re-run it under gdb by running /tmp/redex-gdb-4wiiqka0.sh or under lldb by running /tmp/redex-lldb-ebfzs3fu.sh

![image](https://user-images.githubusercontent.com/1658580/102780217-82b39d80-43d0-11eb-8dc0-87ec1260535e.png)

![image](https://user-images.githubusercontent.com/1658580/102780259-94954080-43d0-11eb-8418-da46beb11c1e.png)

**Comment by daichen** [comment]
ubuntu 18.04

**Comment by sisco0** [comment]
Have a good day @daichen, it seems that the app is complaining when running the _redex_ binary and the _Boost_ shared library files are not found.

Could you kindly run `sudo apt install libboost-iostreams1.71.0` to try to get the solution? If it does not work, please use `sudo apt install libboost-all-dev` to install all libraries.

**Comment by agampe** [comment]
> Could you kindly run `sudo apt install libboost-iostreams1.71.0` to try to get the solution? If it does not work, please use `sudo apt install libboost-all-dev` to install all libraries.

18.04 (bionic) only has Boost 1.65, while we officially require 1.71. I don't remember what required the move. I believe Redex still works with 1.69, at least. But anything other than 1.71 is officially unsupported (we're happy to take patches for forward compatibility, though).

The `setup_oss_toolchain.sh` script should detect 18.04 and install Boost from sources. That seems to have been the case, as some files exist in `/usr/local/lib`. What I don't understand is why they are not found. @daichen, did you change `LD_LIBRARY_PATH` or other related environment variables in your terminal? I wonder whether this is a 32-64-bit mismatch? Or `ld.conf` being misconfigured?

An alternative approach is compiling a static binary, and sidestep library issues.
