### ISSUE TITLE
Crashes on obfuscated apk

### ISSUE THREAD

**Issue by FaolanX** [facebook/redex#626]
```
Running IRTypeChecker...
Inconsistency found in Dex code for La9$c;.c:(Landroid/view/View;)V
 Type error in method La9$c;.c:(Landroid/view/View;)V at instruction 'INVOKE_VIRTUAL v5, v0, v1, Landroid/view/View;.setLayerType:(ILandroid/graphics/Paint;)V' @ 0x1b16931ff60 for register v1: expected type REF, but found INT instead
Code:
[0x1b169320800] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v4
[0x1b1693205c0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v5
[0x1b169320500] OPCODE: CONST v0, 3
[0x1b16931fe10] OPCODE: CONST v0, 0
[0x1b16931fe70] OPCODE: CONST v3, 1
[0x1b1693207d0] OPCODE: IPUT_BOOLEAN v0, v4, La9$c;.b:Z
[0x1b1693202f0] OPCODE: CONST v3, 2
[0x1b1693204a0] OPCODE: IGET_OBJECT v4, La9$c;.a:La9;
[0x1b16931fd80] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x1b169320410] OPCODE: IGET v0, La9;.d:I
[0x1b16931fdb0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v0
[0x1b1693201a0] OPCODE: CONST v1, 0
[0x1b169320440] OPCODE: SHL_INT v3, v3, v1
[0x1b1693201d0] OPCODE: CONST v2, -1
[0x1b169320080] OPCODE: IF_LE v0, v2
[0x1b169320020] OPCODE: CONST v3, 2
[0x1b169320350] OPCODE: CONST v0, 2
[0x1b169320470] OPCODE: CONST v3, 6
[0x1b16931ff60] OPCODE: INVOKE_VIRTUAL v5, v0, v1, Landroid/view/View;.setLayerType:(ILandroid/graphics/Paint;)V
[0x1b170b99760] TARGET: SIMPLE 0x1b169320080
[0x1b169320860] OPCODE: IGET_OBJECT v4, La9$c;.a:La9;
[0x1b16931ff90] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x1b1693204d0] OPCODE: CONST v3, 3
[0x1b16931fd20] OPCODE: IGET_OBJECT v0, La9;.b:Ljava/lang/Runnable;
[0x1b16931fde0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
[0x1b1693206e0] OPCODE: IF_EQZ v2
[0x1b169320530] OPCODE: IPUT_OBJECT v1, v0, La9;.b:Ljava/lang/Runnable;
[0x1b1693205f0] OPCODE: CONST v3, 2
[0x1b169320770] OPCODE: INVOKE_INTERFACE v2, Ljava/lang/Runnable;.run:()V
[0x1b170b99250] TARGET: SIMPLE 0x1b1693206e0
[0x1b1693200e0] OPCODE: CONST v3, 0
[0x1b169320230] OPCODE: CONST v0, 2113929216
[0x1b169320740] OPCODE: INVOKE_VIRTUAL v5, v0, Landroid/view/View;.getTag:(I)Ljava/lang/Object;
[0x1b1693203e0] OPCODE: MOVE_RESULT_OBJECT v0
[0x1b169320650] OPCODE: INSTANCE_OF v0, Lb9;
[0x1b16931ff00] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO v2
[0x1b169320110] OPCODE: CONST v3, 7
[0x1b1693207a0] OPCODE: IF_EQZ v2
[0x1b16931fcf0] OPCODE: MOVE_OBJECT v1, v0
[0x1b169320560] OPCODE: MOVE_OBJECT v1, v0
[0x1b169320620] OPCODE: CONST v3, 3
[0x1b169320680] OPCODE: CHECK_CAST v1, Lb9;
[0x1b16931ff30] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x1b170b998e0] TARGET: SIMPLE 0x1b1693207a0
[0x1b1693206b0] OPCODE: CONST v3, 4
[0x1b16931ffc0] OPCODE: IF_EQZ v1
[0x1b16931fd50] OPCODE: CONST v3, 7
[0x1b169320140] OPCODE: INVOKE_INTERFACE v1, v5, Lb9;.c:(Landroid/view/View;)V
[0x1b170b99490] TARGET: SIMPLE 0x1b16931ffc0
[0x1b169320170] OPCODE: RETURN_VOID

(90 more issues!)
Traceback (most recent call last):
  File "redex.py", line 1166, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "C:\Users\zaqas\Downloads\redex-master\pyredex\utils.py", line 58, in with_temp_cleanup
    fn()
  File "redex.py", line 1166, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "redex.py", line 1145, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "redex.py", line 327, in run_redex_binary
    run()
  File "redex.py", line 309, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 1!
```

**Comment by thezhangwei** [comment]
I think it complaints about `[0x1b169320440] OPCODE: SHL_INT v3, v3, v1` turning `v1` into an `INT`.

**Comment by agampe** [comment]
@FaolanX Can you be a bit more precise? Is that at the start? Is that input code that's technically broken, or something modified by Redex?
