### ISSUE TITLE
Unable to instantiate application after redex step

### ISSUE THREAD

**Issue by polycoder** [facebook/redex#67]
When trying redex with a debug build (NOT pro-guarded at all) the app will immediately crash when launching the redex version of the apk. The exception is as follows:

```
04-14 13:19:30.491 31052 31052 E AndroidRuntime: FATAL EXCEPTION: main
04-14 13:19:30.491 31052 31052 E AndroidRuntime: Process: com.mycompany.music.debug, PID: 31052
04-14 13:19:30.491 31052 31052 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.mycompany.music.MycompanyApplicationDebug: java.lang.ClassNotFoundException: Didn't find class "com.mycompany.music.MycompanyApplicationDebug" on path: DexPathList[[zip file "/data/app/com.mycompany.music.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.music.debug-1/lib/arm, /data/app/com.mycompany.music.debug-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6294)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:222)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mycompany.music.MycompanyApplicationDebug" on path: DexPathList[[zip file "/data/app/com.mycompany.music.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.music.debug-1/lib/arm, /data/app/com.mycompany.music.debug-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	... 9 more
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.mycompany.music.MycompanyApplicationDebug
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 		... 12 more
04-14 13:19:30.491 31052 31052 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot 
```

If I look at the contents of the original debug apk and grep for dex files I see:

```
➜  redex git:(master) ✗ unzip -l ../app/build/outputs/apk/app-armV7-debug-unaligned.apk | grep dex
  7959096  04-14-16 12:23   classes.dex
   805196  04-14-16 12:23   classes2.dex
    89656  04-14-16 12:23   classes3.dex
    ...
   153760  04-14-16 12:22   classes89.dex
   319652  04-14-16 12:23   classes90.dex
      768  04-14-16 12:23   classes91.dex
```

If I look at the contents of the redexed apk and grep for dex files I see:

```
➜  redex git:(master) ✗ unzip -l redex-out.apk | grep dex
Archive:  redex-out.apk
  6688416  04-14-16 13:10   classes.dex
```

It appears the multidex dex files are missing or perhaps just merged? Either way, the app is unable to start...

**Comment by polycoder** [comment]
Similar issue to #27

**Comment by shmuelr** [comment]
So this is the MultiDex issue?

**Comment by Gavin1989** [comment]
https://github.com/facebook/redex/blob/master/docs/Config.md may be have help

**Comment by bertmaher** [comment]
Thanks for reporting the issue! Redex is supposed to work with multidex (FB is multidex), so there must be a bug.

Hard to know what's going on, but you could help me debug it by creating a config file (see the doc linked by @Gavin1989 ), and progressively eliminating passes until the application installs.  That'll at least tell me which pass is misbehaving.

**Comment by bertmaher** [comment]
I just fixed a really silly bug with multidex, so multidex apps should work now.  Sorry for the hassle.

**Comment by polycoder** [comment]
awesome @bertmaher, I will try it out again!
