### ISSUE TITLE
RuntimeError: redex-all crashed with exit code -11!

### ISSUE THREAD

**Issue by JusticeOfHeaven** [facebook/redex#696]
redex --sign -s debug.jks -a android -p android -c redex.config --android-sdk-path $ANDROID_HOME -P app/proguard-rules.pro -o $app/build/outputs/redex/redex.apk $file

0   redex-all                           0x000000010a90ea21 _Z23crash_backtrace_handleri + 81
1   libsystem_platform.dylib            0x00007fff2064dd7d _sigtramp + 29
2   ???                                 0x00007fb67260b790 0x0 + 140421579716496
3   redex-all                           0x000000010a4f18e1 _ZN8interdex8InterDex16emit_primary_dexERKNSt3__16vectorIP8DexClassNS1_9allocatorIS4_EEEERKNS2_IP7DexTypeNS5_ISB_EEEERKNS1_13unordered_setIS4_NS1_4hashIS4_EENS1_8equal_toIS4_EES6_EE + 801
4   redex-all                           0x000000010a4f6734 _ZN8interdex8InterDex3runEv + 3236
5   redex-all                           0x000000010a4fe58e _ZN8interdex12InterDexPass8run_passERKNSt3__16vectorIP8DexClassNS1_9allocatorIS4_EEEERK10XStoreRefsRKN12init_classes26InitClassesWithSideEffectsERNS2_I8DexStoreNS5_ISH_EEEERNS2_IS7_NS5_IS7_EEEERNS2_INS1_10unique_ptrINS_18InterDexPassPluginENS1_14default_deleteISP_EEEENS5_ISS_EEEER11ConfigFilesR11PassManagerRKNS_15ReserveRefsInfoE + 1038
6   redex-all                           0x000000010a4ff8e8 _ZN8interdex12InterDexPass8run_passERNSt3__16vectorI8DexStoreNS1_9allocatorIS3_EEEER11ConfigFilesR11PassManager + 584
7   redex-all                           0x000000010aa8cee3 _ZN11PassManager10run_passesERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFiles + 15923
8   redex-all                           0x000000010a884281 main + 2465
9   libdyld.dylib                       0x00007fff20623f5d start + 1
10  ???                                 0x0000000000000021 0x0 + 33
Traceback (most recent call last):
  File "/tmp/redex.1PvRvO/redex.py", line 1259, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.1PvRvO/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/tmp/redex.1PvRvO/redex.py", line 1259, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.1PvRvO/redex.py", line 1238, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/tmp/redex.1PvRvO/redex.py", line 374, in run_redex_binary
    run()
  File "/tmp/redex.1PvRvO/redex.py", line 367, in run
    raise RuntimeError(msg)
RuntimeError: redex-all crashed with exit code -11! You can re-run it under gdb by running /tmp/redex.1PvRvO/redex-gdb-jlvtmrbg.sh or under lldb by running /tmp/redex.1PvRvO/redex-lldb-20s5d11a.sh

**Comment by NTillmann** [comment]
More information is needed to diagnose this. Line numbers in the stack trace would help, and more details instructions on how to reproduce.
