### ISSUE TITLE
RedexRunException: redex-all crashed with exit code -6! You can re-run it under gdb by running 

### ISSUE THREAD

**Issue by Novelot** [facebook/redex#717]
执行如下命令后提示错误:
```
python3 redex.py ~/Desktop/redex/old.apk -o ~/Desktop/redex/new.apk -J ir_type_checker.run_on_input=false  
```

错误提示:
```
0   redex-all                           0x00000001011ae141 _Z23debug_backtrace_handleri + 81
1   libsystem_platform.dylib            0x00007ff808fdbdfd _sigtramp + 29
2   ???                                 0x000000000000d33d 0x0 + 54077
3   libsystem_c.dylib                   0x00007ff808f11d24 abort + 123
4   libc++abi.dylib                     0x00007ff808f82082 abort_message + 241
5   libc++abi.dylib                     0x00007ff808f731a5 _ZL28demangling_terminate_handlerv + 242
6   libobjc.A.dylib                     0x00007ff808e6fe19 _ZL15_objc_terminatev + 104
7   libc++abi.dylib                     0x00007ff808f814a7 _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007ff808f83d05 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007ff808f83ccc _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
10  redex-all                           0x00000001011ae678 _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 744
11  redex-all                           0x0000000101355535 _ZN12_GLOBAL__N_113CheckerConfig12run_verifierERKNSt3__16vectorIP8DexClassNS1_9allocatorIS4_EEEEb + 4565
12  redex-all                           0x000000010134f1d0 _ZN11PassManager10run_passesERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFiles + 16160
13  redex-all                           0x0000000101121b6b main + 1899
14  dyld                                0x000000010c65152e start + 462
Traceback (most recent call last):
  File "~/redex/redex.py", line 1289, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "~/redex/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "~/redex/redex.py", line 1289, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "~/redex/redex.py", line 1268, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "~/redex/redex.py", line 398, in run_redex_binary
    run()
  File "~/redex/redex.py", line 391, in run
    raise RedexRunException(msg, returncode, abort_error, symbolized)
__main__.RedexRunException: redex-all crashed with exit code -6! You can re-run it under gdb by running /var/folders/yy/pzd6x2bs6x73bz04nr8xsn0r0000gn/T/redex-gdb-lua61yaz.sh or under lldb by running /var/folders/yy/pzd6x2bs6x73bz04nr8xsn0r0000gn/T/redex-lldb-0dz7oldd.sh
```

**Comment by galihuotui** [comment]
is this problem solved?

**Comment by davezhou2022** [comment]
I've met the same error. do you resolve it?
