### ISSUE TITLE
how to config redex pass 

### ISSUE THREAD

**Issue by 123zhangmiao** [facebook/redex#727]
How to configure a set of universal pass, referring to the use of this set of pass Settings for different apps can have a good optimization effect

**Comment by 123zhangmiao** [comment]
How to configure a set of universal pass refers to the good optimization effect that can be achieved by using this set of pass Settings for different apps, how to know and avoid the potential risks of each pass, and what are the standards for measuring the optimization effect.

**Comment by thezhangwei** [comment]
Hi, the [aggressive.config](https://github.com/facebook/redex/blob/main/config/aggressive.config) is a good starting point. Please let us know if run into issues with that. We do plan to keep the config information more updated in the future.

**Comment by 123zhangmiao** [comment]
Evaluating ResultPropagationPass...
        ResultPropagationPass (eval) completed in 0.0 seconds
Evaluating BridgeSynthInlinePass...
        BridgeSynthInlinePass (eval) completed in 0.0 seconds
Evaluating FinalInlinePassV2...
        FinalInlinePassV2 (eval) completed in 0.0 seconds
Evaluating DelSuperPass...
        DelSuperPass (eval) completed in 0.0 seconds

If I get a log like the one above, I can delete the pass ResultPropagationPass、FinalInlinePassV2、DelSuperPass、BridgeSynthInlinePass, right?

The other question is, what is the basis for removing or adding pass. 
Looking forward to reply!

**Comment by thezhangwei** [comment]
> If I get a log like the one above, I can delete the pass RemoveEmptyClassesPass right?

It seems like it doesn't do much but it could be input dependent. It might find empty classes to remove for some other inputs. You don't necessarily have to prune passes even if they don't seem to do much for now. It's not taking much time to run anyways, it seems.

You can always add other passes to the `passes` list and see what they do. Usually the default config for that pass would work. You can also run one pass multiple times by replicating it in the `passes` list. Hopefully that helps.

**Comment by 123zhangmiao** [comment]
How do I see what a pass does? What are the criteria for whether a pass is valuable?

**Comment by 123zhangmiao** [comment]
As you said, default.config is a way to make sure that every pass works, aggressive.config is a good place to start. What should I choose if I want to have a pass configuration that is universal and works for different inputs? Please answer my confusion. My requirement is to have a common pass configuration to optimize different APKs. I would also like to know the criteria to measure the effectiveness of each pass optimization, as well as the overall config optimization. After all, the optimization of redex tool is determined by configuring pass. Do you agree with me?

**Comment by 123zhangmiao** [comment]
When used aggressive.config, the following error occurs

File "/tmp/redex.TGskxX/redex.py", line 956, in prepare_redex
    config_dict = json.loads(remove_comments(lines))
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 21 column 7 (char 257)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.TGskxX/redex.py", line 1262, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.TGskxX/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/tmp/redex.TGskxX/redex.py", line 1262, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.TGskxX/redex.py", line 1238, in run_redex
    state = prepare_redex(args)
  File "/tmp/redex.TGskxX/redex.py", line 958, in prepare_redex
    raise ValueError(
ValueError: Invalid JSON in ReDex config file: redex-test/interdex.config

**Comment by 123zhangmiao** [comment]
@thezhangwei   hi~Can you answer my questions above?

**Comment by thezhangwei** [comment]
The json error was fixed in https://github.com/facebook/redex/commit/52e44ae995172ccaa2d102cf984cb4248cb3b9d9.

**Comment by NTillmann** [comment]
> What are the criteria for whether a pass is valuable?

In general, most passes work towards reducing the final size. Some passes don't do all of the cleanup work and would require a RemoveUnreachablePass to run after to actually remove newly unreachable classes/methods/fields.

Some passes are geared towards improving performance while regressing size, e.g. PerfMethodInlinePass.

Some passes are necessary to produce valid dexes, e.g. InterDexPass and RegAllocPass.
