### ISSUE TITLE
Windows: comment error in default.config

### ISSUE THREAD

**Issue by pashamcr** [facebook/redex#738]
'#' - works
'//' - does not work

```
Traceback (most recent call last):
  File "d:\WORK\redex\redex.py", line 1010, in prepare_redex
    config_dict = json.loads(remove_comments(lines))
  File "C:\Users\pasha\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\pasha\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\pasha\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 45 (char 220)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\WORK\redex\redex.py", line 1321, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "d:\WORK\redex\pyredex\utils.py", line 62, in with_temp_cleanup
    fn()
  File "d:\WORK\redex\redex.py", line 1321, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "d:\WORK\redex\redex.py", line 1297, in run_redex
    state = prepare_redex(args)
  File "d:\WORK\redex\redex.py", line 1012, in prepare_redex
    raise ValueError(
ValueError: Invalid JSON in ReDex config file: d:\WORK\redex\config\default.config
```

**Comment by thezhangwei** [comment]
Fixed by https://github.com/facebook/redex/commit/d935ad0f4af364b4ccee6ace56cccf89a7c4f594
