### ISSUE TITLE
error while loading shared libraries: libfolly.so.57

### ISSUE THREAD

**Issue by waynell** [facebook/redex#75]
command: 
`redex app.apk -o app_redex.apk`

error messages:
 ```
/usr/local/bin/redex-all: error while loading shared libraries: libfolly.so.57: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/local/bin/redex", line 785, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 741, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 116, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /tmp/tmpfqzk7vm_.redex_extracted_apk --outdir /tmp/tmpfedahntj.redex_dexen /tmp/tmpfedahntj.redex_dexen/dex0/classes.dex' returned non-zero exit status 127
```

OS: **Ubuntu 14.04 LTS**

**Comment by thetanuj** [comment]
I am having the same error.
OS: Ubuntu 14.10 LTS

**Comment by thetanuj** [comment]
please add the following in your .bashrc. Make sure you have sourced your rc files again (or logout and login)

```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PATH=/home/tan/Android/Sdk/build-tools/23.0.2:$PATH

```
