### ISSUE TITLE
 NameError: name 'reduce' is not defined (dump_classes_from_hprof.py)

### ISSUE THREAD

**Issue by byronwind** [facebook/redex#76]
python3 redex/tools/hprof/dump_classes_from_hprof.py --hprof my.hprof > list_of_classes.txt

Traceback (most recent call last):
  File "./tools/hprof/dump_classes_from_hprof.py", line 1262, in <module>
    hp = parse_filename(args.hprof)
  File "./tools/hprof/dump_classes_from_hprof.py", line 54, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "./tools/hprof/dump_classes_from_hprof.py", line 31, in parse_hprof_dump
    tag = reduce(operator.concat, iter_until_null, '')
NameError: name 'reduce' is not defined

**Comment by onomatopoeia** [comment]
Use python 2.7 to run the dump script. We're working on fixing this, but it's extracted from a code base that is all python 2.*
