### ISSUE TITLE
redex-all crashed with exit code 1

### ISSUE THREAD

**Issue by guobao90** [facebook/redex#765]
python3 redex.py -c default.config -o /Users/leo.zhang/Desktop/json/release/mcc_origin_out.apk /Users/leo.zhang/Desktop/json/release/mcc_origin.apk

**error message:**
[ERROR   ] Expecting value: line 9 column 45 (char 212)
[WARNING ] Could not find an SDK jar: Could not find SDK path, searched Env, Buck
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
error: No ProGuard keep rules provided. Redex optimizations will not preserve semantics without accurate keep rules.
Traceback (most recent call last):
  File "/Users/leo.zhang/AndroidProject/redex/redex.py", line 1345, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/Users/leo.zhang/AndroidProject/redex/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/Users/leo.zhang/AndroidProject/redex/redex.py", line 1345, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/Users/leo.zhang/AndroidProject/redex/redex.py", line 1324, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/Users/leo.zhang/AndroidProject/redex/redex.py", line 397, in run_redex_binary
    run()
  File "/Users/leo.zhang/AndroidProject/redex/redex.py", line 390, in run
    raise RedexRunException(msg, returncode, abort_error, symbolized)
__main__.RedexRunException: redex-all crashed with exit code 1! You can re-run it under gdb by running /var/folders/hx/78lkd49x14zcvmytj_6z8pkc3mx2f9/T/redex-gdb-crkljhsp.sh or under lldb by running /var/folders/hx/78lkd49x14zcvmytj_6z8pkc3mx2f9/T/redex-lldb-3eh35mq9.sh

please help check this

**Comment by NTillmann** [comment]
Somehow you seem to have a JSON parser that doesn't like the '#' comments in the default.config file. Can you edit it, and remove '#' and everything that follows in each line, and see if that fixes things for you?

**Comment by leo9006** [comment]
> Somehow you seem to have a JSON parser that doesn't like the '#' comments in the default.config file. Can you edit it, and remove '#' and everything that follows in each line, and see if that fixes things for you?

I remove the '#' in the comment, it doesn't work, it does not have this error 

`[ERROR ] Expecting value: line 9 column 45 (char 212)`

others still have the same error message

**Comment by NTillmann** [comment]
> I remove the '#' in the comment, it doesn't work [...]

Please try removing the entire comment, not just the leading '#'. The content needs to become legal JSON.

**Comment by guobao90** [comment]
Yes, I remove all the comment

this is the detail config, but still have the same error message

`{
"redex" : {
  "passes" : [
    "ReBindRefsPass",
    "BridgeSynthInlinePass",
    "FinalInlinePassV2",
    "DelSuperPass",
    "SingleImplPass",
    "MethodInlinePass",
    "StaticReloPassV2",
    "RemoveEmptyClassesPass",
    "ShortenSrcStringsPass",
    "RegAllocPass"
  ]
}
}`

**Comment by guobao90** [comment]
> > I remove the '#' in the comment, it doesn't work [...]
> 
> Please try removing the entire comment, not just the leading '#'. The content needs to become legal JSON.

Yes, I remove all the comment

this is the detail config, but still have the same error message

{ "redex" : { "passes" : [ "ReBindRefsPass", "BridgeSynthInlinePass", "FinalInlinePassV2", "DelSuperPass", "SingleImplPass", "MethodInlinePass", "StaticReloPassV2", "RemoveEmptyClassesPass", "ShortenSrcStringsPass", "RegAllocPass" ] } }

is there any update?

**Comment by Huxn** [comment]
> > > I remove the '#' in the comment, it doesn't work [...]
> > 
> > 
> > Please try removing the entire comment, not just the leading '#'. The content needs to become legal JSON.
> 
> Yes, I remove all the comment
> 
> this is the detail config, but still have the same error message
> 
> { "redex" : { "passes" : [ "ReBindRefsPass", "BridgeSynthInlinePass", "FinalInlinePassV2", "DelSuperPass", "SingleImplPass", "MethodInlinePass", "StaticReloPassV2", "RemoveEmptyClassesPass", "ShortenSrcStringsPass", "RegAllocPass" ] } }
> 
> is there any update?

I have the same problem, based on the master code

**Comment by fdh19979** [comment]
I have the same problem

/Users/user/redex/redex.py:24: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  from pipes import quote
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
error: No ProGuard keep rules provided. Redex optimizations will not preserve semantics without accurate keep rules.
Traceback (most recent call last):
  File "/Users/fudonghui/redex/redex.py", line 1345, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/Users/fudonghui/redex/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/Users/fudonghui/redex/redex.py", line 1345, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
                              ^^^^^^^^^^^^^^^
  File "/Users/fudonghui/redex/redex.py", line 1324, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/Users/fudonghui/redex/redex.py", line 397, in run_redex_binary
    run()
  File "/Users/fudonghui/redex/redex.py", line 390, in run
    raise RedexRunException(msg, returncode, abort_error, symbolized)
RedexRunException: redex-all crashed with exit code 1! You can re-run it under gdb by running /var/folders/58/0n0pypp5257718fhxvy7frfh0000gn/T/redex-gdb-x2kc4qnp.sh or under lldb by running /var/folders/58/0n0pypp5257718fhxvy7frfh0000gn/T/redex-lldb-ux2zwbin.sh

**Comment by NTillmann** [comment]
So it seems like you could workaround the first error:
```
[ERROR ] Expecting value: line 9 column 45 (char 212)
```

But what remains is the second error:
```
error: No ProGuard keep rules provided. Redex optimizations will not preserve semantics without accurate keep rules.
```

You need to provide ProGuard keep rules.

**Comment by lybill** [comment]
> So it seems like you could workaround the first error:
> 
> ```
> [ERROR ] Expecting value: line 9 column 45 (char 212)
> ```
> 
> But what remains is the second error:
> 
> ```
> error: No ProGuard keep rules provided. Redex optimizations will not preserve semantics without accurate keep rules.
> ```
> 
> You need to provide ProGuard keep rules.

How to solve this? I am also facing this problem


`D:\redex\redex\redex.py:24: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  from pipes import quote
[WARNING ] No embedded files, please add manually!
[ERROR   ] expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\redex\redex\redex.py", line 1399, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "D:\redex\redex\pyredex\utils.py", line 62, in with_temp_cleanup
    fn()
  File "D:\redex\redex\redex.py", line 1399, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
                              ^^^^^^^^^^^^^^^
  File "D:\redex\redex\redex.py", line 1365, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "D:\redex\redex\redex.py", line 398, in run_redex_binary
    run()
  File "D:\redex\redex\redex.py", line 377, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 3221225785!`
