### ISSUE TITLE
RedexRunException: redex-all crashed with exit code 1!

### ISSUE THREAD

**Issue by Qin0821** [facebook/redex#779]
Hello, there is a simple demo and a formal project, they have the same signature、 proguard-rules.pro but the same command can be executed on the simple demo, but on the formal project error. Please help to find out what the problem is, thank you!

command:
```
// loans_id/app/proguard-rules.pro == HideU/app/proguard-rules.pro

// simple demo, it work
ANDROID_SDK=/Users/qin/Library/Android/sdk redex --sign -s Loans_IN -a Loans_IN -p 950821 -c /Users/qin/ting/Android/ReDex/redex/config/interdex_stripdebuginfo.config -P /Users/qin/ting/Android/loans/loans_id/app/proguard-rules.pro -o /Users/qin/ting/Android/loans/loans_id/app/release/app-release-out.apk /Users/qin/ting/Android/loans/loans_id/app/release/app-release.apk
// formal project, it not work
ANDROID_SDK=/Users/qin/Library/Android/sdk redex --sign -s Loans_IN -a Loans_IN -p 950821 -c /Users/qin/ting/Android/ReDex/redex/config/interdex_stripdebuginfo.config -P /Users/qin/ting/Amber/HideU/app/proguard-rules.pro -o ~/Desktop/app-release-out.apk /Users/qin/ting/Amber/HideU/app/release/app-arm64-v8a-release.apk
```
interdex_stripdebuginfo.config
```
{
    "redex" : {
        "passes" : [
            "StripDebugInfoPass",
            "InterDexPass",
            "RegAllocPass"
        ]
    },
    "StripDebugInfoPass" : {
        "drop_all_dbg_info" : false,
        "drop_local_variables" : true,
        "drop_line_numbers" : false,
        "drop_src_files" : false,
        "use_whitelist" : false,
        "cls_whitelist" : [],
        "method_whitelist" : [],
        "drop_prologue_end" : true,
        "drop_epilogue_begin" : true,
        "drop_all_dbg_info_if_empty" : true
    },
    "InterDexPass" : {
        "minimize_cross_dex_refs": true,
        "minimize_cross_dex_refs_method_ref_weight": 100,
        "minimize_cross_dex_refs_field_ref_weight": 90,
        "minimize_cross_dex_refs_type_ref_weight": 100,
        "minimize_cross_dex_refs_string_ref_weight": 90
    },
    "RegAllocPass" : {
        "live_range_splitting": false
    },
    "string_sort_mode" : "class_order",
    "bytecode_sort_mode" : "class_order"
}
```
```
/tmp/redex.MrCBZS/redex.py:24: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  from pipes import quote
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
Ignoring -repackageclasses 'ambercore'
20: # hide the original source file name.
21: #-renamesourcefileattribute SourceFile
22: -repackageclasses !>identifier: 'ambercore'<!
23: -obfuscationdictionary identifier: dic.txt
24: -classobfuscationdictionary identifier: dic.txt
Unimplemented command (skipping): -obfuscationdictionary at line 23
21: #-renamesourcefileattribute SourceFile
22: -repackageclasses identifier: 'ambercore'
23: !>-obfuscationdictionary<! identifier: dic.txt
24: -classobfuscationdictionary identifier: dic.txt
25: -packageobfuscationdictionary identifier: dic.txt
Unimplemented command (skipping): -classobfuscationdictionary at line 24
22: -repackageclasses identifier: 'ambercore'
23: -obfuscationdictionary identifier: dic.txt
24: !>-classobfuscationdictionary<! identifier: dic.txt
25: -packageobfuscationdictionary identifier: dic.txt
26: -keepclasseswithmembernames class identifier: * {
Unimplemented command (skipping): -packageobfuscationdictionary at line 25
23: -obfuscationdictionary identifier: dic.txt
24: -classobfuscationdictionary identifier: dic.txt
25: !>-packageobfuscationdictionary<! identifier: dic.txt
26: -keepclasseswithmembernames class identifier: * {
27: native identifier: <methods> ;
Unimplemented command (skipping): -ignorewarnings at line 126
124: filter: org.apache.** # ADD BY GONGWEN 解决混淆后编译失败问题
125: -dontwarn
126: filter: com.spirit.ads.avazusdk.** !>-ignorewarnings<!
Unimplemented command (skipping): -if at line 453
451: filter: retrofit2.KotlinExtensions$* # With R8 full mode, it sees no subtypes of Retrofit interfaces since they are created with a Proxy
452: # and replaces all potential values with null. Explicitly keeping the interfaces prevents this.
453: !>-if<! interface identifier: * { @ identifier: retrofit2.http.* identifier: <methods> ; }
454: -keep , allowobfuscation interface identifier: <1>
Unimplemented command (skipping): -if at line 457
456: # Keep inherited services.
457: !>-if<! interface identifier: * { @ identifier: retrofit2.http.* identifier: <methods> ; }
458: -keep , allowobfuscation interface identifier: * extends identifier: <1>
Unimplemented command (skipping): -ignorewarnings at line 526
524: filter: org.apache.** # ADD BY GONGWEN 解决混淆后编译失败问题
525: -dontwarn
526: filter: com.spirit.ads.avazusdk.** !>-ignorewarnings<!
        Parsed ProGuard config file completed in 0.0 seconds
        Load classes from dexes completed in 1.0 seconds
        Load library jars completed in 0.7 seconds
        Deobfuscating dex elements completed in 0.2 seconds
        No Optimizations Rules completed in 0.0 seconds
            Mark keep-methods completed in 0.0 seconds
            Computing XML reachability completed in 0.1 seconds
            Computing native reachability completed in 0.0 seconds
            Analyzing reflection completed in 0.1 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 0.3 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.9 seconds
            Process keep for classes with native members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 1.0 seconds
    Redex_frontend completed in 3.3 seconds
        API Level Checker completed in 0.1 seconds
WARNING: No inliner config
Evaluating StripDebugInfoPass...
        StripDebugInfoPass (eval) completed in 0.0 seconds
Evaluating InterDexPass...
        InterDexPass (eval) completed in 0.0 seconds
Evaluating RegAllocPass...
        RegAllocPass (eval) completed in 0.0 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 2.8 seconds
Inconsistency found in Dex code for Lcom/google/android/gms/internal/ads/zzcmm;.shouldInterceptRequest:(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Landroid/webkit/WebResourceResponse;
 Encountered [0x60000580f2c0] OPCODE: MOVE_RESULT_OBJECT v1 without appropriate prefix instruction. Expected invoke or filled-new-array, got RETURN_OBJECT v1
Code:
[0x60000580fa00] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v5
[0x60000580f900] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v6
[0x60000580f4a0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v7
[0x60000580f460] OPCODE: CONST_STRING "AdMob|SafeDK: Execution> Lcom/google/android/gms/internal/ads/zzcmm;->shouldInterceptRequest(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Landroid/webkit/WebResourceResponse;"
[0x60000580f200] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x60000580f440] OPCODE: INVOKE_STATIC v0, Lcom/safedk/android/utils/Logger;.d:(Ljava/lang/String;)I
[0x60000580f400] OPCODE: CONST_STRING "com.google.ads"
[0x60000580f160] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x60000580f3e0] OPCODE: INVOKE_VIRTUAL v5, v6, v7, Lcom/google/android/gms/internal/ads/zzcmm;.safedk_zzcmm_shouldInterceptRequest_8234d07f8f01e5056b10728e57fae741:(Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;)Landroid/webkit/WebResourceResponse;
[0x60000580f3a0] OPCODE: MOVE_RESULT_OBJECT v2
[0x60000580f380] OPCODE: CONST_STRING "com.google.ads"
[0x60000580f0a0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x60000580f340] OPCODE: INVOKE_STATIC v0, v6, v7, v2, Lcom/safedk/android/analytics/brandsafety/creatives/CreativeInfoManager;.onWebViewResponseWithHeaders:(Ljava/lang/String;Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;Landroid/webkit/WebResourceResponse;)Landroid/webkit/WebResourceResponse;
[0x60000580f320] OPCODE: MOVE_RESULT_OBJECT v1
[0x60000580f2e0] OPCODE: RETURN_OBJECT v1
[0x60000580f2c0] OPCODE: MOVE_RESULT_OBJECT v1
[0x60000580f280] OPCODE: RETURN_OBJECT v1

(6 more issues!)
 If you are confident that this does not matter (e.g., because you are using MakePublicPass), turn off accessibility checking on input with `-J ir_type_checker.run_on_input_ignore_access=true`.
 You may turn off all input checking with `-J ir_type_checker.run_on_input=false`.
Traceback (most recent call last):
  File "/tmp/redex.MrCBZS/redex.py", line 1399, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.MrCBZS/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/tmp/redex.MrCBZS/redex.py", line 1399, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
                              ^^^^^^^^^^^^^^^
  File "/tmp/redex.MrCBZS/redex.py", line 1365, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/tmp/redex.MrCBZS/redex.py", line 398, in run_redex_binary
    run()
  File "/tmp/redex.MrCBZS/redex.py", line 391, in run
    raise RedexRunException(msg, returncode, abort_error, symbolized)
RedexRunException: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.MrCBZS/redex-gdb-zucn8ipd.sh or under lldb by running /tmp/redex.MrCBZS/redex-lldb-xy3mmo5t.sh
```

**Comment by agampe** [comment]
This says the input code to Redex is invalid and does not adhere to the dex specification. The type checker failed before any Redex optimizations. This means that the app is illegal, and parts of it will fail either at install time or runtime.

In this case, look at the end:
```
[0x60000580f340] OPCODE: INVOKE_STATIC v0, v6, v7, v2, Lcom/safedk/android/analytics/brandsafety/creatives/CreativeInfoManager;.onWebViewResponseWithHeaders:(Ljava/lang/String;Landroid/webkit/WebView;Landroid/webkit/WebResourceRequest;Landroid/webkit/WebResourceResponse;)Landroid/webkit/WebResourceResponse;
[0x60000580f320] OPCODE: MOVE_RESULT_OBJECT v1
[0x60000580f2e0] OPCODE: RETURN_OBJECT v1
[0x60000580f2c0] OPCODE: MOVE_RESULT_OBJECT v1
```
`MOVE_RESULT_OBJECT` is only allowed to directly follow an instruction that sets the result register (invokes, check-cast, stuff like that).
