### ISSUE TITLE
After redex, some content of drawable file becomes "<x/>"

### ISSUE THREAD

**Issue by pidanxiangjiao** [facebook/redex#787]
1. I use below config file:
```
{
  "redex" : {
    "passes" : [
      "MakePublicPass",
      "StripDebugInfoPass",
      "RegAllocPass"
    ]
  },
  "inliner": {
    "throws": false,
    "multiple_callers": true,
    "blocklist": [],
    "no_inline_annos" : [
    ]
  },
  "RegAllocPass" : {
    "live_range_splitting": false
  },
  "StripDebugInfoPass" : {
    "drop_all_dbg_info" : false,
    "drop_local_variables" : true,
    "drop_line_numbers" : true,
    "drop_src_files" : true,
    "use_allowlist" : false,
    "cls_allowlist" : [],
    "method_allowlist" : [],
    "drop_prologue_end" : true,
    "drop_epilogue_begin" : true,
    "drop_all_dbg_info_if_empty" : true
  },
  "keep_packages": [

  ],
  "debug_info_kind": "no_custom_symbolication",
  "method_move_map" : "redex-moved-methods-map.txt",
  "string_sort_mode" : "class_order",
  "bytecode_sort_mode" : ["method_similarity_order", "class_order"],
  "ir_type_checker": {
    "run_after_each_pass" : true,
    "verify_moves" : false
  }
}

```

2.after redex, i install the new apk file and crash happen
and i analyze the crash log then find content of some drawable file becomes "x"
so it cause the crash.

the content is like below:
```
<?xml version="1.0" encoding="utf-8"?>
<x/>
```

3.I also find when i install the apk after redex by "adb install" command,i get error message like:
```
Performing Incremental Install
Serving...

Exception occurred while executing 'install-incremental':
java.lang.IllegalArgumentException: Incremental installation not allowed.
        at com.android.server.pm.PackageInstallerSession.<init>(PackageInstallerSession.java:1026)
        at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:1046)
        at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:676)
        at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3512)
        at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1480)
        at com.android.server.pm.PackageManagerShellCommand.runIncrementalInstall(PackageManagerShellCommand.java:1438)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:238)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6922)
        at android.os.Binder.shellCommand(Binder.java:1085)
        at android.os.Binder.onTransact(Binder.java:903)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4909)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6906)
        at android.os.Binder.execTransactInternal(Binder.java:1321)
        at android.os.Binder.execTransact(Binder.java:1280)
Performing Streamed Install
Success
```

Is there anything wrong when i execute the redex operation?
the redex log is below, it seems there is no error.
```
Evaluating MakePublicPass...
Evaluating StripDebugInfoPass...
Evaluating RegAllocPass...
Note: input type checking is turned off!
Running MakePublicPass...
Running IRTypeChecker...
Running StripDebugInfoPass...
Running IRTypeChecker...
Running RegAllocPass...
Running IRTypeChecker...
All opt passes are done, clear cfg

Running IRTypeChecker...
String storage @ 12 hardware concurrency:
  small: 11 containers with 2013 buffers, 32808808 / 32980992 bytes used / allocated (99%%), 461 / 461 times waited / contended, 0 times sorted
  medium: 11 containers with 504 buffers, 32523386 / 33030144 bytes used / allocated (98%%), 54 / 54 times waited / contended, 0 times sorted
  large: 11 containers with 226 buffers, 1239829 / 1239829 bytes used / allocated (100%%), 0 / 0 times waited / contended, 0 times sorted
[DEBUG   ] Dex processing finished in 82.32 seconds
[DEBUG   ] Attempting Env to find zipalign
[DEBUG   ] Android ENV values = ['xxxxxx/sdk']
[DEBUG   ] Filtered ['xxxxxx/sdk'] to ['xxxxxx/sdk'] = ['xxxxxx/sdk']
[DEBUG   ] Android Build Tools base by env = ['xxxxxx/sdk']
[DEBUG   ] max build tools version: 33.0.0
[DEBUG   ] Filtered ['xxxxxx/sdk/build-tools/33.0.0'] to ['xxxxxx/sdk/build-tools/33.0.0'] = ['xxxxxx/sdk/build-tools/33.0.0']
[DEBUG   ] Attempting Env to find apksigner
[DEBUG   ] Android ENV values = ['xxxxxx/sdk']
[DEBUG   ] Filtered ['xxxxxx/sdk'] to ['xxxxxx/sdk'] = ['xxxxxx/sdk']
[DEBUG   ] Android Build Tools base by env = ['xxxxxx/sdk']
[DEBUG   ] max build tools version: 33.0.0
[DEBUG   ] Filtered ['xxxxxx/sdk/build-tools/33.0.0'] to ['xxxxxx/sdk/build-tools/33.0.0'] = ['xxxxxx/sdk/build-tools/33.0.0']
[DEBUG   ] Creating output APK finished in 8.31 seconds
[DEBUG   ] Copying all redex generated artifacts redex-class-rename-map.txt map to output_dir: xxxxxx/redex/redex-class-rename-map.txt
[DEBUG   ] Copying all redex generated artifacts redex-unused-keep-rules.txt map to output_dir: xxxxxx/redex/redex-unused-keep-rules.txt
[DEBUG   ] Copying all redex generated artifacts redex-full-rename-map.txt map to output_dir: xxxxxx/redex/redex-full-rename-map.txt
[DEBUG   ] Copying all redex generated artifacts redex-stats.txt map to output_dir: xxxxxx/redex/redex-stats.txt
[DEBUG   ] Copying all redex generated artifacts redex-bytecode-offset-map.txt map to output_dir:xxxxxx/redex/redex-bytecode-offset-map.txt

```

**Comment by thezhangwei** [comment]
Is it possible for you to share the full input. Which drawable files were modified please?

**Comment by pidanxiangjiao** [comment]
Of course , i could send the input and output through email , please check your mailbox .Thx.
I create a demo project ,and find the same issue,
the reason for content of xml file becomes "<x/>",  i think it is due to r8 compiler ,when i set "shrinkResource " to "true", r8 make useless resources file's content  to be "<x/">
but after redex, the reason to cause app crash ,i guess maybe is there any logic in redex to mixup  xml files' content ?
it means that, after redex , the content of xml a and the content of xml b get swaped.

why i have the guess above, is that ,when i set "shrinkResources" to "false ",  in output apk , "<x/>" not exists any more, but after redex , the final apk still can not run, it gets some error still in xml file , some layout xml file' content becomes the content of drawable file's content, the error info is like "can not find classs  shape ".

In the demo project i sent you:
activity_main.xml  content in origin apk:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" android:layout_width="match_parent" android:layout_height="match_parent">
    <TextView android:id="@+id/tv_name" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Hello World!" app:layout_constraintBottom_toBottomOf="0" app:layout_constraintLeft_toLeftOf="0" app:layout_constraintRight_toRightOf="0" app:layout_constraintTop_toTopOf="0"/>
    <TextView android:id="@+id/tv_name1" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Hello World!" app:layout_constraintBottom_toBottomOf="@+id/tv_name" app:layout_constraintLeft_toLeftOf="0" app:layout_constraintRight_toRightOf="0" app:layout_constraintTop_toTopOf="0"/>
    <TextView android:id="@+id/tv_name2" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Hello World!" app:layout_constraintBottom_toBottomOf="@+id/tv_name1" app:layout_constraintLeft_toLeftOf="0" app:layout_constraintRight_toRightOf="0" app:layout_constraintTop_toTopOf="0"/>
    <ImageView android:layout_width="wrap_content" android:layout_height="wrap_content" app:layout_constraintStart_toStartOf="0" app:layout_constraintTop_toBottomOf="@+id/tv_name2"/>
</androidx.constraintlayout.widget.ConstraintLayout>
```

activity_main.xml  content in apk after redex:
```
<?xml version="1.0" encoding="utf-8"?>
<x/>
```
when i run final apk ,get error:
```
FATAL EXCEPTION: main
Process: com.netease.cloudmusic.agptest, PID: 18388
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.netease.cloudmusic.agptest/com.netease.cloudmusic.bizlib.SecondActivity}: android.view.InflateException: Binary XML file line #1 in com.netease.cloudmusic.agptest:layout/activity_main: Binary XML file line #1 in com.netease.cloudmusic.agptest:layout/activity_main: Error inflating class x
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.view.InflateException: Binary XML file line #1 in com.netease.cloudmusic.agptest:layout/activity_main: Binary XML file line #1 in com.netease.cloudmusic.agptest:layout/activity_main: Error inflating class x
Caused by: android.view.InflateException: Binary XML file line #1 in com.netease.cloudmusic.agptest:layout/activity_main: Error inflating class x
Caused by: java.lang.ClassNotFoundException: android.view.x                                                                                                   

```

**Comment by pidanxiangjiao** [comment]
I debug the python part of redex, and find that when extract the apk , the activity_main.xml's content will become "<x/>",
the activity_main.xml's final name in apk's res folder is R5.xml.
But if i rename the origin apk to zip, and unzip the final, the activity_main.xml(R5.xml)'s content is still correct. 
I use a mac to do this operation, so  there should be a bug in python part when doing the extract operation.

**Comment by pidanxiangjiao** [comment]
> > I debug the python part of redex, and find that when extract the apk , the activity_main.xml's content will become "",
> > the activity_main.xml's final name in apk's res folder is R5.xml.
> 
> It sounded like you were pretty close to locating the problem in code. If so would you mind sharing a code pointer? That should help us to carry forward on our side. Sorry for the delay.

I figure out that it is because the file system i'm using on mac is case insensitive, i create a case sensitive partition , finally the xml content won't get messed up anymore.

**Comment by thezhangwei** [comment]
I'm glad that you figured it out. Closing for now.
