### ISSUE TITLE
Is there any advice to recover crash stack trace line number in android firebase platform after use "StripDebugInfoPass"?

### ISSUE THREAD

**Issue by pidanxiangjiao** [facebook/redex#818]

**Comment by thezhangwei** [comment]
@agampe Hey any comment on this one?

**Comment by agampe** [comment]
Unlikely, you should have considered the likelihood of your APK being broken before shipping an APK without debug info.

Redex is deterministic. You can try to recompile the **exact** source for the crashing APK, disabling the strip pass, then look at the output. If the dex bytecode is the same, you have a starting point.

If the Android version this is crashing on is new enough, in the absence of debug information the Android Runtime will print bytecode offsets. If method names are unique, or if you have multiple but only one has said offset be an instruction, then you can map back.

---

In general, how about you try IODI? We do not have good documentation, but there's tests that show the config, e.g., [here](https://github.com/facebook/redex/blob/5bd7c512a7aa52b71f7122b8f70bfe0f6da8dfcf/test/debug_info/line_map_iodi2.config#L35).

When you output with IODI, debug info is indirected and shared between buckets of methods. The Play Console won't be very helpful, you will have to use the symbolicator provided with Redex to use the stack, APK **and** debug metadata from build time to get things like line numbers.

**Comment by pidanxiangjiao** [comment]
Hello, current i use iodi2 for debug_info_kind and try to recover the stack trace. and i find the line number is a little bit before or after the right place which cause crash.

Am i config right? or iodi2 debug info could be inaccurate in some cases?

the config i use:
```
  "redex": {
    "passes": [
      "RegAllocPass",
      "ReduceGotosPass"
    ]
  },
    "StripDebugInfoPass": {
    "drop_all_dbg_info": false,
    "drop_local_variables": true,
    "drop_line_numbers": false,
    "drop_src_files": false,
    "use_allowlist": false,
    "cls_allowlist": [
      
    ],
    "drop_synth_aggressive": false,
    "drop_synth_conservative": true,
    "method_allowlist": [
      
    ],
    "drop_prologue_end": true,
    "drop_epilogue_begin": true,
    "drop_all_dbg_info_if_empty": true
  },
  "debug_info_kind": "iodi2",


inaccurate stack trace i recovered, and i saw some weired string like "$b864950c85edb00b67f99fa920190c50c59eaef6472a5a4ce92c09f8e6b9132e$0.run$bridge", there is no such string when i recover the stack from aab that is not be redexed.
```
2024-07-04 21:00:42.056  1454-1598  AndroidRuntime          com.netease.cloudmusic.agptest       E  FATAL EXCEPTION: pool-5-thread-1
                                                                                                    Process: com.netease.cloudmusic.agptest, PID: 1454
                                                                                                    java.lang.NullPointerException
                                                                                                        at com.netease.cloudmusic.agptest.HelperImp.save(HelperImp.java:14)
                                                                                                        at com.netease.cloudmusic.agptest.HelperImp.save(HelperImp.java:8)
                                                                                                        at com.netease.cloudmusic.agptest.BUtils.save(BUtils.java:59)
                                                                                                        at com.netease.cloudmusic.agptest.BUtils.lambda$init$0(BUtils.java:34)
                                                                                                        at androidx.fragment.app.SpecialEffectsController$$InternalSyntheticLambda$1$b864950c85edb00b67f99fa920190c50c59eaef6472a5a4ce92c09f8e6b9132e$0.run$bridge(SpecialEffectsController$$InternalSyntheticLambda$1$b864950c85edb00b67f99fa920190c50c59eaef6472a5a4ce92c09f8e6b9132e.java:90)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)

```
