### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decompressobj'

### ISSUE THREAD

**Issue by durunvo** [facebook/redex#86]
I finally complete sudo make install successfully after stuck at every single step.
But now when trying to redex the .apk this show up.

````
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 793, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 686, in run_redex
    extract_apk(args.input_apk, extracted_apk_dir)
  File "/usr/local/bin/redex", line 213, in extract_apk
    z.extractall(destination_directory)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 1240, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 1228, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 1290, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 1210, in open
    close_fileobj=not self._filePassed)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 651, in __init__
    self._decompressor = _get_decompressor(self._compress_type)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 614, in _get_decompressor
    return zlib.decompressobj(-15)
AttributeError: 'NoneType' object has no attribute 'decompressobj'
````

Any idea?

**Comment by bertmaher** [comment]
What command line are you using to run redex?  It looks like there's some error deep in the zipfile module.

**Comment by durunvo** [comment]
<img width="609" alt="screen shot 2559-04-19 at 11 40 30 am" src="https://cloud.githubusercontent.com/assets/5458194/14627949/8f595e70-0623-11e6-99d5-36c6d8055cb0.png">

**Comment by yemengsky** [comment]
I have the same problem .

**Comment by yemengsky** [comment]
@durunvo @bertmaher Hello, the problem can be soled by the following 
`xcode-select --install
brew reinstall python3`
The error is leaded by the missing of zlib in python .

**Comment by bertmaher** [comment]
@yemengsky thanks for solving it!
