### ISSUE TITLE
Illegal class access

### ISSUE THREAD

**Issue by w4lle** [facebook/redex#89]
run app with redex and without Proguard
and I use the --sign commond to resign the apk
crash log :

```
AndroidRuntime: FATAL EXCEPTION: main
       Process: com.boohee.one, PID: 30145
        java.lang.IllegalAccessError: Illegal class access: 'me.nereo.multi_image_selector.R' attempting to access 'com.handmark.pulltorefresh.library.OverscrollHelper$1' (declaration of 'me.nereo.multi_image_selector.R' appears in /data/app/com.boohee.one-1/base.apk)
        at me.nereo.multi_image_selector.R.overScrollBy(me.nereo.multi_image_selector.R some line)
        at me.nereo.multi_image_selector.R.overScrollBy(me.nereo.multi_image_selector.R some line)
        at com.handmark.pulltorefresh.library.PullToRefreshScrollView$InternalScrollViewSDK9.overScrollBy(titleEditText:91)
        at android.widget.ScrollView.onTouchEvent(ScrollView.java:711)
        at android.view.View.dispatchTouchEvent(View.java:8461)
```

**Comment by tiffyangel89** [comment]
What is this shit?

**Comment by w4lle** [comment]
I use the InterDexPass, and product my app's classes list, and the config file like this
```
{
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "BridgePass",
      "SynthPass",
      "FinalInlinePass",
      "DelSuperPass",
      "SingleImplPass",
      "SimpleInlinePass",
      "StaticReloPass",
      "RemoveEmptyClassesPass",
      "ShortenSrcStringsPass",
      "InterDexPass"
    ]
   },
   "InterDexPass" : {
	"coldstart_classes" : "list_of_classes.txt"
  }
}
```

but the issue still here
it seems access the method of class which does not accessed right now
what's wrong about it?

**Comment by w4lle** [comment]
is same issue with #30 ?
but #30 is not solved now.

**Comment by huyongli** [comment]
Do you solved now ? @w4lle

**Comment by bertmaher** [comment]
#30 is solved as of a few minutes ago, thanks for reporting
