### ISSUE TITLE
dump_classes_from_hprof.py error

### ISSUE THREAD

**Issue by supercocoa** [facebook/redex#97]
``` shell
python $REDEX/tools/hprof/dump_classes_from_hprof.py --hprof SOMEDUMP.hprof > list_of_classes.txt
Traceback (most recent call last):
  File "/Users/xx/workspace/android/lib/redex/tools/hprof/dump_classes_from_hprof.py", line 19, in <module>
    import enum
ImportError: No module named enum
```

``` shell
python3 $REDEX/tools/hprof/dump_classes_from_hprof.py --hprof SOMEDUMP.hprof > list_of_classes.txt
Traceback (most recent call last):
  File "/Users/xx/workspace/android/lib/redex/tools/hprof/dump_classes_from_hprof.py", line 1261, in <module>
    hp = parse_filename(args.hprof)
  File "/Users/xx/workspace/android/lib/redex/tools/hprof/dump_classes_from_hprof.py", line 53, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "/Users/x/workspace/android/lib/redex/tools/hprof/dump_classes_from_hprof.py", line 30, in parse_hprof_dump
    tag = reduce(operator.concat, iter_until_null, '')
NameError: name 'reduce' is not defined
```

**Comment by bashrc-real** [comment]
enum module was backported to python 2.7 https://www.python.org/dev/peps/pep-0435/
You can try installing the module manually. 
I have tried making changes to the script so that it is compatible with both python 2.x and python 3 with pr #97

**Comment by onomatopoeia** [comment]
Testing the PR I'm seeing an error when running against a heap dump from open street maps. Investigating...

**Comment by w4lle** [comment]
@bashrc-real 
I have checkout your repo patch-3 branch, it still have this error
```
redex git:(patch-3)>python tools/hprof/dump_classes_from_hprof.py --hprof ~/Desktop/SOMEDUMP.hprof > ~/Desktop/list_of_classes.txt
Traceback (most recent call last):
  File "tools/hprof/dump_classes_from_hprof.py", line 19, in <module>
    import enum
ImportError: No module named enum
```

and i install enum34 manually by ``sudo pip install enum34``
 it's ok.

**Comment by bashrc-real** [comment]
@w4lle My fix makes the script compatible with python3 which is the second part mentioned in the problem description (Or atleast attempts to, check the PR comments for the issues that have been discovered)

**Comment by shmuelr** [comment]
Just to chime in, I'm having the same issue...

**Comment by bashrc-real** [comment]
@shmuelr did you try my patch? Can you share the hprof if it's not working with my changes with python3?

**Comment by shmuelr** [comment]
@bashrc-real I did try the patch, (was about to post this over there). I got a different error now 
Traceback (most recent call last):
  File "/Users/shmuelr/dev/redex/tools/hprof/dump_classes_from_hprof.py", line 1268, in <module>
    hp = parse_filename(args.hprof)
  File "/Users/shmuelr/dev/redex/tools/hprof/dump_classes_from_hprof.py", line 54, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "/Users/shmuelr/dev/redex/tools/hprof/dump_classes_from_hprof.py", line 42, in parse_hprof_dump
    record = Record.read_from_stream(hprof_data, instream)
  File "/Users/shmuelr/dev/redex/tools/hprof/dump_classes_from_hprof.py", line 178, in read_from_stream
    return hprof_data.parse_heap_dump_segment_record(tag=tag, time_offset_us=time_offset_us, data=data)
  File "/Users/shmuelr/dev/redex/tools/hprof/dump_classes_from_hprof.py", line 787, in parse_heap_dump_segment_record
    heap_tag = HeapTag(byte_stream.next_byte())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py", line 235, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py", line 470, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: -117 is not a valid HeapTag

**Comment by bashrc-real** [comment]
@shmuelr would it be possible for you to share the input hprof file?

**Comment by shmuelr** [comment]
Yah. I'm about to take off on a flight, but I'll try mid air

**Comment by shmuelr** [comment]
So I can't upload the hprof file right now, (Jet Blue's wifi is sooo slow). But I was able to make the current script if I used pip to install the enum34 lib.

**Comment by justinjhendrick** [comment]
closing due to age
