### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by Hesamedin** [facebook/redex#98]
Hi, I followed what readme files says in order to install Redex. Seems has been done successfully.

Last command of `Test` section is `$ make check`. This is the error I get.
```
hesam: redex (master) $ cd test/
hesam: test (master) $ make check
Making check in .
make[1]: Entering directory `/home/hesam/android/projects/redex/test'
make  libgtest_main.la
make[2]: Entering directory `/home/hesam/android/projects/redex/test'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include   -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest-all.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest-all.Tpo -c -o gtest-1.7.0/src/libgtest_main_la-gtest-all.lo `test -f 'gtest-1.7.0/src/gtest-all.cc' || echo './'`gtest-1.7.0/src/gtest-all.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest-all.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest-all.Tpo -c gtest-1.7.0/src/gtest-all.cc  -fPIC -DPIC -o gtest-1.7.0/src/.libs/libgtest_main_la-gtest-all.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest-all.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest-all.Tpo -c gtest-1.7.0/src/gtest-all.cc -o gtest-1.7.0/src/libgtest_main_la-gtest-all.o >/dev/null 2>&1
mv -f gtest-1.7.0/src/.deps/libgtest_main_la-gtest-all.Tpo gtest-1.7.0/src/.deps/libgtest_main_la-gtest-all.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include   -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest_main.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest_main.Tpo -c -o gtest-1.7.0/src/libgtest_main_la-gtest_main.lo `test -f 'gtest-1.7.0/src/gtest_main.cc' || echo './'`gtest-1.7.0/src/gtest_main.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest_main.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest_main.Tpo -c gtest-1.7.0/src/gtest_main.cc  -fPIC -DPIC -o gtest-1.7.0/src/.libs/libgtest_main_la-gtest_main.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Igtest-1.7.0 -Igtest-1.7.0/src -Igtest-1.7.0/include -g -O2 -MT gtest-1.7.0/src/libgtest_main_la-gtest_main.lo -MD -MP -MF gtest-1.7.0/src/.deps/libgtest_main_la-gtest_main.Tpo -c gtest-1.7.0/src/gtest_main.cc -o gtest-1.7.0/src/libgtest_main_la-gtest_main.o >/dev/null 2>&1
mv -f gtest-1.7.0/src/.deps/libgtest_main_la-gtest_main.Tpo gtest-1.7.0/src/.deps/libgtest_main_la-gtest_main.Plo
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2   -o libgtest_main.la  gtest-1.7.0/src/libgtest_main_la-gtest-all.lo gtest-1.7.0/src/libgtest_main_la-gtest_main.lo  -lz 
libtool: link: ar cru .libs/libgtest_main.a gtest-1.7.0/src/.libs/libgtest_main_la-gtest-all.o gtest-1.7.0/src/.libs/libgtest_main_la-gtest_main.o 
libtool: link: ranlib .libs/libgtest_main.a
libtool: link: ( cd ".libs" && rm -f "libgtest_main.la" && ln -s "../libgtest_main.la" "libgtest_main.la" )
make[2]: Leaving directory `/home/hesam/android/projects/redex/test'
make[1]: Leaving directory `/home/hesam/android/projects/redex/test'
Making check in integ
make[1]: Entering directory `/home/hesam/android/projects/redex/test/integ'
make  synth_test empty_classes_test
make[2]: Entering directory `/home/hesam/android/projects/redex/test/integ'
depbase=`echo SynthTest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DHAVE_CONFIG_H -I. -I../..  -I../../test/gtest-1.7.0/include -I../../configparser -I../../include -I../../liblocator -I../../libresource -I../../libresource/android -I../../libresource/androidfw -I../../libresource/cutils -I../../libresource/system -I../../libresource/utils -I../../opt -I../../opt/all-static -I../../opt/annoclasskill -I../../opt/annokill -I../../opt/bridge -I../../opt/delinit -I../../opt/delsuper -I../../opt/final_inline -I../../opt/interdex -I../../opt/local-dce -I../../opt/peephole -I../../opt/rebindrefs -I../../opt/remove_empty_classes -I../../opt/renameclasses -I../../opt/shorten-srcstrings -I../../opt/simpleinline -I../../opt/singleimpl -I../../opt/static-sink -I../../opt/staticrelo -I../../opt/synth -I../../opt/unterface -I../../tools/redex-all -I../../third-party/folly -I../../util  --std=gnu++11 -g -O2 -MT SynthTest.o -MD -MP -MF $depbase.Tpo -c -o SynthTest.o SynthTest.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
mkdir -p synth-test-class
javac -d synth-test-class Alpha.java SynthTest.java
jar cf synth-test-class.jar -C synth-test-class .
dx --dex --output=synth-test-class.dex synth-test-class.jar
/bin/bash: dx: command not found
make[2]: *** [synth-test-class.dex] Error 127
make[2]: Leaving directory `/home/hesam/android/projects/redex/test/integ'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/hesam/android/projects/redex/test/integ'
make: *** [check-recursive] Error 1
```

After that I tried to test `Redex` command however I got following error:
```
hesam: test (master) $ cd ..
hesam: redex (master) $ redex ~/Desktop/01.apk -o ~/Desktop/02.apk
/usr/local/bin/redex-all: error while loading shared libraries: libfolly.so.57: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 793, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 749, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 116, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /tmp/tmp8d9v3whh.redex_extracted_apk --outdir /tmp/tmpecikulxm.redex_dexen /tmp/tmpecikulxm.redex_dexen/dex0/classes.dex /tmp/tmpecikulxm.redex_dexen/dex1/classes2.dex' returned non-zero exit status 127
hesam: redex (master) $
```
Hope the log helps. Thanks.

**Comment by shanenay** [comment]
"dx" is part of the Android SDK.  You have to add the Android SDK to your PATH environment variable.

**Comment by Hesamedin** [comment]
@shanenay Thanks but ya, I defiantly have following path in my `.profile` .
```
export ANDROID_HOME=~/android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```

**Comment by shanenay** [comment]
@Hesamedin 

Ah, yea, but dx isn't in either of those places :).

It's looking for ANDROID_SDK, not ANDROID_HOME.  That's the problem looks like.  Add export ANDROID_SDK=$(ANDROID_HOME).  I'm not sure what the default install script does, the one we're using makes both of them alias to the same place.

**Comment by Hesamedin** [comment]
@shanenay, Thanks for your help. I just added the line.
```
export ANDROID_HOME=~/android/sdk
export ANDROID_SDK=$ANDROID_HOME
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```
However I'm getting same result when I run `make check` in test folder. Do you mean I have to add `dx` path which is `/home/hesam/android/sdk/build-tools/23.0.2` into my PATH?
http://stackoverflow.com/a/20705952/513413

**Comment by Hesamedin** [comment]
I just added `dx` path into my PATH.
```
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
```

After running 'make check' in test directory the error changed to this:
```
hesam: test (master) $ make check
Making check in .
make[1]: Entering directory `/home/hesam/android/projects/redex/test'
make  libgtest_main.la
make[2]: Entering directory `/home/hesam/android/projects/redex/test'
make[2]: `libgtest_main.la' is up to date.
make[2]: Leaving directory `/home/hesam/android/projects/redex/test'
make[1]: Leaving directory `/home/hesam/android/projects/redex/test'
Making check in integ
make[1]: Entering directory `/home/hesam/android/projects/redex/test/integ'
make  synth_test empty_classes_test
make[2]: Entering directory `/home/hesam/android/projects/redex/test/integ'
dx --dex --output=synth-test-class.dex synth-test-class.jar

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:752)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:672)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
	at com.android.dx.command.dexer.Main.processClass(Main.java:749)
	... 12 more
1 error; aborting
make[2]: *** [synth-test-class.dex] Error 1
make[2]: Leaving directory `/home/hesam/android/projects/redex/test/integ'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/hesam/android/projects/redex/test/integ'
make: *** [check-recursive] Error 1
```

**Comment by shanenay** [comment]
Turned out Hesam needed to run "sudo ldconfig".  Will add this to the README.

**Comment by shanenay** [comment]
Added to FAQ section in the README.md .  We can't add it to the install-hook because it will break other platforms.  Only some distros seem effected and after thinking through various potential solutions, an FAQ line seemed the only reasonable approach.

**Comment by WillSprint** [comment]
the same issue bug i can't find FAQ in the README.md
